/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AnonymousAccessCredential : Access credential with no credentials
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnonymousAccessCredential {
    #[serde(rename = "credentialType")]
    pub credential_type: models::DataReferenceCredentialType,
}

impl AnonymousAccessCredential {
    /// Access credential with no credentials
    pub fn new(credential_type: models::DataReferenceCredentialType) -> AnonymousAccessCredential {
        AnonymousAccessCredential {
            credential_type,
        }
    }
}

