/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AssetJobOutput : Asset output type.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetJobOutput {
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<models::OutputDeliveryMode>,
    /// Output Asset URI.
    #[serde(rename = "uri", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub uri: Option<Option<String>>,
}

impl AssetJobOutput {
    /// Asset output type.
    pub fn new() -> AssetJobOutput {
        AssetJobOutput {
            mode: None,
            uri: None,
        }
    }
}

