/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AutoSeasonality {
    #[serde(rename = "mode")]
    pub mode: models::SeasonalityMode,
}

impl AutoSeasonality {
    pub fn new(mode: models::SeasonalityMode) -> AutoSeasonality {
        AutoSeasonality {
            mode,
        }
    }
}

