/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ComponentVersion : Definition of a component version: defines resources that span component types.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComponentVersion {
    /// Defines Component definition details.  <see href=\"https://docs.microsoft.com/en-us/azure/machine-learning/reference-yaml-component-command\" />
    #[serde(rename = "componentSpec", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub component_spec: Option<Option<serde_json::Value>>,
    #[serde(rename = "provisioningState", skip_serializing_if = "Option::is_none")]
    pub provisioning_state: Option<models::AssetProvisioningState>,
    /// If the name version are system generated (anonymous registration).
    #[serde(rename = "isAnonymous", skip_serializing_if = "Option::is_none")]
    pub is_anonymous: Option<bool>,
    /// Is the asset archived?
    #[serde(rename = "isArchived", skip_serializing_if = "Option::is_none")]
    pub is_archived: Option<bool>,
    /// The asset description text.
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    /// The asset property dictionary.
    #[serde(rename = "properties", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Option<std::collections::HashMap<String, String>>>,
    /// Tag dictionary. Tags can be added, removed, and updated.
    #[serde(rename = "tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Option<std::collections::HashMap<String, String>>>,
}

impl ComponentVersion {
    /// Definition of a component version: defines resources that span component types.
    pub fn new() -> ComponentVersion {
        ComponentVersion {
            component_spec: None,
            provisioning_state: None,
            is_anonymous: None,
            is_archived: None,
            description: None,
            properties: None,
            tags: None,
        }
    }
}

