/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateMonitorAction {
    #[serde(rename = "monitorDefinition")]
    pub monitor_definition: Box<models::MonitorDefinition>,
    #[serde(rename = "actionType")]
    pub action_type: models::ScheduleActionType,
}

impl CreateMonitorAction {
    pub fn new(monitor_definition: models::MonitorDefinition, action_type: models::ScheduleActionType) -> CreateMonitorAction {
        CreateMonitorAction {
            monitor_definition: Box::new(monitor_definition),
            action_type,
        }
    }
}

