/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DatastoreCredentials : Base definition for datastore credentials.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "credentialsType")]
pub enum DatastoreCredentials {
    #[serde(rename="AccountKeyDatastoreCredentials")]
    AccountKeyDatastoreCredentials {
    },
    #[serde(rename="CertificateDatastoreCredentials")]
    CertificateDatastoreCredentials {
    },
    #[serde(rename="NoneDatastoreCredentials")]
    NoneDatastoreCredentials {
    },
    #[serde(rename="SasDatastoreCredentials")]
    SasDatastoreCredentials {
    },
    #[serde(rename="ServicePrincipalDatastoreCredentials")]
    ServicePrincipalDatastoreCredentials {
    },
}

impl Default for DatastoreCredentials {
    fn default() -> Self {
        Self::AccountKeyDatastoreCredentials {
        }
        
    }
}


