/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DataQualityMonitoringSignal {
    /// A dictionary that maps feature names to their respective data types.
    #[serde(rename = "featureDataTypeOverride", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feature_data_type_override: Option<Option<std::collections::HashMap<String, models::MonitoringFeatureDataType>>>,
    #[serde(rename = "featureImportanceSettings", skip_serializing_if = "Option::is_none")]
    pub feature_importance_settings: Option<Box<models::FeatureImportanceSettings>>,
    #[serde(rename = "features", skip_serializing_if = "Option::is_none")]
    pub features: Option<Box<models::MonitoringFeatureFilterBase>>,
    /// [Required] A list of metrics to calculate and their associated thresholds.
    #[serde(rename = "metricThresholds")]
    pub metric_thresholds: Vec<models::DataQualityMetricThresholdBase>,
    #[serde(rename = "productionData")]
    pub production_data: Box<models::MonitoringInputDataBase>,
    #[serde(rename = "referenceData")]
    pub reference_data: Box<models::MonitoringInputDataBase>,
    /// The current notification mode for this signal.
    #[serde(rename = "notificationTypes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub notification_types: Option<Option<Vec<models::MonitoringNotificationType>>>,
    /// Property dictionary. Properties can be added, but not removed or altered.
    #[serde(rename = "properties", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Option<std::collections::HashMap<String, String>>>,
    #[serde(rename = "signalType")]
    pub signal_type: models::MonitoringSignalType,
}

impl DataQualityMonitoringSignal {
    pub fn new(metric_thresholds: Vec<models::DataQualityMetricThresholdBase>, production_data: models::MonitoringInputDataBase, reference_data: models::MonitoringInputDataBase, signal_type: models::MonitoringSignalType) -> DataQualityMonitoringSignal {
        DataQualityMonitoringSignal {
            feature_data_type_override: None,
            feature_importance_settings: None,
            features: None,
            metric_thresholds,
            production_data: Box::new(production_data),
            reference_data: Box::new(reference_data),
            notification_types: None,
            properties: None,
            signal_type,
        }
    }
}

