/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DestinationAsset : Publishing destination registry asset information
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DestinationAsset {
    /// Destination asset name
    #[serde(rename = "destinationName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub destination_name: Option<Option<String>>,
    /// Destination asset version
    #[serde(rename = "destinationVersion", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub destination_version: Option<Option<String>>,
    /// Destination registry name
    #[serde(rename = "registryName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub registry_name: Option<Option<String>>,
}

impl DestinationAsset {
    /// Publishing destination registry asset information
    pub fn new() -> DestinationAsset {
        DestinationAsset {
            destination_name: None,
            destination_version: None,
            registry_name: None,
        }
    }
}

