/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EarlyTerminationPolicyType : EarlyTerminationPolicyType enum
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum EarlyTerminationPolicyType {
    #[serde(rename = "Bandit")]
    Bandit,
    #[serde(rename = "MedianStopping")]
    MedianStopping,
    #[serde(rename = "TruncationSelection")]
    TruncationSelection,
}

impl Default for EarlyTerminationPolicyType {
    fn default() -> Self {
        Self::Bandit
    }
}

impl std::fmt::Display for EarlyTerminationPolicyType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Bandit => write!(f, "Bandit"),
            Self::MedianStopping => write!(f, "MedianStopping"),
            Self::TruncationSelection => write!(f, "TruncationSelection"),
        }
    }
}

impl std::str::FromStr for EarlyTerminationPolicyType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Bandit" => Ok(Self::Bandit),
            "MedianStopping" => Ok(Self::MedianStopping),
            "TruncationSelection" => Ok(Self::TruncationSelection),
            _ => Err(format!("Invalid EarlyTerminationPolicyType: {}", s)),
        }
    }
}
