/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeatureSubset {
    /// [Required] The list of features to include.
    #[serde(rename = "features")]
    pub features: Vec<String>,
    #[serde(rename = "filterType")]
    pub filter_type: models::MonitoringFeatureFilterType,
}

impl FeatureSubset {
    pub fn new(features: Vec<String>, filter_type: models::MonitoringFeatureFilterType) -> FeatureSubset {
        FeatureSubset {
            features,
            filter_type,
        }
    }
}

