/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FeatureImportanceMode : The mode of operation for computing feature importance.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum FeatureImportanceMode {
    #[serde(rename = "Disabled")]
    Disabled,
    #[serde(rename = "Enabled")]
    Enabled,
}

impl Default for FeatureImportanceMode {
    fn default() -> Self {
        Self::Disabled
    }
}

impl std::fmt::Display for FeatureImportanceMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Disabled => write!(f, "Disabled"),
            Self::Enabled => write!(f, "Enabled"),
        }
    }
}

impl std::str::FromStr for FeatureImportanceMode {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Disabled" => Ok(Self::Disabled),
            "Enabled" => Ok(Self::Enabled),
            _ => Err(format!("Invalid FeatureImportanceMode: {}", s)),
        }
    }
}
