/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FixedInputData : Fixed input data definition.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FixedInputData {
    /// Mapping of column names to special uses.
    #[serde(rename = "columns", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub columns: Option<Option<std::collections::HashMap<String, String>>>,
    /// The context metadata of the data source.
    #[serde(rename = "dataContext", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub data_context: Option<Option<String>>,
    #[serde(rename = "inputDataType")]
    pub input_data_type: models::MonitoringInputDataType,
    #[serde(rename = "jobInputType")]
    pub job_input_type: models::JobInputType,
    /// [Required] Input Asset URI.
    #[serde(rename = "uri")]
    pub uri: String,
}

impl FixedInputData {
    /// Fixed input data definition.
    pub fn new(input_data_type: models::MonitoringInputDataType, job_input_type: models::JobInputType, uri: String) -> FixedInputData {
        FixedInputData {
            columns: None,
            data_context: None,
            input_data_type,
            job_input_type,
            uri,
        }
    }
}

