/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ForecastingSettings : Forecasting specific parameters.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ForecastingSettings {
    /// Country or region for holidays for forecasting tasks.  These should be ISO 3166 two-letter country/region codes, for example 'US' or 'GB'.
    #[serde(rename = "countryOrRegionForHolidays", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub country_or_region_for_holidays: Option<Option<String>>,
    /// Number of periods between the origin time of one CV fold and the next fold. For  example, if `CVStepSize` = 3 for daily data, the origin time for each fold will be  three days apart.
    #[serde(rename = "cvStepSize", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cv_step_size: Option<Option<i32>>,
    #[serde(rename = "featureLags", skip_serializing_if = "Option::is_none")]
    pub feature_lags: Option<models::FeatureLags>,
    #[serde(rename = "forecastHorizon", skip_serializing_if = "Option::is_none")]
    pub forecast_horizon: Option<Box<models::ForecastHorizon>>,
    /// When forecasting, this parameter represents the period with which the forecast is desired, for example daily, weekly, yearly, etc. The forecast frequency is dataset frequency by default.
    #[serde(rename = "frequency", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub frequency: Option<Option<String>>,
    #[serde(rename = "seasonality", skip_serializing_if = "Option::is_none")]
    pub seasonality: Option<Box<models::Seasonality>>,
    #[serde(rename = "shortSeriesHandlingConfig", skip_serializing_if = "Option::is_none")]
    pub short_series_handling_config: Option<models::ShortSeriesHandlingConfiguration>,
    #[serde(rename = "targetAggregateFunction", skip_serializing_if = "Option::is_none")]
    pub target_aggregate_function: Option<models::TargetAggregationFunction>,
    #[serde(rename = "targetLags", skip_serializing_if = "Option::is_none")]
    pub target_lags: Option<Box<models::TargetLags>>,
    #[serde(rename = "targetRollingWindowSize", skip_serializing_if = "Option::is_none")]
    pub target_rolling_window_size: Option<Box<models::TargetRollingWindowSize>>,
    /// The name of the time column. This parameter is required when forecasting to specify the datetime column in the input data used for building the time series and inferring its frequency.
    #[serde(rename = "timeColumnName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub time_column_name: Option<Option<String>>,
    /// The names of columns used to group a timeseries. It can be used to create multiple series.  If grain is not defined, the data set is assumed to be one time-series. This parameter is used with task type forecasting.
    #[serde(rename = "timeSeriesIdColumnNames", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub time_series_id_column_names: Option<Option<Vec<String>>>,
    #[serde(rename = "useStl", skip_serializing_if = "Option::is_none")]
    pub use_stl: Option<models::UseStl>,
}

impl ForecastingSettings {
    /// Forecasting specific parameters.
    pub fn new() -> ForecastingSettings {
        ForecastingSettings {
            country_or_region_for_holidays: None,
            cv_step_size: None,
            feature_lags: None,
            forecast_horizon: None,
            frequency: None,
            seasonality: None,
            short_series_handling_config: None,
            target_aggregate_function: None,
            target_lags: None,
            target_rolling_window_size: None,
            time_column_name: None,
            time_series_id_column_names: None,
            use_stl: None,
        }
    }
}

