/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InferenceContainerProperties {
    #[serde(rename = "livenessRoute", skip_serializing_if = "Option::is_none")]
    pub liveness_route: Option<Box<models::Route>>,
    #[serde(rename = "readinessRoute", skip_serializing_if = "Option::is_none")]
    pub readiness_route: Option<Box<models::Route>>,
    #[serde(rename = "startupRoute", skip_serializing_if = "Option::is_none")]
    pub startup_route: Option<Box<models::Route>>,
    #[serde(rename = "scoringRoute", skip_serializing_if = "Option::is_none")]
    pub scoring_route: Option<Box<models::Route>>,
}

impl InferenceContainerProperties {
    pub fn new() -> InferenceContainerProperties {
        InferenceContainerProperties {
            liveness_route: None,
            readiness_route: None,
            startup_route: None,
            scoring_route: None,
        }
    }
}

