/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InstanceSegmentationPrimaryMetrics : Primary metrics for InstanceSegmentation tasks.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum InstanceSegmentationPrimaryMetrics {
    #[serde(rename = "MeanAveragePrecision")]
    MeanAveragePrecision,
}

impl Default for InstanceSegmentationPrimaryMetrics {
    fn default() -> Self {
        Self::MeanAveragePrecision
    }
}

impl std::fmt::Display for InstanceSegmentationPrimaryMetrics {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::MeanAveragePrecision => write!(f, "MeanAveragePrecision"),
        }
    }
}

impl std::str::FromStr for InstanceSegmentationPrimaryMetrics {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "MeanAveragePrecision" => Ok(Self::MeanAveragePrecision),
            _ => Err(format!("Invalid InstanceSegmentationPrimaryMetrics: {}", s)),
        }
    }
}
