/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JobType : Enum to determine the type of job.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum JobType {
    #[serde(rename = "AutoML")]
    AutoML,
    #[serde(rename = "Command")]
    Command,
    #[serde(rename = "Sweep")]
    Sweep,
    #[serde(rename = "Pipeline")]
    Pipeline,
    #[serde(rename = "Spark")]
    Spark,
}

impl Default for JobType {
    fn default() -> Self {
        Self::AutoML
    }
}

impl std::fmt::Display for JobType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AutoML => write!(f, "AutoML"),
            Self::Command => write!(f, "Command"),
            Self::Sweep => write!(f, "Sweep"),
            Self::Pipeline => write!(f, "Pipeline"),
            Self::Spark => write!(f, "Spark"),
        }
    }
}

impl std::str::FromStr for JobType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "AutoML" => Ok(Self::AutoML),
            "Command" => Ok(Self::Command),
            "Sweep" => Ok(Self::Sweep),
            "Pipeline" => Ok(Self::Pipeline),
            "Spark" => Ok(Self::Spark),
            _ => Err(format!("Invalid JobType: {}", s)),
        }
    }
}
