/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JobInputType : Enum to determine the Job Input Type.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum JobInputType {
    #[serde(rename = "literal")]
    literal,
    #[serde(rename = "uri_file")]
    uri_file,
    #[serde(rename = "uri_folder")]
    uri_folder,
    #[serde(rename = "mltable")]
    mltable,
    #[serde(rename = "custom_model")]
    custom_model,
    #[serde(rename = "mlflow_model")]
    mlflow_model,
    #[serde(rename = "triton_model")]
    triton_model,
}

impl Default for JobInputType {
    fn default() -> Self {
        Self::literal
    }
}

impl std::fmt::Display for JobInputType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::literal => write!(f, "literal"),
            Self::uri_file => write!(f, "uri_file"),
            Self::uri_folder => write!(f, "uri_folder"),
            Self::mltable => write!(f, "mltable"),
            Self::custom_model => write!(f, "custom_model"),
            Self::mlflow_model => write!(f, "mlflow_model"),
            Self::triton_model => write!(f, "triton_model"),
        }
    }
}

impl std::str::FromStr for JobInputType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "literal" => Ok(Self::literal),
            "uri_file" => Ok(Self::uri_file),
            "uri_folder" => Ok(Self::uri_folder),
            "mltable" => Ok(Self::mltable),
            "custom_model" => Ok(Self::custom_model),
            "mlflow_model" => Ok(Self::mlflow_model),
            "triton_model" => Ok(Self::triton_model),
            _ => Err(format!("Invalid JobInputType: {}", s)),
        }
    }
}
