/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarketplacePlan {
    /// The identifying name of the Offer of the Marketplace Plan.
    #[serde(rename = "offerId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub offer_id: Option<Option<String>>,
    /// The identifying name of the Plan of the Marketplace Plan.
    #[serde(rename = "planId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub plan_id: Option<Option<String>>,
    /// The identifying name of the Publisher of the Marketplace Plan.
    #[serde(rename = "publisherId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub publisher_id: Option<Option<String>>,
}

impl MarketplacePlan {
    pub fn new() -> MarketplacePlan {
        MarketplacePlan {
            offer_id: None,
            plan_id: None,
            publisher_id: None,
        }
    }
}

