/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarketplaceSubscription {
    #[serde(rename = "marketplacePlan", skip_serializing_if = "Option::is_none")]
    pub marketplace_plan: Option<Box<models::MarketplacePlan>>,
    #[serde(rename = "marketplaceSubscriptionStatus", skip_serializing_if = "Option::is_none")]
    pub marketplace_subscription_status: Option<models::MarketplaceSubscriptionStatus>,
    /// [Required] Target Marketplace Model ID to create a Marketplace Subscription for.
    #[serde(rename = "modelId")]
    pub model_id: String,
    #[serde(rename = "provisioningState", skip_serializing_if = "Option::is_none")]
    pub provisioning_state: Option<models::MarketplaceSubscriptionProvisioningState>,
}

impl MarketplaceSubscription {
    pub fn new(model_id: String) -> MarketplaceSubscription {
        MarketplaceSubscription {
            marketplace_plan: None,
            marketplace_subscription_status: None,
            model_id,
            provisioning_state: None,
        }
    }
}

