/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MaterializationSettings {
    #[serde(rename = "notification", skip_serializing_if = "Option::is_none")]
    pub notification: Option<Box<models::NotificationSetting>>,
    #[serde(rename = "resource", skip_serializing_if = "Option::is_none")]
    pub resource: Option<Box<models::MaterializationComputeResource>>,
    #[serde(rename = "schedule", skip_serializing_if = "Option::is_none")]
    pub schedule: Option<Box<models::RecurrenceTrigger>>,
    /// Specifies the spark compute settings
    #[serde(rename = "sparkConfiguration", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub spark_configuration: Option<Option<std::collections::HashMap<String, String>>>,
    #[serde(rename = "storeType", skip_serializing_if = "Option::is_none")]
    pub store_type: Option<models::MaterializationStoreType>,
}

impl MaterializationSettings {
    pub fn new() -> MaterializationSettings {
        MaterializationSettings {
            notification: None,
            resource: None,
            schedule: None,
            spark_configuration: None,
            store_type: None,
        }
    }
}

