/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MedianStoppingPolicy : Defines an early termination policy based on running averages of the primary metric of all runs
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MedianStoppingPolicy {
    /// Number of intervals by which to delay the first evaluation.
    #[serde(rename = "delayEvaluation", skip_serializing_if = "Option::is_none")]
    pub delay_evaluation: Option<i32>,
    /// Interval (number of runs) between policy evaluations.
    #[serde(rename = "evaluationInterval", skip_serializing_if = "Option::is_none")]
    pub evaluation_interval: Option<i32>,
    #[serde(rename = "policyType")]
    pub policy_type: models::EarlyTerminationPolicyType,
}

impl MedianStoppingPolicy {
    /// Defines an early termination policy based on running averages of the primary metric of all runs
    pub fn new(policy_type: models::EarlyTerminationPolicyType) -> MedianStoppingPolicy {
        MedianStoppingPolicy {
            delay_evaluation: None,
            evaluation_interval: None,
            policy_type,
        }
    }
}

