/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MonitorComputeIdentityType : Monitor compute identity type enum.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum MonitorComputeIdentityType {
    #[serde(rename = "AmlToken")]
    AmlToken,
    #[serde(rename = "ManagedIdentity")]
    ManagedIdentity,
}

impl Default for MonitorComputeIdentityType {
    fn default() -> Self {
        Self::AmlToken
    }
}

impl std::fmt::Display for MonitorComputeIdentityType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AmlToken => write!(f, "AmlToken"),
            Self::ManagedIdentity => write!(f, "ManagedIdentity"),
        }
    }
}

impl std::str::FromStr for MonitorComputeIdentityType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "AmlToken" => Ok(Self::AmlToken),
            "ManagedIdentity" => Ok(Self::ManagedIdentity),
            _ => Err(format!("Invalid MonitorComputeIdentityType: {}", s)),
        }
    }
}
