/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MonitorEmailNotificationSettings {
    /// The email recipient list which has a limitation of 499 characters in total.
    #[serde(rename = "emails", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub emails: Option<Option<Vec<String>>>,
}

impl MonitorEmailNotificationSettings {
    pub fn new() -> MonitorEmailNotificationSettings {
        MonitorEmailNotificationSettings {
            emails: None,
        }
    }
}

