/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NlpVerticalLimitSettings : Job execution constraints.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NlpVerticalLimitSettings {
    /// Maximum Concurrent AutoML iterations.
    #[serde(rename = "maxConcurrentTrials", skip_serializing_if = "Option::is_none")]
    pub max_concurrent_trials: Option<i32>,
    /// Number of AutoML iterations.
    #[serde(rename = "maxTrials", skip_serializing_if = "Option::is_none")]
    pub max_trials: Option<i32>,
    /// AutoML job timeout.
    #[serde(rename = "timeout", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<String>,
}

impl NlpVerticalLimitSettings {
    /// Job execution constraints.
    pub fn new() -> NlpVerticalLimitSettings {
        NlpVerticalLimitSettings {
            max_concurrent_trials: None,
            max_trials: None,
            timeout: None,
        }
    }
}

