/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NlpVertical : Abstract class for NLP related AutoML tasks.  NLP - Natural Language Processing.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NlpVertical {
    #[serde(rename = "featurizationSettings", skip_serializing_if = "Option::is_none")]
    pub featurization_settings: Option<Box<models::NlpVerticalFeaturizationSettings>>,
    #[serde(rename = "limitSettings", skip_serializing_if = "Option::is_none")]
    pub limit_settings: Option<Box<models::NlpVerticalLimitSettings>>,
    #[serde(rename = "validationData", skip_serializing_if = "Option::is_none")]
    pub validation_data: Option<Box<models::MlTableJobInput>>,
}

impl NlpVertical {
    /// Abstract class for NLP related AutoML tasks.  NLP - Natural Language Processing.
    pub fn new() -> NlpVertical {
        NlpVertical {
            featurization_settings: None,
            limit_settings: None,
            validation_data: None,
        }
    }
}

