/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NotificationSetting : Configuration for notification.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationSetting {
    /// Send email notification to user on specified notification type
    #[serde(rename = "emailOn", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub email_on: Option<Option<Vec<models::EmailNotificationEnableType>>>,
    /// This is the email recipient list which has a limitation of 499 characters in total concat with comma separator
    #[serde(rename = "emails", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub emails: Option<Option<Vec<String>>>,
    /// Send webhook callback to a service. Key is a user-provided name for the webhook.
    #[serde(rename = "webhooks", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub webhooks: Option<Option<std::collections::HashMap<String, models::Webhook>>>,
}

impl NotificationSetting {
    /// Configuration for notification.
    pub fn new() -> NotificationSetting {
        NotificationSetting {
            email_on: None,
            emails: None,
            webhooks: None,
        }
    }
}

