/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrderString : OrderString enum
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum OrderString {
    #[serde(rename = "CreatedAtDesc")]
    CreatedAtDesc,
    #[serde(rename = "CreatedAtAsc")]
    CreatedAtAsc,
    #[serde(rename = "UpdatedAtDesc")]
    UpdatedAtDesc,
    #[serde(rename = "UpdatedAtAsc")]
    UpdatedAtAsc,
}

impl Default for OrderString {
    fn default() -> Self {
        Self::CreatedAtDesc
    }
}

impl std::fmt::Display for OrderString {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CreatedAtDesc => write!(f, "CreatedAtDesc"),
            Self::CreatedAtAsc => write!(f, "CreatedAtAsc"),
            Self::UpdatedAtDesc => write!(f, "UpdatedAtDesc"),
            Self::UpdatedAtAsc => write!(f, "UpdatedAtAsc"),
        }
    }
}

impl std::str::FromStr for OrderString {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "CreatedAtDesc" => Ok(Self::CreatedAtDesc),
            "CreatedAtAsc" => Ok(Self::CreatedAtAsc),
            "UpdatedAtDesc" => Ok(Self::UpdatedAtDesc),
            "UpdatedAtAsc" => Ok(Self::UpdatedAtAsc),
            _ => Err(format!("Invalid OrderString: {}", s)),
        }
    }
}
