/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PartialBatchDeployment : Mutable batch inference settings per deployment.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartialBatchDeployment {
    /// Description of the endpoint deployment.
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
}

impl PartialBatchDeployment {
    /// Mutable batch inference settings per deployment.
    pub fn new() -> PartialBatchDeployment {
        PartialBatchDeployment {
            description: None,
        }
    }
}

