/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PartialMinimalTrackedResource : Strictly used in update requests.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartialMinimalTrackedResource {
    /// Resource tags.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<std::collections::HashMap<String, String>>,
}

impl PartialMinimalTrackedResource {
    /// Strictly used in update requests.
    pub fn new() -> PartialMinimalTrackedResource {
        PartialMinimalTrackedResource {
            tags: None,
        }
    }
}

