/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PendingUploadCredentialType : Enum to determine the PendingUpload credentials type.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum PendingUploadCredentialType {
    #[serde(rename = "SAS")]
    SAS,
}

impl Default for PendingUploadCredentialType {
    fn default() -> Self {
        Self::SAS
    }
}

impl std::fmt::Display for PendingUploadCredentialType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::SAS => write!(f, "SAS"),
        }
    }
}

impl std::str::FromStr for PendingUploadCredentialType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "SAS" => Ok(Self::SAS),
            _ => Err(format!("Invalid PendingUploadCredentialType: {}", s)),
        }
    }
}
