/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RandomSamplingAlgorithmRule : The specific type of random algorithm
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum RandomSamplingAlgorithmRule {
    #[serde(rename = "Random")]
    Random,
    #[serde(rename = "Sobol")]
    Sobol,
}

impl Default for RandomSamplingAlgorithmRule {
    fn default() -> Self {
        Self::Random
    }
}

impl std::fmt::Display for RandomSamplingAlgorithmRule {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Random => write!(f, "Random"),
            Self::Sobol => write!(f, "Sobol"),
        }
    }
}

impl std::str::FromStr for RandomSamplingAlgorithmRule {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Random" => Ok(Self::Random),
            "Sobol" => Ok(Self::Sobol),
            _ => Err(format!("Invalid RandomSamplingAlgorithmRule: {}", s)),
        }
    }
}
