/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ShortSeriesHandlingConfiguration : The parameter defining how if AutoML should handle short time series.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum ShortSeriesHandlingConfiguration {
    #[serde(rename = "None")]
    None,
    #[serde(rename = "Auto")]
    Auto,
    #[serde(rename = "Pad")]
    Pad,
    #[serde(rename = "Drop")]
    Drop,
}

impl Default for ShortSeriesHandlingConfiguration {
    fn default() -> Self {
        Self::None
    }
}

impl std::fmt::Display for ShortSeriesHandlingConfiguration {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::None => write!(f, "None"),
            Self::Auto => write!(f, "Auto"),
            Self::Pad => write!(f, "Pad"),
            Self::Drop => write!(f, "Drop"),
        }
    }
}

impl std::str::FromStr for ShortSeriesHandlingConfiguration {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "None" => Ok(Self::None),
            "Auto" => Ok(Self::Auto),
            "Pad" => Ok(Self::Pad),
            "Drop" => Ok(Self::Drop),
            _ => Err(format!("Invalid ShortSeriesHandlingConfiguration: {}", s)),
        }
    }
}
