/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SkuResource : Fulfills ARM Contract requirement to list all available SKUS for a resource.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SkuResource {
    #[serde(rename = "capacity", skip_serializing_if = "Option::is_none")]
    pub capacity: Option<Box<models::SkuCapacity>>,
    /// The resource type name.
    #[serde(rename = "resourceType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub resource_type: Option<Option<String>>,
    #[serde(rename = "sku", skip_serializing_if = "Option::is_none")]
    pub sku: Option<Box<models::SkuSetting>>,
}

impl SkuResource {
    /// Fulfills ARM Contract requirement to list all available SKUS for a resource.
    pub fn new() -> SkuResource {
        SkuResource {
            capacity: None,
            resource_type: None,
            sku: None,
        }
    }
}

