/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SweepJob : Sweep job definition.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SweepJob {
    #[serde(rename = "earlyTermination", skip_serializing_if = "Option::is_none")]
    pub early_termination: Option<Box<models::EarlyTerminationPolicy>>,
    /// Mapping of input data bindings used in the job.
    #[serde(rename = "inputs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub inputs: Option<Option<std::collections::HashMap<String, models::JobInput>>>,
    #[serde(rename = "limits", skip_serializing_if = "Option::is_none")]
    pub limits: Option<Box<models::SweepJobLimits>>,
    #[serde(rename = "objective")]
    pub objective: Box<models::Objective>,
    /// Mapping of output data bindings used in the job.
    #[serde(rename = "outputs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub outputs: Option<Option<std::collections::HashMap<String, models::JobOutput>>>,
    #[serde(rename = "queueSettings", skip_serializing_if = "Option::is_none")]
    pub queue_settings: Option<Box<models::QueueSettings>>,
    #[serde(rename = "samplingAlgorithm")]
    pub sampling_algorithm: Box<models::SamplingAlgorithm>,
    /// [Required] A dictionary containing each parameter and its distribution. The dictionary key is the name of the parameter
    #[serde(rename = "searchSpace")]
    pub search_space: serde_json::Value,
    #[serde(rename = "trial")]
    pub trial: Box<models::TrialComponent>,
    /// ARM resource ID of the component resource.
    #[serde(rename = "componentId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub component_id: Option<Option<String>>,
    /// ARM resource ID of the compute resource.
    #[serde(rename = "computeId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub compute_id: Option<Option<String>>,
    /// Display name of job.
    #[serde(rename = "displayName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<Option<String>>,
    /// The name of the experiment the job belongs to. If not set, the job is placed in the \"Default\" experiment.
    #[serde(rename = "experimentName", skip_serializing_if = "Option::is_none")]
    pub experiment_name: Option<String>,
    #[serde(rename = "identity", skip_serializing_if = "Option::is_none")]
    pub identity: Option<Box<models::IdentityConfiguration>>,
    /// Is the asset archived?
    #[serde(rename = "isArchived", skip_serializing_if = "Option::is_none")]
    pub is_archived: Option<bool>,
    #[serde(rename = "jobType")]
    pub job_type: models::JobType,
    #[serde(rename = "notificationSetting", skip_serializing_if = "Option::is_none")]
    pub notification_setting: Option<Box<models::NotificationSetting>>,
    /// List of JobEndpoints.  For local jobs, a job endpoint will have an endpoint value of FileStreamObject.
    #[serde(rename = "services", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub services: Option<Option<std::collections::HashMap<String, models::JobService>>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::JobStatus>,
    /// The asset description text.
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    /// The asset property dictionary.
    #[serde(rename = "properties", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Option<std::collections::HashMap<String, String>>>,
    /// Tag dictionary. Tags can be added, removed, and updated.
    #[serde(rename = "tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Option<std::collections::HashMap<String, String>>>,
}

impl SweepJob {
    /// Sweep job definition.
    pub fn new(objective: models::Objective, sampling_algorithm: models::SamplingAlgorithm, search_space: serde_json::Value, trial: models::TrialComponent, job_type: models::JobType) -> SweepJob {
        SweepJob {
            early_termination: None,
            inputs: None,
            limits: None,
            objective: Box::new(objective),
            outputs: None,
            queue_settings: None,
            sampling_algorithm: Box::new(sampling_algorithm),
            search_space,
            trial: Box::new(trial),
            component_id: None,
            compute_id: None,
            display_name: None,
            experiment_name: None,
            identity: None,
            is_archived: None,
            job_type,
            notification_setting: None,
            services: None,
            status: None,
            description: None,
            properties: None,
            tags: None,
        }
    }
}

