/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TargetRollingWindowSizeMode : Target rolling windows size mode.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum TargetRollingWindowSizeMode {
    #[serde(rename = "Auto")]
    Auto,
    #[serde(rename = "Custom")]
    Custom,
}

impl Default for TargetRollingWindowSizeMode {
    fn default() -> Self {
        Self::Auto
    }
}

impl std::fmt::Display for TargetRollingWindowSizeMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Auto => write!(f, "Auto"),
            Self::Custom => write!(f, "Custom"),
        }
    }
}

impl std::str::FromStr for TargetRollingWindowSizeMode {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Auto" => Ok(Self::Auto),
            "Custom" => Ok(Self::Custom),
            _ => Err(format!("Invalid TargetRollingWindowSizeMode: {}", s)),
        }
    }
}
