/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TargetUtilizationScaleSettings {
    /// The maximum number of instances that the deployment can scale to. The quota will be reserved for max_instances.
    #[serde(rename = "maxInstances", skip_serializing_if = "Option::is_none")]
    pub max_instances: Option<i32>,
    /// The minimum number of instances to always be present.
    #[serde(rename = "minInstances", skip_serializing_if = "Option::is_none")]
    pub min_instances: Option<i32>,
    /// The polling interval in ISO 8691 format. Only supports duration with precision as low as Seconds.
    #[serde(rename = "pollingInterval", skip_serializing_if = "Option::is_none")]
    pub polling_interval: Option<String>,
    /// Target CPU usage for the autoscaler.
    #[serde(rename = "targetUtilizationPercentage", skip_serializing_if = "Option::is_none")]
    pub target_utilization_percentage: Option<i32>,
    #[serde(rename = "scaleType")]
    pub scale_type: models::ScaleType,
}

impl TargetUtilizationScaleSettings {
    pub fn new(scale_type: models::ScaleType) -> TargetUtilizationScaleSettings {
        TargetUtilizationScaleSettings {
            max_instances: None,
            min_instances: None,
            polling_interval: None,
            target_utilization_percentage: None,
            scale_type,
        }
    }
}

