/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Webhook : Webhook base
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "webhookType")]
pub enum Webhook {
    #[serde(rename="AzureDevOpsWebhook")]
    AzureDevOpsWebhook {
        /// Send callback on a specified notification event
        #[serde(rename = "eventType", skip_serializing_if = "Option::is_none")]
        event_type: Option<String>,
    },
}

impl Default for Webhook {
    fn default() -> Self {
        Self::AzureDevOpsWebhook {
            event_type: Default::default(),
        }
        
    }
}


