/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AllNodes : All nodes means the service will be running on all of the nodes of the job
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllNodes {
    #[serde(rename = "nodesValueType")]
    pub nodes_value_type: models::NodesValueType,
}

impl AllNodes {
    /// All nodes means the service will be running on all of the nodes of the job
    pub fn new(nodes_value_type: models::NodesValueType) -> AllNodes {
        AllNodes {
            nodes_value_type,
        }
    }
}

