/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllFeatures {
    #[serde(rename = "filterType")]
    pub filter_type: models::MonitoringFeatureFilterType,
}

impl AllFeatures {
    pub fn new(filter_type: models::MonitoringFeatureFilterType) -> AllFeatures {
        AllFeatures { filter_type }
    }
}
