/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AmlToken : AML Token identity configuration.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AmlToken {
    #[serde(rename = "identityType")]
    pub identity_type: models::IdentityConfigurationType,
}

impl AmlToken {
    /// AML Token identity configuration.
    pub fn new(identity_type: models::IdentityConfigurationType) -> AmlToken {
        AmlToken { identity_type }
    }
}
