/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AmlTokenComputeIdentity : AML token compute identity definition.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AmlTokenComputeIdentity {
    #[serde(rename = "computeIdentityType")]
    pub compute_identity_type: models::MonitorComputeIdentityType,
}

impl AmlTokenComputeIdentity {
    /// AML token compute identity definition.
    pub fn new(
        compute_identity_type: models::MonitorComputeIdentityType,
    ) -> AmlTokenComputeIdentity {
        AmlTokenComputeIdentity {
            compute_identity_type,
        }
    }
}
