/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AssetJobInput : Asset input type.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetJobInput {
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<models::InputDeliveryMode>,
    /// [Required] Input Asset URI.
    #[serde(rename = "uri")]
    pub uri: String,
}

impl AssetJobInput {
    /// Asset input type.
    pub fn new(uri: String) -> AssetJobInput {
        AssetJobInput { mode: None, uri }
    }
}
