/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AutoTargetRollingWindowSize : Target lags rolling window determined automatically.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AutoTargetRollingWindowSize {
    #[serde(rename = "mode")]
    pub mode: models::TargetRollingWindowSizeMode,
}

impl AutoTargetRollingWindowSize {
    /// Target lags rolling window determined automatically.
    pub fn new(mode: models::TargetRollingWindowSizeMode) -> AutoTargetRollingWindowSize {
        AutoTargetRollingWindowSize { mode }
    }
}
