/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AutoNCrossValidations : N-Cross validations determined automatically.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AutoNCrossValidations {
    #[serde(rename = "mode")]
    pub mode: models::NCrossValidationsMode,
}

impl AutoNCrossValidations {
    /// N-Cross validations determined automatically.
    pub fn new(mode: models::NCrossValidationsMode) -> AutoNCrossValidations {
        AutoNCrossValidations { mode }
    }
}
