/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// AutoRebuildSetting : AutoRebuild setting for the derived image
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum AutoRebuildSetting {
    #[serde(rename = "Disabled")]
    Disabled,
    #[serde(rename = "OnBaseImageUpdate")]
    OnBaseImageUpdate,
}

impl Default for AutoRebuildSetting {
    fn default() -> Self {
        Self::Disabled
    }
}

impl std::fmt::Display for AutoRebuildSetting {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Disabled => write!(f, "Disabled"),
            Self::OnBaseImageUpdate => write!(f, "OnBaseImageUpdate"),
        }
    }
}

impl std::str::FromStr for AutoRebuildSetting {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Disabled" => Ok(Self::Disabled),
            "OnBaseImageUpdate" => Ok(Self::OnBaseImageUpdate),
            _ => Err(format!("Invalid AutoRebuildSetting: {}", s)),
        }
    }
}
