/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AutoForecastHorizon : Forecast horizon determined automatically by system.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AutoForecastHorizon {
    #[serde(rename = "mode")]
    pub mode: models::ForecastHorizonMode,
}

impl AutoForecastHorizon {
    /// Forecast horizon determined automatically by system.
    pub fn new(mode: models::ForecastHorizonMode) -> AutoForecastHorizon {
        AutoForecastHorizon {
            mode,
        }
    }
}

