/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AzureDevOpsWebhook : Webhook details specific for Azure DevOps
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AzureDevOpsWebhook {
    /// Send callback on a specified notification event
    #[serde(
        rename = "eventType",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub event_type: Option<Option<String>>,
    #[serde(rename = "webhookType")]
    pub webhook_type: models::WebhookType,
}

impl AzureDevOpsWebhook {
    /// Webhook details specific for Azure DevOps
    pub fn new(webhook_type: models::WebhookType) -> AzureDevOpsWebhook {
        AzureDevOpsWebhook {
            event_type: None,
            webhook_type,
        }
    }
}
