/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AzureDataLakeGen2Datastore : Azure Data Lake Gen2 datastore configuration.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AzureDataLakeGen2Datastore {
    /// [Required] Storage account name.
    #[serde(rename = "accountName")]
    pub account_name: String,
    /// Azure cloud endpoint for the storage account.
    #[serde(
        rename = "endpoint",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub endpoint: Option<Option<String>>,
    /// [Required] The name of the Data Lake Gen2 filesystem.
    #[serde(rename = "filesystem")]
    pub filesystem: String,
    /// Protocol used to communicate with the storage account.
    #[serde(
        rename = "protocol",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub protocol: Option<Option<String>>,
    #[serde(
        rename = "serviceDataAccessAuthIdentity",
        skip_serializing_if = "Option::is_none"
    )]
    pub service_data_access_auth_identity: Option<models::ServiceDataAccessAuthIdentity>,
    /// Azure Resource Group name
    #[serde(
        rename = "resourceGroup",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub resource_group: Option<Option<String>>,
    /// Azure Subscription Id
    #[serde(
        rename = "subscriptionId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub subscription_id: Option<Option<String>>,
    #[serde(rename = "credentials")]
    pub credentials: Box<models::DatastoreCredentials>,
    #[serde(rename = "datastoreType")]
    pub datastore_type: models::DatastoreType,
    /// Readonly property to indicate if datastore is the workspace default datastore
    #[serde(rename = "isDefault", skip_serializing_if = "Option::is_none")]
    pub is_default: Option<bool>,
    /// The asset description text.
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    /// The asset property dictionary.
    #[serde(
        rename = "properties",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub properties: Option<Option<std::collections::HashMap<String, String>>>,
    /// Tag dictionary. Tags can be added, removed, and updated.
    #[serde(
        rename = "tags",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tags: Option<Option<std::collections::HashMap<String, String>>>,
}

impl AzureDataLakeGen2Datastore {
    /// Azure Data Lake Gen2 datastore configuration.
    pub fn new(
        account_name: String,
        filesystem: String,
        credentials: models::DatastoreCredentials,
        datastore_type: models::DatastoreType,
    ) -> AzureDataLakeGen2Datastore {
        AzureDataLakeGen2Datastore {
            account_name,
            endpoint: None,
            filesystem,
            protocol: None,
            service_data_access_auth_identity: None,
            resource_group: None,
            subscription_id: None,
            credentials: Box::new(credentials),
            datastore_type,
            is_default: None,
            description: None,
            properties: None,
            tags: None,
        }
    }
}
