/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BatchPipelineComponentDeploymentConfiguration : Properties for a Batch Pipeline Component Deployment.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchPipelineComponentDeploymentConfiguration {
    #[serde(rename = "componentId", skip_serializing_if = "Option::is_none")]
    pub component_id: Option<Box<models::IdAssetReference>>,
    /// The description which will be applied to the job.
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    /// Run-time settings for the pipeline job.
    #[serde(
        rename = "settings",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub settings: Option<Option<std::collections::HashMap<String, String>>>,
    /// The tags which will be applied to the job.
    #[serde(
        rename = "tags",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tags: Option<Option<std::collections::HashMap<String, String>>>,
    #[serde(rename = "deploymentConfigurationType")]
    pub deployment_configuration_type: models::BatchDeploymentConfigurationType,
}

impl BatchPipelineComponentDeploymentConfiguration {
    /// Properties for a Batch Pipeline Component Deployment.
    pub fn new(
        deployment_configuration_type: models::BatchDeploymentConfigurationType,
    ) -> BatchPipelineComponentDeploymentConfiguration {
        BatchPipelineComponentDeploymentConfiguration {
            component_id: None,
            description: None,
            settings: None,
            tags: None,
            deployment_configuration_type,
        }
    }
}
