/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BatchOutputAction : Enum to determine how batch inferencing will handle output
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum BatchOutputAction {
    #[serde(rename = "SummaryOnly")]
    SummaryOnly,
    #[serde(rename = "AppendRow")]
    AppendRow,
}

impl Default for BatchOutputAction {
    fn default() -> Self {
        Self::SummaryOnly
    }
}

impl std::fmt::Display for BatchOutputAction {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::SummaryOnly => write!(f, "SummaryOnly"),
            Self::AppendRow => write!(f, "AppendRow"),
        }
    }
}

impl std::str::FromStr for BatchOutputAction {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "SummaryOnly" => Ok(Self::SummaryOnly),
            "AppendRow" => Ok(Self::AppendRow),
            _ => Err(format!("Invalid BatchOutputAction: {}", s)),
        }
    }
}
