/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchEndpointTrackedResource {
    #[serde(rename = "identity", skip_serializing_if = "Option::is_none")]
    pub identity: Option<Box<models::ManagedServiceIdentity>>,
    /// Metadata used by portal/tooling/etc to render different UX experiences for resources of the same type.
    #[serde(rename = "kind", skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    #[serde(rename = "properties")]
    pub properties: Box<models::BatchEndpoint>,
    #[serde(rename = "sku", skip_serializing_if = "Option::is_none")]
    pub sku: Option<Box<models::Sku>>,
    /// Resource tags.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<std::collections::HashMap<String, String>>,
    /// The geo-location where the resource lives
    #[serde(rename = "location")]
    pub location: String,
    /// Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The name of the resource
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The type of the resource. E.g. \"Microsoft.Compute/virtualMachines\" or \"Microsoft.Storage/storageAccounts\"
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "systemData", skip_serializing_if = "Option::is_none")]
    pub system_data: Option<Box<models::SystemData>>,
}

impl BatchEndpointTrackedResource {
    pub fn new(
        properties: models::BatchEndpoint,
        location: String,
    ) -> BatchEndpointTrackedResource {
        BatchEndpointTrackedResource {
            identity: None,
            kind: None,
            properties: Box::new(properties),
            sku: None,
            tags: None,
            location,
            id: None,
            name: None,
            r#type: None,
            system_data: None,
        }
    }
}
