/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BatchDeployment : Batch inference settings per deployment.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchDeployment {
    /// Compute target for batch inference operation.
    #[serde(rename = "compute", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub compute: Option<Option<String>>,
    #[serde(rename = "deploymentConfiguration", skip_serializing_if = "Option::is_none")]
    pub deployment_configuration: Option<Box<models::BatchDeploymentConfiguration>>,
    /// Error threshold, if the error count for the entire input goes above this value,  the batch inference will be aborted. Range is [-1, int.MaxValue].  For FileDataset, this value is the count of file failures.  For TabularDataset, this value is the count of record failures.  If set to -1 (the lower bound), all failures during batch inference will be ignored.
    #[serde(rename = "errorThreshold", skip_serializing_if = "Option::is_none")]
    pub error_threshold: Option<i32>,
    #[serde(rename = "loggingLevel", skip_serializing_if = "Option::is_none")]
    pub logging_level: Option<models::BatchLoggingLevel>,
    /// Indicates maximum number of parallelism per instance.
    #[serde(rename = "maxConcurrencyPerInstance", skip_serializing_if = "Option::is_none")]
    pub max_concurrency_per_instance: Option<i32>,
    /// Size of the mini-batch passed to each batch invocation.  For FileDataset, this is the number of files per mini-batch.  For TabularDataset, this is the size of the records in bytes, per mini-batch.
    #[serde(rename = "miniBatchSize", skip_serializing_if = "Option::is_none")]
    pub mini_batch_size: Option<i64>,
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<Box<models::AssetReferenceBase>>,
    #[serde(rename = "outputAction", skip_serializing_if = "Option::is_none")]
    pub output_action: Option<models::BatchOutputAction>,
    /// Customized output file name for append_row output action.
    #[serde(rename = "outputFileName", skip_serializing_if = "Option::is_none")]
    pub output_file_name: Option<String>,
    #[serde(rename = "provisioningState", skip_serializing_if = "Option::is_none")]
    pub provisioning_state: Option<models::DeploymentProvisioningState>,
    #[serde(rename = "resources", skip_serializing_if = "Option::is_none")]
    pub resources: Option<Box<models::DeploymentResourceConfiguration>>,
    #[serde(rename = "retrySettings", skip_serializing_if = "Option::is_none")]
    pub retry_settings: Option<Box<models::BatchRetrySettings>>,
    #[serde(rename = "codeConfiguration", skip_serializing_if = "Option::is_none")]
    pub code_configuration: Option<Box<models::CodeConfiguration>>,
    /// Description of the endpoint deployment.
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    /// ARM resource ID or AssetId of the environment specification for the endpoint deployment.
    #[serde(rename = "environmentId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub environment_id: Option<Option<String>>,
    /// Environment variables configuration for the deployment.
    #[serde(rename = "environmentVariables", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub environment_variables: Option<Option<std::collections::HashMap<String, String>>>,
    /// Property dictionary. Properties can be added, but not removed or altered.
    #[serde(rename = "properties", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Option<std::collections::HashMap<String, String>>>,
}

impl BatchDeployment {
    /// Batch inference settings per deployment.
    pub fn new() -> BatchDeployment {
        BatchDeployment {
            compute: None,
            deployment_configuration: None,
            error_threshold: None,
            logging_level: None,
            max_concurrency_per_instance: None,
            mini_batch_size: None,
            model: None,
            output_action: None,
            output_file_name: None,
            provisioning_state: None,
            resources: None,
            retry_settings: None,
            code_configuration: None,
            description: None,
            environment_id: None,
            environment_variables: None,
            properties: None,
        }
    }
}

