/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// BatchDeploymentConfigurationType : The enumerated property types for batch deployments.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
pub enum BatchDeploymentConfigurationType {
    #[serde(rename = "Model")]
    #[default]
    Model,
    #[serde(rename = "PipelineComponent")]
    PipelineComponent,
}

impl std::fmt::Display for BatchDeploymentConfigurationType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Model => write!(f, "Model"),
            Self::PipelineComponent => write!(f, "PipelineComponent"),
        }
    }
}

impl std::str::FromStr for BatchDeploymentConfigurationType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Model" => Ok(Self::Model),
            "PipelineComponent" => Ok(Self::PipelineComponent),
            _ => Err(format!("Invalid BatchDeploymentConfigurationType: {}", s)),
        }
    }
}
