/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BatchDeploymentConfiguration : Properties relevant to different deployment types.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "deploymentConfigurationType")]
pub enum BatchDeploymentConfiguration {
    #[serde(rename="BatchPipelineComponentDeploymentConfiguration")]
    BatchPipelineComponentDeploymentConfiguration {
    },
}

impl Default for BatchDeploymentConfiguration {
    fn default() -> Self {
        Self::BatchPipelineComponentDeploymentConfiguration {
        }
        
    }
}


