/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// BatchRetrySettings : Retry settings for a batch inference operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchRetrySettings {
    /// Maximum retry count for a mini-batch
    #[serde(rename = "maxRetries", skip_serializing_if = "Option::is_none")]
    pub max_retries: Option<i32>,
    /// Invocation timeout for a mini-batch, in ISO 8601 format.
    #[serde(rename = "timeout", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<String>,
}

impl BatchRetrySettings {
    /// Retry settings for a batch inference operation.
    pub fn new() -> BatchRetrySettings {
        BatchRetrySettings {
            max_retries: None,
            timeout: None,
        }
    }
}
