/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlobReferenceForConsumptionDto {
    /// Blob URI path for client to upload data.  Example: https://blob.windows.core.net/Container/Path
    #[serde(
        rename = "blobUri",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub blob_uri: Option<Option<String>>,
    #[serde(rename = "credential", skip_serializing_if = "Option::is_none")]
    pub credential: Option<Box<models::PendingUploadCredentialDto>>,
    /// Arm ID of the storage account to use
    #[serde(
        rename = "storageAccountArmId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub storage_account_arm_id: Option<Option<String>>,
}

impl BlobReferenceForConsumptionDto {
    pub fn new() -> BlobReferenceForConsumptionDto {
        BlobReferenceForConsumptionDto {
            blob_uri: None,
            credential: None,
            storage_account_arm_id: None,
        }
    }
}
