/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// BuildContext : Configuration settings for Docker build context
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BuildContext {
    /// [Required] URI of the Docker build context used to build the image. Supports blob URIs on environment creation and may return blob or Git URIs.  <seealso href=\"https://docs.docker.com/engine/reference/commandline/build/#extended-description\" />
    #[serde(rename = "contextUri")]
    pub context_uri: String,
    /// Path to the Dockerfile in the build context.  <seealso href=\"https://docs.docker.com/engine/reference/builder/\" />
    #[serde(rename = "dockerfilePath", skip_serializing_if = "Option::is_none")]
    pub dockerfile_path: Option<String>,
}

impl BuildContext {
    /// Configuration settings for Docker build context
    pub fn new(context_uri: String) -> BuildContext {
        BuildContext {
            context_uri,
            dockerfile_path: None,
        }
    }
}
