/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// CapabilityHostKind : CapabilityHostKind enum
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum CapabilityHostKind {
    #[serde(rename = "Agents")]
    Agents,
}

impl Default for CapabilityHostKind {
    fn default() -> Self {
        Self::Agents
    }
}

impl std::fmt::Display for CapabilityHostKind {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Agents => write!(f, "Agents"),
        }
    }
}

impl std::str::FromStr for CapabilityHostKind {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Agents" => Ok(Self::Agents),
            _ => Err(format!("Invalid CapabilityHostKind: {}", s)),
        }
    }
}
