/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CapabilityHost {
    /// List of AI services connections.
    #[serde(rename = "aiServicesConnections", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ai_services_connections: Option<Option<Vec<String>>>,
    #[serde(rename = "capabilityHostKind", skip_serializing_if = "Option::is_none")]
    pub capability_host_kind: Option<models::CapabilityHostKind>,
    /// Customer subnet info to help set up this capability host.
    #[serde(rename = "customerSubnet", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub customer_subnet: Option<Option<String>>,
    #[serde(rename = "provisioningState", skip_serializing_if = "Option::is_none")]
    pub provisioning_state: Option<models::CapabilityHostProvisioningState>,
    /// List of Storage connections.
    #[serde(rename = "storageConnections", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub storage_connections: Option<Option<Vec<String>>>,
    /// List of Thread storage connections.
    #[serde(rename = "threadStorageConnections", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub thread_storage_connections: Option<Option<Vec<String>>>,
    /// List of VectorStore connections.
    #[serde(rename = "vectorStoreConnections", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub vector_store_connections: Option<Option<Vec<String>>>,
    /// The asset description text.
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    /// The asset property dictionary.
    #[serde(rename = "properties", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Option<std::collections::HashMap<String, String>>>,
    /// Tag dictionary. Tags can be added, removed, and updated.
    #[serde(rename = "tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Option<std::collections::HashMap<String, String>>>,
}

impl CapabilityHost {
    pub fn new() -> CapabilityHost {
        CapabilityHost {
            ai_services_connections: None,
            capability_host_kind: None,
            customer_subnet: None,
            provisioning_state: None,
            storage_connections: None,
            thread_storage_connections: None,
            vector_store_connections: None,
            description: None,
            properties: None,
            tags: None,
        }
    }
}

