/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CategoricalDataQualityMetricThreshold {
    #[serde(rename = "metric")]
    pub metric: models::CategoricalDataQualityMetric,
    #[serde(rename = "dataType")]
    pub data_type: models::MonitoringFeatureDataType,
    #[serde(rename = "threshold", skip_serializing_if = "Option::is_none")]
    pub threshold: Option<Box<models::MonitoringThreshold>>,
}

impl CategoricalDataQualityMetricThreshold {
    pub fn new(
        metric: models::CategoricalDataQualityMetric,
        data_type: models::MonitoringFeatureDataType,
    ) -> CategoricalDataQualityMetricThreshold {
        CategoricalDataQualityMetricThreshold {
            metric,
            data_type,
            threshold: None,
        }
    }
}
