/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// CategoricalDataQualityMetric : CategoricalDataQualityMetric enum
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum CategoricalDataQualityMetric {
    #[serde(rename = "NullValueRate")]
    NullValueRate,
    #[serde(rename = "DataTypeErrorRate")]
    DataTypeErrorRate,
    #[serde(rename = "OutOfBoundsRate")]
    OutOfBoundsRate,
}

impl Default for CategoricalDataQualityMetric {
    fn default() -> Self {
        Self::NullValueRate
    }
}

impl std::fmt::Display for CategoricalDataQualityMetric {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::NullValueRate => write!(f, "NullValueRate"),
            Self::DataTypeErrorRate => write!(f, "DataTypeErrorRate"),
            Self::OutOfBoundsRate => write!(f, "OutOfBoundsRate"),
        }
    }
}

impl std::str::FromStr for CategoricalDataQualityMetric {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "NullValueRate" => Ok(Self::NullValueRate),
            "DataTypeErrorRate" => Ok(Self::DataTypeErrorRate),
            "OutOfBoundsRate" => Ok(Self::OutOfBoundsRate),
            _ => Err(format!("Invalid CategoricalDataQualityMetric: {}", s)),
        }
    }
}
