/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// CategoricalDataDriftMetric : CategoricalDataDriftMetric enum
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
pub enum CategoricalDataDriftMetric {
    #[serde(rename = "JensenShannonDistance")]
    #[default]
    JensenShannonDistance,
    #[serde(rename = "PopulationStabilityIndex")]
    PopulationStabilityIndex,
    #[serde(rename = "PearsonsChiSquaredTest")]
    PearsonsChiSquaredTest,
}

impl std::fmt::Display for CategoricalDataDriftMetric {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::JensenShannonDistance => write!(f, "JensenShannonDistance"),
            Self::PopulationStabilityIndex => write!(f, "PopulationStabilityIndex"),
            Self::PearsonsChiSquaredTest => write!(f, "PearsonsChiSquaredTest"),
        }
    }
}

impl std::str::FromStr for CategoricalDataDriftMetric {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "JensenShannonDistance" => Ok(Self::JensenShannonDistance),
            "PopulationStabilityIndex" => Ok(Self::PopulationStabilityIndex),
            "PearsonsChiSquaredTest" => Ok(Self::PearsonsChiSquaredTest),
            _ => Err(format!("Invalid CategoricalDataDriftMetric: {}", s)),
        }
    }
}
