/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CertificateDatastoreSecrets : Datastore certificate secrets.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CertificateDatastoreSecrets {
    /// Service principal certificate.
    #[serde(rename = "certificate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub certificate: Option<Option<String>>,
    #[serde(rename = "secretsType")]
    pub secrets_type: models::SecretsType,
}

impl CertificateDatastoreSecrets {
    /// Datastore certificate secrets.
    pub fn new(secrets_type: models::SecretsType) -> CertificateDatastoreSecrets {
        CertificateDatastoreSecrets {
            certificate: None,
            secrets_type,
        }
    }
}

