/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ClassificationMultilabelPrimaryMetrics : Primary metrics for classification multilabel tasks.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum ClassificationMultilabelPrimaryMetrics {
    #[serde(rename = "AUCWeighted")]
    AUCWeighted,
    #[serde(rename = "Accuracy")]
    Accuracy,
    #[serde(rename = "NormMacroRecall")]
    NormMacroRecall,
    #[serde(rename = "AveragePrecisionScoreWeighted")]
    AveragePrecisionScoreWeighted,
    #[serde(rename = "PrecisionScoreWeighted")]
    PrecisionScoreWeighted,
    #[serde(rename = "IOU")]
    IOU,
}

impl Default for ClassificationMultilabelPrimaryMetrics {
    fn default() -> Self {
        Self::AUCWeighted
    }
}

impl std::fmt::Display for ClassificationMultilabelPrimaryMetrics {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AUCWeighted => write!(f, "AUCWeighted"),
            Self::Accuracy => write!(f, "Accuracy"),
            Self::NormMacroRecall => write!(f, "NormMacroRecall"),
            Self::AveragePrecisionScoreWeighted => write!(f, "AveragePrecisionScoreWeighted"),
            Self::PrecisionScoreWeighted => write!(f, "PrecisionScoreWeighted"),
            Self::IOU => write!(f, "IOU"),
        }
    }
}

impl std::str::FromStr for ClassificationMultilabelPrimaryMetrics {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "AUCWeighted" => Ok(Self::AUCWeighted),
            "Accuracy" => Ok(Self::Accuracy),
            "NormMacroRecall" => Ok(Self::NormMacroRecall),
            "AveragePrecisionScoreWeighted" => Ok(Self::AveragePrecisionScoreWeighted),
            "PrecisionScoreWeighted" => Ok(Self::PrecisionScoreWeighted),
            "IOU" => Ok(Self::IOU),
            _ => Err(format!("Invalid ClassificationMultilabelPrimaryMetrics: {}", s)),
        }
    }
}
