/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ClassificationModels : Enum for all classification models supported by AutoML.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
pub enum ClassificationModels {
    #[serde(rename = "LogisticRegression")]
    #[default]
    LogisticRegression,
    #[serde(rename = "SGD")]
    SGD,
    #[serde(rename = "MultinomialNaiveBayes")]
    MultinomialNaiveBayes,
    #[serde(rename = "BernoulliNaiveBayes")]
    BernoulliNaiveBayes,
    #[serde(rename = "SVM")]
    SVM,
    #[serde(rename = "LinearSVM")]
    LinearSVM,
    #[serde(rename = "KNN")]
    KNN,
    #[serde(rename = "DecisionTree")]
    DecisionTree,
    #[serde(rename = "RandomForest")]
    RandomForest,
    #[serde(rename = "ExtremeRandomTrees")]
    ExtremeRandomTrees,
    #[serde(rename = "LightGBM")]
    LightGBM,
    #[serde(rename = "GradientBoosting")]
    GradientBoosting,
    #[serde(rename = "XGBoostClassifier")]
    XGBoostClassifier,
}

impl std::fmt::Display for ClassificationModels {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::LogisticRegression => write!(f, "LogisticRegression"),
            Self::SGD => write!(f, "SGD"),
            Self::MultinomialNaiveBayes => write!(f, "MultinomialNaiveBayes"),
            Self::BernoulliNaiveBayes => write!(f, "BernoulliNaiveBayes"),
            Self::SVM => write!(f, "SVM"),
            Self::LinearSVM => write!(f, "LinearSVM"),
            Self::KNN => write!(f, "KNN"),
            Self::DecisionTree => write!(f, "DecisionTree"),
            Self::RandomForest => write!(f, "RandomForest"),
            Self::ExtremeRandomTrees => write!(f, "ExtremeRandomTrees"),
            Self::LightGBM => write!(f, "LightGBM"),
            Self::GradientBoosting => write!(f, "GradientBoosting"),
            Self::XGBoostClassifier => write!(f, "XGBoostClassifier"),
        }
    }
}

impl std::str::FromStr for ClassificationModels {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "LogisticRegression" => Ok(Self::LogisticRegression),
            "SGD" => Ok(Self::SGD),
            "MultinomialNaiveBayes" => Ok(Self::MultinomialNaiveBayes),
            "BernoulliNaiveBayes" => Ok(Self::BernoulliNaiveBayes),
            "SVM" => Ok(Self::SVM),
            "LinearSVM" => Ok(Self::LinearSVM),
            "KNN" => Ok(Self::KNN),
            "DecisionTree" => Ok(Self::DecisionTree),
            "RandomForest" => Ok(Self::RandomForest),
            "ExtremeRandomTrees" => Ok(Self::ExtremeRandomTrees),
            "LightGBM" => Ok(Self::LightGBM),
            "GradientBoosting" => Ok(Self::GradientBoosting),
            "XGBoostClassifier" => Ok(Self::XGBoostClassifier),
            _ => Err(format!("Invalid ClassificationModels: {}", s)),
        }
    }
}
