/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CodeContainer : Container for code asset versions.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CodeContainer {
    #[serde(rename = "provisioningState", skip_serializing_if = "Option::is_none")]
    pub provisioning_state: Option<models::AssetProvisioningState>,
    /// Is the asset archived?
    #[serde(rename = "isArchived", skip_serializing_if = "Option::is_none")]
    pub is_archived: Option<bool>,
    /// The latest version inside this container.
    #[serde(
        rename = "latestVersion",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub latest_version: Option<Option<String>>,
    /// The next auto incremental version
    #[serde(
        rename = "nextVersion",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub next_version: Option<Option<String>>,
    /// The asset description text.
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    /// The asset property dictionary.
    #[serde(
        rename = "properties",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub properties: Option<Option<std::collections::HashMap<String, String>>>,
    /// Tag dictionary. Tags can be added, removed, and updated.
    #[serde(
        rename = "tags",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tags: Option<Option<std::collections::HashMap<String, String>>>,
}

impl CodeContainer {
    /// Container for code asset versions.
    pub fn new() -> CodeContainer {
        CodeContainer {
            provisioning_state: None,
            is_archived: None,
            latest_version: None,
            next_version: None,
            description: None,
            properties: None,
            tags: None,
        }
    }
}
