/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Collection {
    /// The msi client id used to collect logging to blob storage. If it's null,backend will pick a registered endpoint identity to auth.
    #[serde(
        rename = "clientId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub client_id: Option<Option<String>>,
    #[serde(rename = "dataCollectionMode", skip_serializing_if = "Option::is_none")]
    pub data_collection_mode: Option<models::DataCollectionMode>,
    /// The data asset arm resource id. Client side will ensure data asset is pointing to the blob storage, and backend will collect data to the blob storage.
    #[serde(
        rename = "dataId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub data_id: Option<Option<String>>,
    /// The sampling rate for collection. Sampling rate 1.0 means we collect 100% of data by default.
    #[serde(rename = "samplingRate", skip_serializing_if = "Option::is_none")]
    pub sampling_rate: Option<f64>,
}

impl Collection {
    pub fn new() -> Collection {
        Collection {
            client_id: None,
            data_collection_mode: None,
            data_id: None,
            sampling_rate: None,
        }
    }
}
