/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ColumnTransformer : Column transformer parameters.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ColumnTransformer {
    /// Fields to apply transformer logic on.
    #[serde(
        rename = "fields",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub fields: Option<Option<Vec<String>>>,
    /// Different properties to be passed to transformer.  Input expected is dictionary of key,value pairs in JSON format.
    #[serde(
        rename = "parameters",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub parameters: Option<Option<serde_json::Value>>,
}

impl ColumnTransformer {
    /// Column transformer parameters.
    pub fn new() -> ColumnTransformer {
        ColumnTransformer {
            fields: None,
            parameters: None,
        }
    }
}
