/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContainerResourceRequirements : Resource requirements for each container instance within an online deployment.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerResourceRequirements {
    #[serde(
        rename = "containerResourceLimits",
        skip_serializing_if = "Option::is_none"
    )]
    pub container_resource_limits: Option<Box<models::ContainerResourceSettings>>,
    #[serde(
        rename = "containerResourceRequests",
        skip_serializing_if = "Option::is_none"
    )]
    pub container_resource_requests: Option<Box<models::ContainerResourceSettings>>,
}

impl ContainerResourceRequirements {
    /// Resource requirements for each container instance within an online deployment.
    pub fn new() -> ContainerResourceRequirements {
        ContainerResourceRequirements {
            container_resource_limits: None,
            container_resource_requests: None,
        }
    }
}
