/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ContainerType : ContainerType enum
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
pub enum ContainerType {
    #[serde(rename = "StorageInitializer")]
    #[default]
    StorageInitializer,
    #[serde(rename = "InferenceServer")]
    InferenceServer,
}

impl std::fmt::Display for ContainerType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::StorageInitializer => write!(f, "StorageInitializer"),
            Self::InferenceServer => write!(f, "InferenceServer"),
        }
    }
}

impl std::str::FromStr for ContainerType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "StorageInitializer" => Ok(Self::StorageInitializer),
            "InferenceServer" => Ok(Self::InferenceServer),
            _ => Err(format!("Invalid ContainerType: {}", s)),
        }
    }
}
