/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentSafety {
    #[serde(rename = "contentSafetyStatus")]
    pub content_safety_status: models::ContentSafetyStatus,
}

impl ContentSafety {
    pub fn new(content_safety_status: models::ContentSafetyStatus) -> ContentSafety {
        ContentSafety {
            content_safety_status,
        }
    }
}

