/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomTargetRollingWindowSize {
    /// [Required] TargetRollingWindowSize value.
    #[serde(rename = "value")]
    pub value: i32,
    #[serde(rename = "mode")]
    pub mode: models::TargetRollingWindowSizeMode,
}

impl CustomTargetRollingWindowSize {
    pub fn new(
        value: i32,
        mode: models::TargetRollingWindowSizeMode,
    ) -> CustomTargetRollingWindowSize {
        CustomTargetRollingWindowSize { value, mode }
    }
}
