/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustomForecastHorizon : The desired maximum forecast horizon in units of time-series frequency.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomForecastHorizon {
    /// [Required] Forecast horizon value.
    #[serde(rename = "value")]
    pub value: i32,
    #[serde(rename = "mode")]
    pub mode: models::ForecastHorizonMode,
}

impl CustomForecastHorizon {
    /// The desired maximum forecast horizon in units of time-series frequency.
    pub fn new(value: i32, mode: models::ForecastHorizonMode) -> CustomForecastHorizon {
        CustomForecastHorizon { value, mode }
    }
}
