/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomMonitoringSignal {
    /// [Required] Reference to the component asset used to calculate the custom metrics.
    #[serde(rename = "componentId")]
    pub component_id: String,
    /// Monitoring assets to take as input. Key is the component input port name, value is the data asset.
    #[serde(
        rename = "inputAssets",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub input_assets:
        Option<Option<std::collections::HashMap<String, models::MonitoringInputDataBase>>>,
    /// Extra component parameters to take as input. Key is the component literal input port name, value is the parameter value.
    #[serde(
        rename = "inputs",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub inputs: Option<Option<std::collections::HashMap<String, models::JobInput>>>,
    /// [Required] A list of metrics to calculate and their associated thresholds.
    #[serde(rename = "metricThresholds")]
    pub metric_thresholds: Vec<models::CustomMetricThreshold>,
    /// The current notification mode for this signal.
    #[serde(
        rename = "notificationTypes",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub notification_types: Option<Option<Vec<models::MonitoringNotificationType>>>,
    /// Property dictionary. Properties can be added, but not removed or altered.
    #[serde(
        rename = "properties",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub properties: Option<Option<std::collections::HashMap<String, String>>>,
    #[serde(rename = "signalType")]
    pub signal_type: models::MonitoringSignalType,
}

impl CustomMonitoringSignal {
    pub fn new(
        component_id: String,
        metric_thresholds: Vec<models::CustomMetricThreshold>,
        signal_type: models::MonitoringSignalType,
    ) -> CustomMonitoringSignal {
        CustomMonitoringSignal {
            component_id,
            input_assets: None,
            inputs: None,
            metric_thresholds,
            notification_types: None,
            properties: None,
            signal_type,
        }
    }
}
