/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomTargetLags {
    /// [Required] Set target lags values.
    #[serde(rename = "values")]
    pub values: Vec<i32>,
    #[serde(rename = "mode")]
    pub mode: models::TargetLagsMode,
}

impl CustomTargetLags {
    pub fn new(values: Vec<i32>, mode: models::TargetLagsMode) -> CustomTargetLags {
        CustomTargetLags {
            values,
            mode,
        }
    }
}

