/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// DataCollectionMode : DataCollectionMode enum
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
pub enum DataCollectionMode {
    #[serde(rename = "Enabled")]
    #[default]
    Enabled,
    #[serde(rename = "Disabled")]
    Disabled,
}

impl std::fmt::Display for DataCollectionMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Enabled => write!(f, "Enabled"),
            Self::Disabled => write!(f, "Disabled"),
        }
    }
}

impl std::str::FromStr for DataCollectionMode {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Enabled" => Ok(Self::Enabled),
            "Disabled" => Ok(Self::Disabled),
            _ => Err(format!("Invalid DataCollectionMode: {}", s)),
        }
    }
}
