/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "dataType")]
pub enum DataDriftMetricThresholdBase {
    #[serde(rename = "CategoricalDataDriftMetricThreshold")]
    CategoricalDataDriftMetricThreshold {
        #[serde(rename = "threshold", skip_serializing_if = "Option::is_none")]
        threshold: Option<Box<models::MonitoringThreshold>>,
    },
    #[serde(rename = "NumericalDataDriftMetricThreshold")]
    NumericalDataDriftMetricThreshold {
        #[serde(rename = "threshold", skip_serializing_if = "Option::is_none")]
        threshold: Option<Box<models::MonitoringThreshold>>,
    },
}

impl Default for DataDriftMetricThresholdBase {
    fn default() -> Self {
        Self::CategoricalDataDriftMetricThreshold {
            threshold: Default::default(),
        }
    }
}
