/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// DataReferenceCredentialType : Enum to determine the DataReference credentials type.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
pub enum DataReferenceCredentialType {
    #[serde(rename = "SAS")]
    #[default]
    SAS,
    #[serde(rename = "DockerCredentials")]
    DockerCredentials,
    #[serde(rename = "ManagedIdentity")]
    ManagedIdentity,
    #[serde(rename = "NoCredentials")]
    NoCredentials,
}

impl std::fmt::Display for DataReferenceCredentialType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::SAS => write!(f, "SAS"),
            Self::DockerCredentials => write!(f, "DockerCredentials"),
            Self::ManagedIdentity => write!(f, "ManagedIdentity"),
            Self::NoCredentials => write!(f, "NoCredentials"),
        }
    }
}

impl std::str::FromStr for DataReferenceCredentialType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "SAS" => Ok(Self::SAS),
            "DockerCredentials" => Ok(Self::DockerCredentials),
            "ManagedIdentity" => Ok(Self::ManagedIdentity),
            "NoCredentials" => Ok(Self::NoCredentials),
            _ => Err(format!("Invalid DataReferenceCredentialType: {}", s)),
        }
    }
}
