/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DataType : Enum to determine the type of data.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum DataType {
    #[serde(rename = "uri_file")]
    uri_file,
    #[serde(rename = "uri_folder")]
    uri_folder,
    #[serde(rename = "mltable")]
    mltable,
}

impl Default for DataType {
    fn default() -> Self {
        Self::uri_file
    }
}

impl std::fmt::Display for DataType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::uri_file => write!(f, "uri_file"),
            Self::uri_folder => write!(f, "uri_folder"),
            Self::mltable => write!(f, "mltable"),
        }
    }
}

impl std::str::FromStr for DataType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "uri_file" => Ok(Self::uri_file),
            "uri_folder" => Ok(Self::uri_folder),
            "mltable" => Ok(Self::mltable),
            _ => Err(format!("Invalid DataType: {}", s)),
        }
    }
}
