/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// DatastoreType : Enum to determine the datastore contents type.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
pub enum DatastoreType {
    #[serde(rename = "AzureBlob")]
    #[default]
    AzureBlob,
    #[serde(rename = "AzureDataLakeGen1")]
    AzureDataLakeGen1,
    #[serde(rename = "AzureDataLakeGen2")]
    AzureDataLakeGen2,
    #[serde(rename = "AzureFile")]
    AzureFile,
    #[serde(rename = "OneLake")]
    OneLake,
}

impl std::fmt::Display for DatastoreType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AzureBlob => write!(f, "AzureBlob"),
            Self::AzureDataLakeGen1 => write!(f, "AzureDataLakeGen1"),
            Self::AzureDataLakeGen2 => write!(f, "AzureDataLakeGen2"),
            Self::AzureFile => write!(f, "AzureFile"),
            Self::OneLake => write!(f, "OneLake"),
        }
    }
}

impl std::str::FromStr for DatastoreType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "AzureBlob" => Ok(Self::AzureBlob),
            "AzureDataLakeGen1" => Ok(Self::AzureDataLakeGen1),
            "AzureDataLakeGen2" => Ok(Self::AzureDataLakeGen2),
            "AzureFile" => Ok(Self::AzureFile),
            "OneLake" => Ok(Self::OneLake),
            _ => Err(format!("Invalid DatastoreType: {}", s)),
        }
    }
}
