/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// DatastoreSecrets : Base definition for datastore secrets.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "secretsType")]
pub enum DatastoreSecrets {
    #[serde(rename = "AccountKeyDatastoreSecrets")]
    AccountKeyDatastoreSecrets {},
    #[serde(rename = "CertificateDatastoreSecrets")]
    CertificateDatastoreSecrets {},
    #[serde(rename = "SasDatastoreSecrets")]
    SasDatastoreSecrets {},
    #[serde(rename = "ServicePrincipalDatastoreSecrets")]
    ServicePrincipalDatastoreSecrets {},
}

impl Default for DatastoreSecrets {
    fn default() -> Self {
        Self::AccountKeyDatastoreSecrets {}
    }
}
