/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// DataType : Enum to determine the type of data.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum DataType {
    #[serde(rename = "uri_file")]
    UriFile,
    #[serde(rename = "uri_folder")]
    UriFolder,
    #[serde(rename = "mltable")]
    MlTable,
}

impl Default for DataType {
    fn default() -> Self {
        Self::UriFile
    }
}

impl std::fmt::Display for DataType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::UriFile => write!(f, "uri_file"),
            Self::UriFolder => write!(f, "uri_folder"),
            Self::MlTable => write!(f, "mltable"),
        }
    }
}

impl std::str::FromStr for DataType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "uri_file" => Ok(Self::UriFile),
            "uri_folder" => Ok(Self::UriFolder),
            "mltable" => Ok(Self::MlTable),
            _ => Err(format!("Invalid DataType: {}", s)),
        }
    }
}
