/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DataCollector {
    /// [Required] The collection configuration. Each collection has it own configuration to collect model data and the name of collection can be arbitrary string.  Model data collector can be used for either payload logging or custom logging or both of them. Collection request and response are reserved for payload logging, others are for custom logging.
    #[serde(rename = "collections")]
    pub collections: std::collections::HashMap<String, models::Collection>,
    #[serde(rename = "requestLogging", skip_serializing_if = "Option::is_none")]
    pub request_logging: Option<Box<models::RequestLogging>>,
    #[serde(rename = "rollingRate", skip_serializing_if = "Option::is_none")]
    pub rolling_rate: Option<models::RollingRateType>,
}

impl DataCollector {
    pub fn new(
        collections: std::collections::HashMap<String, models::Collection>,
    ) -> DataCollector {
        DataCollector {
            collections,
            request_logging: None,
            rolling_rate: None,
        }
    }
}
