/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// DataAvailabilityStatus : DataAvailabilityStatus enum
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum DataAvailabilityStatus {
    #[serde(rename = "None")]
    None,
    #[serde(rename = "Pending")]
    Pending,
    #[serde(rename = "Incomplete")]
    Incomplete,
    #[serde(rename = "Complete")]
    Complete,
}

impl Default for DataAvailabilityStatus {
    fn default() -> Self {
        Self::None
    }
}

impl std::fmt::Display for DataAvailabilityStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::None => write!(f, "None"),
            Self::Pending => write!(f, "Pending"),
            Self::Incomplete => write!(f, "Incomplete"),
            Self::Complete => write!(f, "Complete"),
        }
    }
}

impl std::str::FromStr for DataAvailabilityStatus {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "None" => Ok(Self::None),
            "Pending" => Ok(Self::Pending),
            "Incomplete" => Ok(Self::Incomplete),
            "Complete" => Ok(Self::Complete),
            _ => Err(format!("Invalid DataAvailabilityStatus: {}", s)),
        }
    }
}
