/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Datastore : Base definition for datastore contents configuration.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Datastore {
    #[serde(rename = "credentials")]
    pub credentials: Box<models::DatastoreCredentials>,
    #[serde(rename = "datastoreType")]
    pub datastore_type: models::DatastoreType,
    /// Readonly property to indicate if datastore is the workspace default datastore
    #[serde(rename = "isDefault", skip_serializing_if = "Option::is_none")]
    pub is_default: Option<bool>,
    /// The asset description text.
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    /// The asset property dictionary.
    #[serde(
        rename = "properties",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub properties: Option<Option<std::collections::HashMap<String, String>>>,
    /// Tag dictionary. Tags can be added, removed, and updated.
    #[serde(
        rename = "tags",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tags: Option<Option<std::collections::HashMap<String, String>>>,
}

impl Datastore {
    /// Base definition for datastore contents configuration.
    pub fn new(
        credentials: models::DatastoreCredentials,
        datastore_type: models::DatastoreType,
    ) -> Datastore {
        Datastore {
            credentials: Box::new(credentials),
            datastore_type,
            is_default: None,
            description: None,
            properties: None,
            tags: None,
        }
    }
}
