/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentResourceConfiguration {
    /// Optional number of instances or nodes used by the compute target.
    #[serde(rename = "instanceCount", skip_serializing_if = "Option::is_none")]
    pub instance_count: Option<i32>,
    /// Optional type of VM used as supported by the compute target.
    #[serde(
        rename = "instanceType",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub instance_type: Option<Option<String>>,
    /// Additional properties bag.
    #[serde(
        rename = "properties",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub properties: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
}

impl DeploymentResourceConfiguration {
    pub fn new() -> DeploymentResourceConfiguration {
        DeploymentResourceConfiguration {
            instance_count: None,
            instance_type: None,
            properties: None,
        }
    }
}
