/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentLogsRequest {
    #[serde(rename = "containerType", skip_serializing_if = "Option::is_none")]
    pub container_type: Option<models::ContainerType>,
    /// The maximum number of lines to tail.
    #[serde(rename = "tail", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tail: Option<Option<i32>>,
}

impl DeploymentLogsRequest {
    pub fn new() -> DeploymentLogsRequest {
        DeploymentLogsRequest {
            container_type: None,
            tail: None,
        }
    }
}

