/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DistributionConfiguration : Base definition for job distribution configuration.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "distributionType")]
pub enum DistributionConfiguration {
    #[serde(rename="Mpi")]
    Mpi {
    },
    #[serde(rename="PyTorch")]
    PyTorch {
    },
    #[serde(rename="TensorFlow")]
    TensorFlow {
    },
}

impl Default for DistributionConfiguration {
    fn default() -> Self {
        Self::Mpi {
        }
        
    }
}


