/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DockerCredential : Credential for docker with username and password
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DockerCredential {
    /// DockerCredential user password
    #[serde(
        rename = "password",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub password: Option<Option<String>>,
    /// DockerCredential user name
    #[serde(
        rename = "userName",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_name: Option<Option<String>>,
    #[serde(rename = "credentialType")]
    pub credential_type: models::DataReferenceCredentialType,
}

impl DockerCredential {
    /// Credential for docker with username and password
    pub fn new(credential_type: models::DataReferenceCredentialType) -> DockerCredential {
        DockerCredential {
            password: None,
            user_name: None,
            credential_type,
        }
    }
}
