/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// EarlyTerminationPolicy : Early termination policies enable canceling poor-performing runs before they complete
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "policyType")]
pub enum EarlyTerminationPolicy {
    #[serde(rename="BanditPolicy")]
    BanditPolicy {
        /// Number of intervals by which to delay the first evaluation.
        #[serde(rename = "delayEvaluation", skip_serializing_if = "Option::is_none")]
        delay_evaluation: Option<i32>,
        /// Interval (number of runs) between policy evaluations.
        #[serde(rename = "evaluationInterval", skip_serializing_if = "Option::is_none")]
        evaluation_interval: Option<i32>,
    },
    #[serde(rename="MedianStoppingPolicy")]
    MedianStoppingPolicy {
        /// Number of intervals by which to delay the first evaluation.
        #[serde(rename = "delayEvaluation", skip_serializing_if = "Option::is_none")]
        delay_evaluation: Option<i32>,
        /// Interval (number of runs) between policy evaluations.
        #[serde(rename = "evaluationInterval", skip_serializing_if = "Option::is_none")]
        evaluation_interval: Option<i32>,
    },
    #[serde(rename="TruncationSelectionPolicy")]
    TruncationSelectionPolicy {
        /// Number of intervals by which to delay the first evaluation.
        #[serde(rename = "delayEvaluation", skip_serializing_if = "Option::is_none")]
        delay_evaluation: Option<i32>,
        /// Interval (number of runs) between policy evaluations.
        #[serde(rename = "evaluationInterval", skip_serializing_if = "Option::is_none")]
        evaluation_interval: Option<i32>,
    },
}

impl Default for EarlyTerminationPolicy {
    fn default() -> Self {
        Self::BanditPolicy {
            delay_evaluation: Default::default(),
            evaluation_interval: Default::default(),
        }
        
    }
}


