/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EmailNotificationEnableType : Enum to determine the email notification type.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum EmailNotificationEnableType {
    #[serde(rename = "JobCompleted")]
    JobCompleted,
    #[serde(rename = "JobFailed")]
    JobFailed,
    #[serde(rename = "JobCancelled")]
    JobCancelled,
}

impl Default for EmailNotificationEnableType {
    fn default() -> Self {
        Self::JobCompleted
    }
}

impl std::fmt::Display for EmailNotificationEnableType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::JobCompleted => write!(f, "JobCompleted"),
            Self::JobFailed => write!(f, "JobFailed"),
            Self::JobCancelled => write!(f, "JobCancelled"),
        }
    }
}

impl std::str::FromStr for EmailNotificationEnableType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "JobCompleted" => Ok(Self::JobCompleted),
            "JobFailed" => Ok(Self::JobFailed),
            "JobCancelled" => Ok(Self::JobCancelled),
            _ => Err(format!("Invalid EmailNotificationEnableType: {}", s)),
        }
    }
}
