/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EndpointScheduleAction {
    /// [Required] Defines Schedule action definition details.  <see href=\"TBD\" />
    #[serde(rename = "endpointInvocationDefinition")]
    pub endpoint_invocation_definition: serde_json::Value,
    #[serde(rename = "actionType")]
    pub action_type: models::ScheduleActionType,
}

impl EndpointScheduleAction {
    pub fn new(
        endpoint_invocation_definition: serde_json::Value,
        action_type: models::ScheduleActionType,
    ) -> EndpointScheduleAction {
        EndpointScheduleAction {
            endpoint_invocation_definition,
            action_type,
        }
    }
}
