/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// EndpointComputeType : Enum to determine endpoint compute type.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum EndpointComputeType {
    #[serde(rename = "Managed")]
    Managed,
    #[serde(rename = "Kubernetes")]
    Kubernetes,
    #[serde(rename = "AzureMLCompute")]
    AzureMLCompute,
}

impl Default for EndpointComputeType {
    fn default() -> Self {
        Self::Managed
    }
}

impl std::fmt::Display for EndpointComputeType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Managed => write!(f, "Managed"),
            Self::Kubernetes => write!(f, "Kubernetes"),
            Self::AzureMLCompute => write!(f, "AzureMLCompute"),
        }
    }
}

impl std::str::FromStr for EndpointComputeType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Managed" => Ok(Self::Managed),
            "Kubernetes" => Ok(Self::Kubernetes),
            "AzureMLCompute" => Ok(Self::AzureMLCompute),
            _ => Err(format!("Invalid EndpointComputeType: {}", s)),
        }
    }
}
