/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// EndpointAuthToken : Service Token
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EndpointAuthToken {
    /// Access token for endpoint authentication.
    #[serde(rename = "accessToken", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub access_token: Option<Option<String>>,
    /// Access token expiry time (UTC).
    #[serde(rename = "expiryTimeUtc", skip_serializing_if = "Option::is_none")]
    pub expiry_time_utc: Option<i64>,
    /// Refresh access token after time (UTC).
    #[serde(rename = "refreshAfterTimeUtc", skip_serializing_if = "Option::is_none")]
    pub refresh_after_time_utc: Option<i64>,
    /// Access token type.
    #[serde(rename = "tokenType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub token_type: Option<Option<String>>,
}

impl EndpointAuthToken {
    /// Service Token
    pub fn new() -> EndpointAuthToken {
        EndpointAuthToken {
            access_token: None,
            expiry_time_utc: None,
            refresh_after_time_utc: None,
            token_type: None,
        }
    }
}

