/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// EndpointAuthMode : Enum to determine endpoint authentication mode.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum EndpointAuthMode {
    #[serde(rename = "AMLToken")]
    AMLToken,
    #[serde(rename = "Key")]
    Key,
    #[serde(rename = "AADToken")]
    AADToken,
}

impl Default for EndpointAuthMode {
    fn default() -> Self {
        Self::AMLToken
    }
}

impl std::fmt::Display for EndpointAuthMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AMLToken => write!(f, "AMLToken"),
            Self::Key => write!(f, "Key"),
            Self::AADToken => write!(f, "AADToken"),
        }
    }
}

impl std::str::FromStr for EndpointAuthMode {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "AMLToken" => Ok(Self::AMLToken),
            "Key" => Ok(Self::Key),
            "AADToken" => Ok(Self::AADToken),
            _ => Err(format!("Invalid EndpointAuthMode: {}", s)),
        }
    }
}
