/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// EnvironmentType : Environment type is either user created or curated by Azure ML service
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
pub enum EnvironmentType {
    #[serde(rename = "Curated")]
    #[default]
    Curated,
    #[serde(rename = "UserCreated")]
    UserCreated,
}

impl std::fmt::Display for EnvironmentType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Curated => write!(f, "Curated"),
            Self::UserCreated => write!(f, "UserCreated"),
        }
    }
}

impl std::str::FromStr for EnvironmentType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Curated" => Ok(Self::Curated),
            "UserCreated" => Ok(Self::UserCreated),
            _ => Err(format!("Invalid EnvironmentType: {}", s)),
        }
    }
}
