/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ErrorAdditionalInfo : The resource management error additional info.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorAdditionalInfo {
    /// The additional info type.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// The additional info.
    #[serde(rename = "info", skip_serializing_if = "Option::is_none")]
    pub info: Option<serde_json::Value>,
}

impl ErrorAdditionalInfo {
    /// The resource management error additional info.
    pub fn new() -> ErrorAdditionalInfo {
        ErrorAdditionalInfo {
            r#type: None,
            info: None,
        }
    }
}
