/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// FeaturesetSpecification : DTO object representing specification
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeaturesetSpecification {
    /// Specifies the spec path
    #[serde(rename = "path", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub path: Option<Option<String>>,
}

impl FeaturesetSpecification {
    /// DTO object representing specification
    pub fn new() -> FeaturesetSpecification {
        FeaturesetSpecification {
            path: None,
        }
    }
}

