/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeatureAttributionMetricThreshold {
    #[serde(rename = "metric")]
    pub metric: models::FeatureAttributionMetric,
    #[serde(rename = "threshold", skip_serializing_if = "Option::is_none")]
    pub threshold: Option<Box<models::MonitoringThreshold>>,
}

impl FeatureAttributionMetricThreshold {
    pub fn new(metric: models::FeatureAttributionMetric) -> FeatureAttributionMetricThreshold {
        FeatureAttributionMetricThreshold {
            metric,
            threshold: None,
        }
    }
}

