/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// FeatureWindow : Specifies the feature window
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeatureWindow {
    /// Specifies the feature window end time
    #[serde(
        rename = "featureWindowEnd",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub feature_window_end: Option<Option<String>>,
    /// Specifies the feature window start time
    #[serde(
        rename = "featureWindowStart",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub feature_window_start: Option<Option<String>>,
}

impl FeatureWindow {
    /// Specifies the feature window
    pub fn new() -> FeatureWindow {
        FeatureWindow {
            feature_window_end: None,
            feature_window_start: None,
        }
    }
}
