/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FeaturestoreEntityVersionResource : Azure Resource Manager resource envelope.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeaturestoreEntityVersionResource {
    #[serde(rename = "properties")]
    pub properties: Box<models::FeaturestoreEntityVersion>,
    /// Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The name of the resource
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The type of the resource. E.g. \"Microsoft.Compute/virtualMachines\" or \"Microsoft.Storage/storageAccounts\"
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "systemData", skip_serializing_if = "Option::is_none")]
    pub system_data: Option<Box<models::SystemData>>,
}

impl FeaturestoreEntityVersionResource {
    /// Azure Resource Manager resource envelope.
    pub fn new(properties: models::FeaturestoreEntityVersion) -> FeaturestoreEntityVersionResource {
        FeaturestoreEntityVersionResource {
            properties: Box::new(properties),
            id: None,
            name: None,
            r#type: None,
            system_data: None,
        }
    }
}
