/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// FeaturizationSettings : Featurization Configuration.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeaturizationSettings {
    /// Dataset language, useful for the text data.
    #[serde(
        rename = "datasetLanguage",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub dataset_language: Option<Option<String>>,
}

impl FeaturizationSettings {
    /// Featurization Configuration.
    pub fn new() -> FeaturizationSettings {
        FeaturizationSettings {
            dataset_language: None,
        }
    }
}
