/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FeaturestoreEntityVersion : DTO object representing feature entity version
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeaturestoreEntityVersion {
    /// Specifies index columns
    #[serde(
        rename = "indexColumns",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub index_columns: Option<Option<Vec<models::IndexColumn>>>,
    #[serde(rename = "provisioningState", skip_serializing_if = "Option::is_none")]
    pub provisioning_state: Option<models::AssetProvisioningState>,
    /// Specifies the asset stage
    #[serde(
        rename = "stage",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub stage: Option<Option<String>>,
    /// If the name version are system generated (anonymous registration).
    #[serde(rename = "isAnonymous", skip_serializing_if = "Option::is_none")]
    pub is_anonymous: Option<bool>,
    /// Is the asset archived?
    #[serde(rename = "isArchived", skip_serializing_if = "Option::is_none")]
    pub is_archived: Option<bool>,
    /// The asset description text.
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    /// The asset property dictionary.
    #[serde(
        rename = "properties",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub properties: Option<Option<std::collections::HashMap<String, String>>>,
    /// Tag dictionary. Tags can be added, removed, and updated.
    #[serde(
        rename = "tags",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tags: Option<Option<std::collections::HashMap<String, String>>>,
}

impl FeaturestoreEntityVersion {
    /// DTO object representing feature entity version
    pub fn new() -> FeaturestoreEntityVersion {
        FeaturestoreEntityVersion {
            index_columns: None,
            provisioning_state: None,
            stage: None,
            is_anonymous: None,
            is_archived: None,
            description: None,
            properties: None,
            tags: None,
        }
    }
}
