/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// FeatureAttributionMetric : FeatureAttributionMetric enum
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum FeatureAttributionMetric {
    #[serde(rename = "NormalizedDiscountedCumulativeGain")]
    NormalizedDiscountedCumulativeGain,
}

impl Default for FeatureAttributionMetric {
    fn default() -> Self {
        Self::NormalizedDiscountedCumulativeGain
    }
}

impl std::fmt::Display for FeatureAttributionMetric {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::NormalizedDiscountedCumulativeGain => {
                write!(f, "NormalizedDiscountedCumulativeGain")
            }
        }
    }
}

impl std::str::FromStr for FeatureAttributionMetric {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "NormalizedDiscountedCumulativeGain" => Ok(Self::NormalizedDiscountedCumulativeGain),
            _ => Err(format!("Invalid FeatureAttributionMetric: {}", s)),
        }
    }
}
