/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// FeaturesetVersionBackfillResponse : Response payload for creating a backfill request for a given feature set version
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeaturesetVersionBackfillResponse {
    /// List of jobs submitted as part of the backfill request.
    #[serde(
        rename = "jobIds",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub job_ids: Option<Option<Vec<String>>>,
}

impl FeaturesetVersionBackfillResponse {
    /// Response payload for creating a backfill request for a given feature set version
    pub fn new() -> FeaturesetVersionBackfillResponse {
        FeaturesetVersionBackfillResponse { job_ids: None }
    }
}
