/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// FeatureLags : Flag for generating lags for the numeric features.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
pub enum FeatureLags {
    #[serde(rename = "None")]
    #[default]
    None,
    #[serde(rename = "Auto")]
    Auto,
}

impl std::fmt::Display for FeatureLags {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::None => write!(f, "None"),
            Self::Auto => write!(f, "Auto"),
        }
    }
}

impl std::str::FromStr for FeatureLags {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "None" => Ok(Self::None),
            "Auto" => Ok(Self::Auto),
            _ => Err(format!("Invalid FeatureLags: {}", s)),
        }
    }
}
