/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeatureImportanceSettings {
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<models::FeatureImportanceMode>,
    /// The name of the target column within the input data asset.
    #[serde(rename = "targetColumn", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub target_column: Option<Option<String>>,
}

impl FeatureImportanceSettings {
    pub fn new() -> FeatureImportanceSettings {
        FeatureImportanceSettings {
            mode: None,
            target_column: None,
        }
    }
}

