/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Feature : DTO object representing feature
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Feature {
    #[serde(rename = "dataType", skip_serializing_if = "Option::is_none")]
    pub data_type: Option<models::FeatureDataType>,
    /// Specifies name
    #[serde(rename = "featureName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub feature_name: Option<Option<String>>,
    /// The asset description text.
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    /// The asset property dictionary.
    #[serde(rename = "properties", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Option<std::collections::HashMap<String, String>>>,
    /// Tag dictionary. Tags can be added, removed, and updated.
    #[serde(rename = "tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Option<std::collections::HashMap<String, String>>>,
}

impl Feature {
    /// DTO object representing feature
    pub fn new() -> Feature {
        Feature {
            data_type: None,
            feature_name: None,
            description: None,
            properties: None,
            tags: None,
        }
    }
}

