/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeatureAttributionDriftMonitoringSignal {
    /// A dictionary that maps feature names to their respective data types.
    #[serde(
        rename = "featureDataTypeOverride",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub feature_data_type_override:
        Option<Option<std::collections::HashMap<String, models::MonitoringFeatureDataType>>>,
    #[serde(rename = "featureImportanceSettings")]
    pub feature_importance_settings: Box<models::FeatureImportanceSettings>,
    #[serde(rename = "metricThreshold")]
    pub metric_threshold: Box<models::FeatureAttributionMetricThreshold>,
    /// [Required] The data which drift will be calculated for.
    #[serde(rename = "productionData")]
    pub production_data: Vec<models::MonitoringInputDataBase>,
    #[serde(rename = "referenceData")]
    pub reference_data: Box<models::MonitoringInputDataBase>,
    /// The current notification mode for this signal.
    #[serde(
        rename = "notificationTypes",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub notification_types: Option<Option<Vec<models::MonitoringNotificationType>>>,
    /// Property dictionary. Properties can be added, but not removed or altered.
    #[serde(
        rename = "properties",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub properties: Option<Option<std::collections::HashMap<String, String>>>,
    #[serde(rename = "signalType")]
    pub signal_type: models::MonitoringSignalType,
}

impl FeatureAttributionDriftMonitoringSignal {
    pub fn new(
        feature_importance_settings: models::FeatureImportanceSettings,
        metric_threshold: models::FeatureAttributionMetricThreshold,
        production_data: Vec<models::MonitoringInputDataBase>,
        reference_data: models::MonitoringInputDataBase,
        signal_type: models::MonitoringSignalType,
    ) -> FeatureAttributionDriftMonitoringSignal {
        FeatureAttributionDriftMonitoringSignal {
            feature_data_type_override: None,
            feature_importance_settings: Box::new(feature_importance_settings),
            metric_threshold: Box::new(metric_threshold),
            production_data,
            reference_data: Box::new(reference_data),
            notification_types: None,
            properties: None,
            signal_type,
        }
    }
}
