/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ForecastHorizon : The desired maximum forecast horizon in units of time-series frequency.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "mode")]
pub enum ForecastHorizon {
    #[serde(rename="AutoForecastHorizon")]
    AutoForecastHorizon {
    },
    #[serde(rename="CustomForecastHorizon")]
    CustomForecastHorizon {
    },
}

impl Default for ForecastHorizon {
    fn default() -> Self {
        Self::AutoForecastHorizon {
        }
        
    }
}


