/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ForecastingModels : Enum for all forecasting models supported by AutoML.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
pub enum ForecastingModels {
    #[serde(rename = "AutoArima")]
    #[default]
    AutoArima,
    #[serde(rename = "Prophet")]
    Prophet,
    #[serde(rename = "Naive")]
    Naive,
    #[serde(rename = "SeasonalNaive")]
    SeasonalNaive,
    #[serde(rename = "Average")]
    Average,
    #[serde(rename = "SeasonalAverage")]
    SeasonalAverage,
    #[serde(rename = "ExponentialSmoothing")]
    ExponentialSmoothing,
    #[serde(rename = "Arimax")]
    Arimax,
    #[serde(rename = "TCNForecaster")]
    TCNForecaster,
    #[serde(rename = "ElasticNet")]
    ElasticNet,
    #[serde(rename = "GradientBoosting")]
    GradientBoosting,
    #[serde(rename = "DecisionTree")]
    DecisionTree,
    #[serde(rename = "KNN")]
    KNN,
    #[serde(rename = "LassoLars")]
    LassoLars,
    #[serde(rename = "SGD")]
    SGD,
    #[serde(rename = "RandomForest")]
    RandomForest,
    #[serde(rename = "ExtremeRandomTrees")]
    ExtremeRandomTrees,
    #[serde(rename = "LightGBM")]
    LightGBM,
    #[serde(rename = "XGBoostRegressor")]
    XGBoostRegressor,
}

impl std::fmt::Display for ForecastingModels {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AutoArima => write!(f, "AutoArima"),
            Self::Prophet => write!(f, "Prophet"),
            Self::Naive => write!(f, "Naive"),
            Self::SeasonalNaive => write!(f, "SeasonalNaive"),
            Self::Average => write!(f, "Average"),
            Self::SeasonalAverage => write!(f, "SeasonalAverage"),
            Self::ExponentialSmoothing => write!(f, "ExponentialSmoothing"),
            Self::Arimax => write!(f, "Arimax"),
            Self::TCNForecaster => write!(f, "TCNForecaster"),
            Self::ElasticNet => write!(f, "ElasticNet"),
            Self::GradientBoosting => write!(f, "GradientBoosting"),
            Self::DecisionTree => write!(f, "DecisionTree"),
            Self::KNN => write!(f, "KNN"),
            Self::LassoLars => write!(f, "LassoLars"),
            Self::SGD => write!(f, "SGD"),
            Self::RandomForest => write!(f, "RandomForest"),
            Self::ExtremeRandomTrees => write!(f, "ExtremeRandomTrees"),
            Self::LightGBM => write!(f, "LightGBM"),
            Self::XGBoostRegressor => write!(f, "XGBoostRegressor"),
        }
    }
}

impl std::str::FromStr for ForecastingModels {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "AutoArima" => Ok(Self::AutoArima),
            "Prophet" => Ok(Self::Prophet),
            "Naive" => Ok(Self::Naive),
            "SeasonalNaive" => Ok(Self::SeasonalNaive),
            "Average" => Ok(Self::Average),
            "SeasonalAverage" => Ok(Self::SeasonalAverage),
            "ExponentialSmoothing" => Ok(Self::ExponentialSmoothing),
            "Arimax" => Ok(Self::Arimax),
            "TCNForecaster" => Ok(Self::TCNForecaster),
            "ElasticNet" => Ok(Self::ElasticNet),
            "GradientBoosting" => Ok(Self::GradientBoosting),
            "DecisionTree" => Ok(Self::DecisionTree),
            "KNN" => Ok(Self::KNN),
            "LassoLars" => Ok(Self::LassoLars),
            "SGD" => Ok(Self::SGD),
            "RandomForest" => Ok(Self::RandomForest),
            "ExtremeRandomTrees" => Ok(Self::ExtremeRandomTrees),
            "LightGBM" => Ok(Self::LightGBM),
            "XGBoostRegressor" => Ok(Self::XGBoostRegressor),
            _ => Err(format!("Invalid ForecastingModels: {}", s)),
        }
    }
}
