/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// GetBlobReferenceSasRequestDto : BlobReferenceSASRequest for getBlobReferenceSAS API
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetBlobReferenceSasRequestDto {
    /// Id of the asset to be accessed
    #[serde(rename = "assetId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub asset_id: Option<Option<String>>,
    /// Blob uri of the asset to be accessed
    #[serde(rename = "blobUri", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub blob_uri: Option<Option<String>>,
}

impl GetBlobReferenceSasRequestDto {
    /// BlobReferenceSASRequest for getBlobReferenceSAS API
    pub fn new() -> GetBlobReferenceSasRequestDto {
        GetBlobReferenceSasRequestDto {
            asset_id: None,
            blob_uri: None,
        }
    }
}

