/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IdAssetReference : Reference to an asset via its ARM resource ID.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IdAssetReference {
    /// [Required] ARM resource ID of the asset.
    #[serde(rename = "assetId")]
    pub asset_id: String,
    #[serde(rename = "referenceType")]
    pub reference_type: models::ReferenceType,
}

impl IdAssetReference {
    /// Reference to an asset via its ARM resource ID.
    pub fn new(asset_id: String, reference_type: models::ReferenceType) -> IdAssetReference {
        IdAssetReference {
            asset_id,
            reference_type,
        }
    }
}
