/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// IdentityConfigurationType : Enum to determine identity framework.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
pub enum IdentityConfigurationType {
    #[serde(rename = "Managed")]
    #[default]
    Managed,
    #[serde(rename = "AMLToken")]
    AMLToken,
    #[serde(rename = "UserIdentity")]
    UserIdentity,
}

impl std::fmt::Display for IdentityConfigurationType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Managed => write!(f, "Managed"),
            Self::AMLToken => write!(f, "AMLToken"),
            Self::UserIdentity => write!(f, "UserIdentity"),
        }
    }
}

impl std::str::FromStr for IdentityConfigurationType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Managed" => Ok(Self::Managed),
            "AMLToken" => Ok(Self::AMLToken),
            "UserIdentity" => Ok(Self::UserIdentity),
            _ => Err(format!("Invalid IdentityConfigurationType: {}", s)),
        }
    }
}
