/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IdentityConfiguration : Base definition for identity configuration.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "identityType")]
pub enum IdentityConfiguration {
    #[serde(rename="AmlToken")]
    AmlToken {
    },
    #[serde(rename="ManagedIdentity")]
    ManagedIdentity {
    },
    #[serde(rename="UserIdentity")]
    UserIdentity {
    },
}

impl Default for IdentityConfiguration {
    fn default() -> Self {
        Self::AmlToken {
        }
        
    }
}


