/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ImageModelDistributionSettings : Distribution expressions to sweep over values of model settings.  <example>  Some examples are:  ```  ModelName = \"choice('seresnext', 'resnest50')\";  LearningRate = \"uniform(0.001, 0.01)\";  LayersToFreeze = \"choice(0, 2)\";  ```</example>  All distributions can be specified as distribution_name(min, max) or choice(val1, val2, ..., valn)  where distribution name can be: uniform, quniform, loguniform, etc  For more details on how to compose distribution expressions please check the documentation:  https://docs.microsoft.com/en-us/azure/machine-learning/how-to-tune-hyperparameters  For more information on the available settings please visit the official documentation:  https://docs.microsoft.com/en-us/azure/machine-learning/how-to-auto-train-image-models.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImageModelDistributionSettings {
    /// Enable AMSGrad when optimizer is 'adam' or 'adamw'.
    #[serde(rename = "amsGradient", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ams_gradient: Option<Option<String>>,
    /// Settings for using Augmentations.
    #[serde(rename = "augmentations", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub augmentations: Option<Option<String>>,
    /// Value of 'beta1' when optimizer is 'adam' or 'adamw'. Must be a float in the range [0, 1].
    #[serde(rename = "beta1", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub beta1: Option<Option<String>>,
    /// Value of 'beta2' when optimizer is 'adam' or 'adamw'. Must be a float in the range [0, 1].
    #[serde(rename = "beta2", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub beta2: Option<Option<String>>,
    /// Whether to use distributer training.
    #[serde(rename = "distributed", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub distributed: Option<Option<String>>,
    /// Enable early stopping logic during training.
    #[serde(rename = "earlyStopping", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub early_stopping: Option<Option<String>>,
    /// Minimum number of epochs or validation evaluations to wait before primary metric improvement  is tracked for early stopping. Must be a positive integer.
    #[serde(rename = "earlyStoppingDelay", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub early_stopping_delay: Option<Option<String>>,
    /// Minimum number of epochs or validation evaluations with no primary metric improvement before  the run is stopped. Must be a positive integer.
    #[serde(rename = "earlyStoppingPatience", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub early_stopping_patience: Option<Option<String>>,
    /// Enable normalization when exporting ONNX model.
    #[serde(rename = "enableOnnxNormalization", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub enable_onnx_normalization: Option<Option<String>>,
    /// Frequency to evaluate validation dataset to get metric scores. Must be a positive integer.
    #[serde(rename = "evaluationFrequency", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub evaluation_frequency: Option<Option<String>>,
    /// Gradient accumulation means running a configured number of \"GradAccumulationStep\" steps without  updating the model weights while accumulating the gradients of those steps, and then using  the accumulated gradients to compute the weight updates. Must be a positive integer.
    #[serde(rename = "gradientAccumulationStep", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub gradient_accumulation_step: Option<Option<String>>,
    /// Number of layers to freeze for the model. Must be a positive integer.  For instance, passing 2 as value for 'seresnext' means  freezing layer0 and layer1. For a full list of models supported and details on layer freeze, please  see: https://docs.microsoft.com/en-us/azure/machine-learning/how-to-auto-train-image-models.
    #[serde(rename = "layersToFreeze", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub layers_to_freeze: Option<Option<String>>,
    /// Initial learning rate. Must be a float in the range [0, 1].
    #[serde(rename = "learningRate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub learning_rate: Option<Option<String>>,
    /// Type of learning rate scheduler. Must be 'warmup_cosine' or 'step'.
    #[serde(rename = "learningRateScheduler", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub learning_rate_scheduler: Option<Option<String>>,
    /// Name of the model to use for training.  For more information on the available models please visit the official documentation:  https://docs.microsoft.com/en-us/azure/machine-learning/how-to-auto-train-image-models.
    #[serde(rename = "modelName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub model_name: Option<Option<String>>,
    /// Value of momentum when optimizer is 'sgd'. Must be a float in the range [0, 1].
    #[serde(rename = "momentum", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub momentum: Option<Option<String>>,
    /// Enable nesterov when optimizer is 'sgd'.
    #[serde(rename = "nesterov", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub nesterov: Option<Option<String>>,
    /// Number of training epochs. Must be a positive integer.
    #[serde(rename = "numberOfEpochs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub number_of_epochs: Option<Option<String>>,
    /// Number of data loader workers. Must be a non-negative integer.
    #[serde(rename = "numberOfWorkers", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub number_of_workers: Option<Option<String>>,
    /// Type of optimizer. Must be either 'sgd', 'adam', or 'adamw'.
    #[serde(rename = "optimizer", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub optimizer: Option<Option<String>>,
    /// Random seed to be used when using deterministic training.
    #[serde(rename = "randomSeed", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub random_seed: Option<Option<String>>,
    /// Value of gamma when learning rate scheduler is 'step'. Must be a float in the range [0, 1].
    #[serde(rename = "stepLRGamma", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub step_lr_gamma: Option<Option<String>>,
    /// Value of step size when learning rate scheduler is 'step'. Must be a positive integer.
    #[serde(rename = "stepLRStepSize", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub step_lr_step_size: Option<Option<String>>,
    /// Training batch size. Must be a positive integer.
    #[serde(rename = "trainingBatchSize", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub training_batch_size: Option<Option<String>>,
    /// Validation batch size. Must be a positive integer.
    #[serde(rename = "validationBatchSize", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub validation_batch_size: Option<Option<String>>,
    /// Value of cosine cycle when learning rate scheduler is 'warmup_cosine'. Must be a float in the range [0, 1].
    #[serde(rename = "warmupCosineLRCycles", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub warmup_cosine_lr_cycles: Option<Option<String>>,
    /// Value of warmup epochs when learning rate scheduler is 'warmup_cosine'. Must be a positive integer.
    #[serde(rename = "warmupCosineLRWarmupEpochs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub warmup_cosine_lr_warmup_epochs: Option<Option<String>>,
    /// Value of weight decay when optimizer is 'sgd', 'adam', or 'adamw'. Must be a float in the range[0, 1].
    #[serde(rename = "weightDecay", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub weight_decay: Option<Option<String>>,
}

impl ImageModelDistributionSettings {
    /// Distribution expressions to sweep over values of model settings.  <example>  Some examples are:  ```  ModelName = \"choice('seresnext', 'resnest50')\";  LearningRate = \"uniform(0.001, 0.01)\";  LayersToFreeze = \"choice(0, 2)\";  ```</example>  All distributions can be specified as distribution_name(min, max) or choice(val1, val2, ..., valn)  where distribution name can be: uniform, quniform, loguniform, etc  For more details on how to compose distribution expressions please check the documentation:  https://docs.microsoft.com/en-us/azure/machine-learning/how-to-tune-hyperparameters  For more information on the available settings please visit the official documentation:  https://docs.microsoft.com/en-us/azure/machine-learning/how-to-auto-train-image-models.
    pub fn new() -> ImageModelDistributionSettings {
        ImageModelDistributionSettings {
            ams_gradient: None,
            augmentations: None,
            beta1: None,
            beta2: None,
            distributed: None,
            early_stopping: None,
            early_stopping_delay: None,
            early_stopping_patience: None,
            enable_onnx_normalization: None,
            evaluation_frequency: None,
            gradient_accumulation_step: None,
            layers_to_freeze: None,
            learning_rate: None,
            learning_rate_scheduler: None,
            model_name: None,
            momentum: None,
            nesterov: None,
            number_of_epochs: None,
            number_of_workers: None,
            optimizer: None,
            random_seed: None,
            step_lr_gamma: None,
            step_lr_step_size: None,
            training_batch_size: None,
            validation_batch_size: None,
            warmup_cosine_lr_cycles: None,
            warmup_cosine_lr_warmup_epochs: None,
            weight_decay: None,
        }
    }
}

