/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ImageSweepSettings : Model sweeping and hyperparameter sweeping related settings.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImageSweepSettings {
    #[serde(rename = "earlyTermination", skip_serializing_if = "Option::is_none")]
    pub early_termination: Option<Box<models::EarlyTerminationPolicy>>,
    #[serde(rename = "samplingAlgorithm")]
    pub sampling_algorithm: models::SamplingAlgorithmType,
}

impl ImageSweepSettings {
    /// Model sweeping and hyperparameter sweeping related settings.
    pub fn new(sampling_algorithm: models::SamplingAlgorithmType) -> ImageSweepSettings {
        ImageSweepSettings {
            early_termination: None,
            sampling_algorithm,
        }
    }
}
