/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ImageModelSettings : Settings used for training the model.  For more information on the available settings please visit the official documentation:  https://docs.microsoft.com/en-us/azure/machine-learning/how-to-auto-train-image-models.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImageModelSettings {
    /// Settings for advanced scenarios.
    #[serde(
        rename = "advancedSettings",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub advanced_settings: Option<Option<String>>,
    /// Enable AMSGrad when optimizer is 'adam' or 'adamw'.
    #[serde(
        rename = "amsGradient",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub ams_gradient: Option<Option<bool>>,
    /// Settings for using Augmentations.
    #[serde(
        rename = "augmentations",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub augmentations: Option<Option<String>>,
    /// Value of 'beta1' when optimizer is 'adam' or 'adamw'. Must be a float in the range [0, 1].
    #[serde(
        rename = "beta1",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub beta1: Option<Option<f32>>,
    /// Value of 'beta2' when optimizer is 'adam' or 'adamw'. Must be a float in the range [0, 1].
    #[serde(
        rename = "beta2",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub beta2: Option<Option<f32>>,
    /// Frequency to store model checkpoints. Must be a positive integer.
    #[serde(
        rename = "checkpointFrequency",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub checkpoint_frequency: Option<Option<i32>>,
    #[serde(rename = "checkpointModel", skip_serializing_if = "Option::is_none")]
    pub checkpoint_model: Option<Box<models::MlFlowModelJobInput>>,
    /// The id of a previous run that has a pretrained checkpoint for incremental training.
    #[serde(
        rename = "checkpointRunId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub checkpoint_run_id: Option<Option<String>>,
    /// Whether to use distributed training.
    #[serde(
        rename = "distributed",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub distributed: Option<Option<bool>>,
    /// Enable early stopping logic during training.
    #[serde(
        rename = "earlyStopping",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub early_stopping: Option<Option<bool>>,
    /// Minimum number of epochs or validation evaluations to wait before primary metric improvement  is tracked for early stopping. Must be a positive integer.
    #[serde(
        rename = "earlyStoppingDelay",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub early_stopping_delay: Option<Option<i32>>,
    /// Minimum number of epochs or validation evaluations with no primary metric improvement before  the run is stopped. Must be a positive integer.
    #[serde(
        rename = "earlyStoppingPatience",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub early_stopping_patience: Option<Option<i32>>,
    /// Enable normalization when exporting ONNX model.
    #[serde(
        rename = "enableOnnxNormalization",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub enable_onnx_normalization: Option<Option<bool>>,
    /// Frequency to evaluate validation dataset to get metric scores. Must be a positive integer.
    #[serde(
        rename = "evaluationFrequency",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub evaluation_frequency: Option<Option<i32>>,
    /// Gradient accumulation means running a configured number of \"GradAccumulationStep\" steps without  updating the model weights while accumulating the gradients of those steps, and then using  the accumulated gradients to compute the weight updates. Must be a positive integer.
    #[serde(
        rename = "gradientAccumulationStep",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub gradient_accumulation_step: Option<Option<i32>>,
    /// Number of layers to freeze for the model. Must be a positive integer.  For instance, passing 2 as value for 'seresnext' means  freezing layer0 and layer1. For a full list of models supported and details on layer freeze, please  see: https://docs.microsoft.com/en-us/azure/machine-learning/how-to-auto-train-image-models.
    #[serde(
        rename = "layersToFreeze",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub layers_to_freeze: Option<Option<i32>>,
    /// Initial learning rate. Must be a float in the range [0, 1].
    #[serde(
        rename = "learningRate",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub learning_rate: Option<Option<f32>>,
    #[serde(
        rename = "learningRateScheduler",
        skip_serializing_if = "Option::is_none"
    )]
    pub learning_rate_scheduler: Option<models::LearningRateScheduler>,
    /// Name of the model to use for training.  For more information on the available models please visit the official documentation:  https://docs.microsoft.com/en-us/azure/machine-learning/how-to-auto-train-image-models.
    #[serde(
        rename = "modelName",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub model_name: Option<Option<String>>,
    /// Value of momentum when optimizer is 'sgd'. Must be a float in the range [0, 1].
    #[serde(
        rename = "momentum",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub momentum: Option<Option<f32>>,
    /// Enable nesterov when optimizer is 'sgd'.
    #[serde(
        rename = "nesterov",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub nesterov: Option<Option<bool>>,
    /// Number of training epochs. Must be a positive integer.
    #[serde(
        rename = "numberOfEpochs",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub number_of_epochs: Option<Option<i32>>,
    /// Number of data loader workers. Must be a non-negative integer.
    #[serde(
        rename = "numberOfWorkers",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub number_of_workers: Option<Option<i32>>,
    #[serde(rename = "optimizer", skip_serializing_if = "Option::is_none")]
    pub optimizer: Option<models::StochasticOptimizer>,
    /// Random seed to be used when using deterministic training.
    #[serde(
        rename = "randomSeed",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub random_seed: Option<Option<i32>>,
    /// Value of gamma when learning rate scheduler is 'step'. Must be a float in the range [0, 1].
    #[serde(
        rename = "stepLRGamma",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub step_lr_gamma: Option<Option<f32>>,
    /// Value of step size when learning rate scheduler is 'step'. Must be a positive integer.
    #[serde(
        rename = "stepLRStepSize",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub step_lr_step_size: Option<Option<i32>>,
    /// Training batch size. Must be a positive integer.
    #[serde(
        rename = "trainingBatchSize",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub training_batch_size: Option<Option<i32>>,
    /// Validation batch size. Must be a positive integer.
    #[serde(
        rename = "validationBatchSize",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub validation_batch_size: Option<Option<i32>>,
    /// Value of cosine cycle when learning rate scheduler is 'warmup_cosine'. Must be a float in the range [0, 1].
    #[serde(
        rename = "warmupCosineLRCycles",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub warmup_cosine_lr_cycles: Option<Option<f32>>,
    /// Value of warmup epochs when learning rate scheduler is 'warmup_cosine'. Must be a positive integer.
    #[serde(
        rename = "warmupCosineLRWarmupEpochs",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub warmup_cosine_lr_warmup_epochs: Option<Option<i32>>,
    /// Value of weight decay when optimizer is 'sgd', 'adam', or 'adamw'. Must be a float in the range[0, 1].
    #[serde(
        rename = "weightDecay",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub weight_decay: Option<Option<f32>>,
}

impl ImageModelSettings {
    /// Settings used for training the model.  For more information on the available settings please visit the official documentation:  https://docs.microsoft.com/en-us/azure/machine-learning/how-to-auto-train-image-models.
    pub fn new() -> ImageModelSettings {
        ImageModelSettings {
            advanced_settings: None,
            ams_gradient: None,
            augmentations: None,
            beta1: None,
            beta2: None,
            checkpoint_frequency: None,
            checkpoint_model: None,
            checkpoint_run_id: None,
            distributed: None,
            early_stopping: None,
            early_stopping_delay: None,
            early_stopping_patience: None,
            enable_onnx_normalization: None,
            evaluation_frequency: None,
            gradient_accumulation_step: None,
            layers_to_freeze: None,
            learning_rate: None,
            learning_rate_scheduler: None,
            model_name: None,
            momentum: None,
            nesterov: None,
            number_of_epochs: None,
            number_of_workers: None,
            optimizer: None,
            random_seed: None,
            step_lr_gamma: None,
            step_lr_step_size: None,
            training_batch_size: None,
            validation_batch_size: None,
            warmup_cosine_lr_cycles: None,
            warmup_cosine_lr_warmup_epochs: None,
            weight_decay: None,
        }
    }
}
