/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ImageLimitSettings : Limit settings for the AutoML job.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImageLimitSettings {
    /// Maximum number of concurrent AutoML iterations.
    #[serde(rename = "maxConcurrentTrials", skip_serializing_if = "Option::is_none")]
    pub max_concurrent_trials: Option<i32>,
    /// Maximum number of AutoML iterations.
    #[serde(rename = "maxTrials", skip_serializing_if = "Option::is_none")]
    pub max_trials: Option<i32>,
    /// AutoML job timeout.
    #[serde(rename = "timeout", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<String>,
}

impl ImageLimitSettings {
    /// Limit settings for the AutoML job.
    pub fn new() -> ImageLimitSettings {
        ImageLimitSettings {
            max_concurrent_trials: None,
            max_trials: None,
            timeout: None,
        }
    }
}

