/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IndexColumn : DTO object representing index column
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexColumn {
    /// Specifies the column name
    #[serde(
        rename = "columnName",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub column_name: Option<Option<String>>,
    #[serde(rename = "dataType", skip_serializing_if = "Option::is_none")]
    pub data_type: Option<models::FeatureDataType>,
}

impl IndexColumn {
    /// DTO object representing index column
    pub fn new() -> IndexColumn {
        IndexColumn {
            column_name: None,
            data_type: None,
        }
    }
}
