/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// InputDeliveryMode : Enum to determine the input data delivery mode.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum InputDeliveryMode {
    #[serde(rename = "ReadOnlyMount")]
    ReadOnlyMount,
    #[serde(rename = "ReadWriteMount")]
    ReadWriteMount,
    #[serde(rename = "Download")]
    Download,
    #[serde(rename = "Direct")]
    Direct,
    #[serde(rename = "EvalMount")]
    EvalMount,
    #[serde(rename = "EvalDownload")]
    EvalDownload,
}

impl Default for InputDeliveryMode {
    fn default() -> Self {
        Self::ReadOnlyMount
    }
}

impl std::fmt::Display for InputDeliveryMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ReadOnlyMount => write!(f, "ReadOnlyMount"),
            Self::ReadWriteMount => write!(f, "ReadWriteMount"),
            Self::Download => write!(f, "Download"),
            Self::Direct => write!(f, "Direct"),
            Self::EvalMount => write!(f, "EvalMount"),
            Self::EvalDownload => write!(f, "EvalDownload"),
        }
    }
}

impl std::str::FromStr for InputDeliveryMode {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "ReadOnlyMount" => Ok(Self::ReadOnlyMount),
            "ReadWriteMount" => Ok(Self::ReadWriteMount),
            "Download" => Ok(Self::Download),
            "Direct" => Ok(Self::Direct),
            "EvalMount" => Ok(Self::EvalMount),
            "EvalDownload" => Ok(Self::EvalDownload),
            _ => Err(format!("Invalid InputDeliveryMode: {}", s)),
        }
    }
}
