/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Job : Union type for all job types
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "jobType")]
pub enum Job {
    #[serde(rename = "AutoML")]
    AutoML(models::AutoMlJob),
    #[serde(rename = "Command")]
    Command(models::CommandJob),
    #[serde(rename = "Pipeline")]
    Pipeline(models::PipelineJob),
    #[serde(rename = "Sweep")]
    Sweep(models::SweepJob),
    #[serde(rename = "Spark")]
    Spark(models::SparkJob),
}
