/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// JobOutputType : Enum to determine the Job Output Type.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
pub enum JobOutputType {
    #[serde(rename = "uri_file")]
    #[default]
    UriFile,
    #[serde(rename = "uri_folder")]
    UriFolder,
    #[serde(rename = "mltable")]
    MlTable,
    #[serde(rename = "custom_model")]
    CustomModel,
    #[serde(rename = "mlflow_model")]
    MlFlowModel,
    #[serde(rename = "triton_model")]
    TritonModel,
}

impl std::fmt::Display for JobOutputType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::UriFile => write!(f, "uri_file"),
            Self::UriFolder => write!(f, "uri_folder"),
            Self::MlTable => write!(f, "mltable"),
            Self::CustomModel => write!(f, "custom_model"),
            Self::MlFlowModel => write!(f, "mlflow_model"),
            Self::TritonModel => write!(f, "triton_model"),
        }
    }
}

impl std::str::FromStr for JobOutputType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "uri_file" => Ok(Self::UriFile),
            "uri_folder" => Ok(Self::UriFolder),
            "mltable" => Ok(Self::MlTable),
            "custom_model" => Ok(Self::CustomModel),
            "mlflow_model" => Ok(Self::MlFlowModel),
            "triton_model" => Ok(Self::TritonModel),
            _ => Err(format!("Invalid JobOutputType: {}", s)),
        }
    }
}
