/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JobBase : Base definition for a job.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobBase {
    /// ARM resource ID of the component resource.
    #[serde(
        rename = "componentId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub component_id: Option<Option<String>>,
    /// ARM resource ID of the compute resource.
    #[serde(
        rename = "computeId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub compute_id: Option<Option<String>>,
    /// Display name of job.
    #[serde(
        rename = "displayName",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub display_name: Option<Option<String>>,
    /// The name of the experiment the job belongs to. If not set, the job is placed in the \"Default\" experiment.
    #[serde(rename = "experimentName", skip_serializing_if = "Option::is_none")]
    pub experiment_name: Option<String>,
    #[serde(rename = "identity", skip_serializing_if = "Option::is_none")]
    pub identity: Option<Box<models::IdentityConfiguration>>,
    /// Is the asset archived?
    #[serde(rename = "isArchived", skip_serializing_if = "Option::is_none")]
    pub is_archived: Option<bool>,
    #[serde(rename = "jobType")]
    pub job_type: models::JobType,
    #[serde(
        rename = "notificationSetting",
        skip_serializing_if = "Option::is_none"
    )]
    pub notification_setting: Option<Box<models::NotificationSetting>>,
    /// List of JobEndpoints.  For local jobs, a job endpoint will have an endpoint value of FileStreamObject.
    #[serde(
        rename = "services",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub services: Option<Option<std::collections::HashMap<String, models::JobService>>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::JobStatus>,
    /// The asset description text.
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    /// The asset property dictionary.
    #[serde(
        rename = "properties",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub properties: Option<Option<std::collections::HashMap<String, String>>>,
    /// Tag dictionary. Tags can be added, removed, and updated.
    #[serde(
        rename = "tags",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tags: Option<Option<std::collections::HashMap<String, String>>>,
}

impl JobBase {
    /// Base definition for a job.
    pub fn new(job_type: models::JobType) -> JobBase {
        JobBase {
            component_id: None,
            compute_id: None,
            display_name: None,
            experiment_name: None,
            identity: None,
            is_archived: None,
            job_type,
            notification_setting: None,
            services: None,
            status: None,
            description: None,
            properties: None,
            tags: None,
        }
    }
}
