/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// JobOutput : Job output definition container information on where to find job output/logs.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "jobOutputType")]
pub enum JobOutput {
    #[serde(rename="CustomModelJobOutput")]
    CustomModelJobOutput {
        /// Description for the output.
        #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
        description: Option<String>,
    },
    #[serde(rename="MLFlowModelJobOutput")]
    MlFlowModelJobOutput {
        /// Description for the output.
        #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
        description: Option<String>,
    },
    #[serde(rename="MLTableJobOutput")]
    MlTableJobOutput {
        /// Description for the output.
        #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
        description: Option<String>,
    },
    #[serde(rename="TritonModelJobOutput")]
    TritonModelJobOutput {
        /// Description for the output.
        #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
        description: Option<String>,
    },
    #[serde(rename="UriFileJobOutput")]
    UriFileJobOutput {
        /// Description for the output.
        #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
        description: Option<String>,
    },
    #[serde(rename="UriFolderJobOutput")]
    UriFolderJobOutput {
        /// Description for the output.
        #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
        description: Option<String>,
    },
}

impl Default for JobOutput {
    fn default() -> Self {
        Self::CustomModelJobOutput {
            description: Default::default(),
        }
        
    }
}


