/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JobTier : Enum to determine the job tier.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum JobTier {
    #[serde(rename = "Null")]
    Null,
    #[serde(rename = "Spot")]
    Spot,
    #[serde(rename = "Basic")]
    Basic,
    #[serde(rename = "Standard")]
    Standard,
    #[serde(rename = "Premium")]
    Premium,
}

impl Default for JobTier {
    fn default() -> Self {
        Self::Null
    }
}

impl std::fmt::Display for JobTier {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Null => write!(f, "Null"),
            Self::Spot => write!(f, "Spot"),
            Self::Basic => write!(f, "Basic"),
            Self::Standard => write!(f, "Standard"),
            Self::Premium => write!(f, "Premium"),
        }
    }
}

impl std::str::FromStr for JobTier {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Null" => Ok(Self::Null),
            "Spot" => Ok(Self::Spot),
            "Basic" => Ok(Self::Basic),
            "Standard" => Ok(Self::Standard),
            "Premium" => Ok(Self::Premium),
            _ => Err(format!("Invalid JobTier: {}", s)),
        }
    }
}
