/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JobInput : Command job definition.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "jobInputType")]
pub enum JobInput {
    #[serde(rename="CustomModelJobInput")]
    CustomModelJobInput {
        /// Description for the input.
        #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
        description: Option<String>,
    },
    #[serde(rename="LiteralJobInput")]
    LiteralJobInput {
        /// Description for the input.
        #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
        description: Option<String>,
    },
    #[serde(rename="MLFlowModelJobInput")]
    MlFlowModelJobInput {
        /// Description for the input.
        #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
        description: Option<String>,
    },
    #[serde(rename="MLTableJobInput")]
    MlTableJobInput {
        /// Description for the input.
        #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
        description: Option<String>,
    },
    #[serde(rename="TritonModelJobInput")]
    TritonModelJobInput {
        /// Description for the input.
        #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
        description: Option<String>,
    },
    #[serde(rename="UriFileJobInput")]
    UriFileJobInput {
        /// Description for the input.
        #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
        description: Option<String>,
    },
    #[serde(rename="UriFolderJobInput")]
    UriFolderJobInput {
        /// Description for the input.
        #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
        description: Option<String>,
    },
}

impl Default for JobInput {
    fn default() -> Self {
        Self::CustomModelJobInput {
            description: Default::default(),
        }
        
    }
}


