/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "jobLimitsType")]
pub enum JobLimits {
    #[serde(rename="CommandJobLimits")]
    CommandJobLimits {
        /// The max run duration in ISO 8601 format, after which the job will be cancelled. Only supports duration with precision as low as Seconds.
        #[serde(rename = "timeout", skip_serializing_if = "Option::is_none")]
        timeout: Option<String>,
    },
    #[serde(rename="SweepJobLimits")]
    SweepJobLimits {
        /// The max run duration in ISO 8601 format, after which the job will be cancelled. Only supports duration with precision as low as Seconds.
        #[serde(rename = "timeout", skip_serializing_if = "Option::is_none")]
        timeout: Option<String>,
    },
}

impl Default for JobLimits {
    fn default() -> Self {
        Self::CommandJobLimits {
            timeout: Default::default(),
        }
        
    }
}


