/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JobService : Job endpoint definition
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobService {
    /// Url for endpoint.
    #[serde(rename = "endpoint", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub endpoint: Option<Option<String>>,
    /// Any error in the service.
    #[serde(rename = "errorMessage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<Option<String>>,
    /// Endpoint type.
    #[serde(rename = "jobServiceType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub job_service_type: Option<Option<String>>,
    #[serde(rename = "nodes", skip_serializing_if = "Option::is_none")]
    pub nodes: Option<Box<models::Nodes>>,
    /// Port for endpoint.
    #[serde(rename = "port", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub port: Option<Option<i32>>,
    /// Additional properties to set on the endpoint.
    #[serde(rename = "properties", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Option<std::collections::HashMap<String, String>>>,
    /// Status of endpoint.
    #[serde(rename = "status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status: Option<Option<String>>,
}

impl JobService {
    /// Job endpoint definition
    pub fn new() -> JobService {
        JobService {
            endpoint: None,
            error_message: None,
            job_service_type: None,
            nodes: None,
            port: None,
            properties: None,
            status: None,
        }
    }
}

