/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobScheduleAction {
    #[serde(rename = "jobDefinition")]
    pub job_definition: Box<models::JobBase>,
    #[serde(rename = "actionType")]
    pub action_type: models::ScheduleActionType,
}

impl JobScheduleAction {
    pub fn new(
        job_definition: models::JobBase,
        action_type: models::ScheduleActionType,
    ) -> JobScheduleAction {
        JobScheduleAction {
            job_definition: Box::new(job_definition),
            action_type,
        }
    }
}
