/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobResourceConfiguration {
    /// Extra arguments to pass to the Docker run command. This would override any parameters that have already been set by the system, or in this section. This parameter is only supported for Azure ML compute types.
    #[serde(
        rename = "dockerArgs",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub docker_args: Option<Option<String>>,
    /// Size of the docker container's shared memory block. This should be in the format of (number)(unit) where number as to be greater than 0 and the unit can be one of b(bytes), k(kilobytes), m(megabytes), or g(gigabytes).
    #[serde(rename = "shmSize", skip_serializing_if = "Option::is_none")]
    pub shm_size: Option<String>,
    /// Optional number of instances or nodes used by the compute target.
    #[serde(rename = "instanceCount", skip_serializing_if = "Option::is_none")]
    pub instance_count: Option<i32>,
    /// Optional type of VM used as supported by the compute target.
    #[serde(
        rename = "instanceType",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub instance_type: Option<Option<String>>,
    /// Additional properties bag.
    #[serde(
        rename = "properties",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub properties: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
}

impl JobResourceConfiguration {
    pub fn new() -> JobResourceConfiguration {
        JobResourceConfiguration {
            docker_args: None,
            shm_size: None,
            instance_count: None,
            instance_type: None,
            properties: None,
        }
    }
}
