/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// JobLimitsType : JobLimitsType enum
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
pub enum JobLimitsType {
    #[serde(rename = "Command")]
    #[default]
    Command,
    #[serde(rename = "Sweep")]
    Sweep,
}

impl std::fmt::Display for JobLimitsType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Command => write!(f, "Command"),
            Self::Sweep => write!(f, "Sweep"),
        }
    }
}

impl std::str::FromStr for JobLimitsType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Command" => Ok(Self::Command),
            "Sweep" => Ok(Self::Sweep),
            _ => Err(format!("Invalid JobLimitsType: {}", s)),
        }
    }
}
