/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// KeyType : KeyType enum
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum KeyType {
    #[serde(rename = "Primary")]
    Primary,
    #[serde(rename = "Secondary")]
    Secondary,
}

impl Default for KeyType {
    fn default() -> Self {
        Self::Primary
    }
}

impl std::fmt::Display for KeyType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Primary => write!(f, "Primary"),
            Self::Secondary => write!(f, "Secondary"),
        }
    }
}

impl std::str::FromStr for KeyType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Primary" => Ok(Self::Primary),
            "Secondary" => Ok(Self::Secondary),
            _ => Err(format!("Invalid KeyType: {}", s)),
        }
    }
}
