/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ListViewType : ListViewType enum
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
pub enum ListViewType {
    #[serde(rename = "ActiveOnly")]
    #[default]
    ActiveOnly,
    #[serde(rename = "ArchivedOnly")]
    ArchivedOnly,
    #[serde(rename = "All")]
    All,
}

impl std::fmt::Display for ListViewType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ActiveOnly => write!(f, "ActiveOnly"),
            Self::ArchivedOnly => write!(f, "ArchivedOnly"),
            Self::All => write!(f, "All"),
        }
    }
}

impl std::str::FromStr for ListViewType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "ActiveOnly" => Ok(Self::ActiveOnly),
            "ArchivedOnly" => Ok(Self::ArchivedOnly),
            "All" => Ok(Self::All),
            _ => Err(format!("Invalid ListViewType: {}", s)),
        }
    }
}
