/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// LogVerbosity : Enum for setting log verbosity.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
pub enum LogVerbosity {
    #[serde(rename = "NotSet")]
    #[default]
    NotSet,
    #[serde(rename = "Debug")]
    Debug,
    #[serde(rename = "Info")]
    Info,
    #[serde(rename = "Warning")]
    Warning,
    #[serde(rename = "Error")]
    Error,
    #[serde(rename = "Critical")]
    Critical,
}

impl std::fmt::Display for LogVerbosity {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::NotSet => write!(f, "NotSet"),
            Self::Debug => write!(f, "Debug"),
            Self::Info => write!(f, "Info"),
            Self::Warning => write!(f, "Warning"),
            Self::Error => write!(f, "Error"),
            Self::Critical => write!(f, "Critical"),
        }
    }
}

impl std::str::FromStr for LogVerbosity {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "NotSet" => Ok(Self::NotSet),
            "Debug" => Ok(Self::Debug),
            "Info" => Ok(Self::Info),
            "Warning" => Ok(Self::Warning),
            "Error" => Ok(Self::Error),
            "Critical" => Ok(Self::Critical),
            _ => Err(format!("Invalid LogVerbosity: {}", s)),
        }
    }
}
