/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ManagedServiceIdentityType : Type of managed service identity (where both SystemAssigned and UserAssigned types are allowed).
/// Type of managed service identity (where both SystemAssigned and UserAssigned types are allowed).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default)]
pub enum ManagedServiceIdentityType {
    #[serde(rename = "None")]
    #[default]
    None,
    #[serde(rename = "SystemAssigned")]
    SystemAssigned,
    #[serde(rename = "UserAssigned")]
    UserAssigned,
    #[serde(rename = "SystemAssigned,UserAssigned")]
    SystemAssignedCommaUserAssigned,
}

impl std::fmt::Display for ManagedServiceIdentityType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::None => write!(f, "None"),
            Self::SystemAssigned => write!(f, "SystemAssigned"),
            Self::UserAssigned => write!(f, "UserAssigned"),
            Self::SystemAssignedCommaUserAssigned => write!(f, "SystemAssigned,UserAssigned"),
        }
    }
}
