/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ManagedIdentityCredential : Credential for user managed identity
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ManagedIdentityCredential {
    /// ManagedIdentityCredential identity type
    #[serde(rename = "managedIdentityType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub managed_identity_type: Option<Option<String>>,
    /// ClientId for the UAMI. For ManagedIdentityType = SystemManaged, this field is null.
    #[serde(rename = "userManagedIdentityClientId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_managed_identity_client_id: Option<Option<String>>,
    /// PrincipalId for the UAMI. For ManagedIdentityType = SystemManaged, this field is null.
    #[serde(rename = "userManagedIdentityPrincipalId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_managed_identity_principal_id: Option<Option<String>>,
    /// Full arm scope for the Id. For ManagedIdentityType = SystemManaged, this field is null.
    #[serde(rename = "userManagedIdentityResourceId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_managed_identity_resource_id: Option<Option<String>>,
    /// TenantId for the UAMI. For ManagedIdentityType = SystemManaged, this field is null.
    #[serde(rename = "userManagedIdentityTenantId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_managed_identity_tenant_id: Option<Option<String>>,
    #[serde(rename = "credentialType")]
    pub credential_type: models::DataReferenceCredentialType,
}

impl ManagedIdentityCredential {
    /// Credential for user managed identity
    pub fn new(credential_type: models::DataReferenceCredentialType) -> ManagedIdentityCredential {
        ManagedIdentityCredential {
            managed_identity_type: None,
            user_managed_identity_client_id: None,
            user_managed_identity_principal_id: None,
            user_managed_identity_resource_id: None,
            user_managed_identity_tenant_id: None,
            credential_type,
        }
    }
}

