/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ManagedComputeIdentity : Managed compute identity definition.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ManagedComputeIdentity {
    #[serde(rename = "identity", skip_serializing_if = "Option::is_none")]
    pub identity: Option<Box<models::ManagedServiceIdentity>>,
    #[serde(rename = "computeIdentityType")]
    pub compute_identity_type: models::MonitorComputeIdentityType,
}

impl ManagedComputeIdentity {
    /// Managed compute identity definition.
    pub fn new(
        compute_identity_type: models::MonitorComputeIdentityType,
    ) -> ManagedComputeIdentity {
        ManagedComputeIdentity {
            identity: None,
            compute_identity_type,
        }
    }
}
