/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ManagedServiceIdentity : Managed service identity (system assigned and/or user assigned identities)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ManagedServiceIdentity {
    /// The service principal ID of the system assigned identity. This property will only be provided for a system assigned identity.
    #[serde(rename = "principalId", skip_serializing_if = "Option::is_none")]
    pub principal_id: Option<uuid::Uuid>,
    /// The tenant ID of the system assigned identity. This property will only be provided for a system assigned identity.
    #[serde(rename = "tenantId", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<uuid::Uuid>,
    #[serde(rename = "type")]
    pub r#type: models::ManagedServiceIdentityType,
    /// The set of user assigned identities associated with the resource. The userAssignedIdentities dictionary keys will be ARM resource ids in the form: '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{identityName}. The dictionary values can be empty objects ({}) in requests.
    #[serde(
        rename = "userAssignedIdentities",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_assigned_identities:
        Option<std::collections::HashMap<String, models::UserAssignedIdentity>>,
}

impl ManagedServiceIdentity {
    /// Managed service identity (system assigned and/or user assigned identities)
    pub fn new(r#type: models::ManagedServiceIdentityType) -> ManagedServiceIdentity {
        ManagedServiceIdentity {
            principal_id: None,
            tenant_id: None,
            r#type,
            user_assigned_identities: None,
        }
    }
}
