/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// MarketplaceSubscriptionStatus : MarketplaceSubscriptionStatus enum
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum MarketplaceSubscriptionStatus {
    #[serde(rename = "Subscribed")]
    Subscribed,
    #[serde(rename = "Suspended")]
    Suspended,
    #[serde(rename = "Unsubscribed")]
    Unsubscribed,
}

impl Default for MarketplaceSubscriptionStatus {
    fn default() -> Self {
        Self::Subscribed
    }
}

impl std::fmt::Display for MarketplaceSubscriptionStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Subscribed => write!(f, "Subscribed"),
            Self::Suspended => write!(f, "Suspended"),
            Self::Unsubscribed => write!(f, "Unsubscribed"),
        }
    }
}

impl std::str::FromStr for MarketplaceSubscriptionStatus {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Subscribed" => Ok(Self::Subscribed),
            "Suspended" => Ok(Self::Suspended),
            "Unsubscribed" => Ok(Self::Unsubscribed),
            _ => Err(format!("Invalid MarketplaceSubscriptionStatus: {}", s)),
        }
    }
}
