/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// MaterializationComputeResource : DTO object representing compute resource
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MaterializationComputeResource {
    /// Specifies the instance type
    #[serde(
        rename = "instanceType",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub instance_type: Option<Option<String>>,
}

impl MaterializationComputeResource {
    /// DTO object representing compute resource
    pub fn new() -> MaterializationComputeResource {
        MaterializationComputeResource {
            instance_type: None,
        }
    }
}
