/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MlTableData : MLTable data definition
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MlTableData {
    /// Uris referenced in the MLTable definition (required for lineage)
    #[serde(
        rename = "referencedUris",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub referenced_uris: Option<Option<Vec<String>>>,
    #[serde(rename = "dataType")]
    pub data_type: models::DataType,
    /// [Required] Uri of the data. Example: https://go.microsoft.com/fwlink/?linkid=2202330
    #[serde(rename = "dataUri")]
    pub data_uri: String,
    /// If the name version are system generated (anonymous registration).
    #[serde(rename = "isAnonymous", skip_serializing_if = "Option::is_none")]
    pub is_anonymous: Option<bool>,
    /// Is the asset archived?
    #[serde(rename = "isArchived", skip_serializing_if = "Option::is_none")]
    pub is_archived: Option<bool>,
    /// The asset description text.
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    /// The asset property dictionary.
    #[serde(
        rename = "properties",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub properties: Option<Option<std::collections::HashMap<String, String>>>,
    /// Tag dictionary. Tags can be added, removed, and updated.
    #[serde(
        rename = "tags",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tags: Option<Option<std::collections::HashMap<String, String>>>,
}

impl MlTableData {
    /// MLTable data definition
    pub fn new(data_type: models::DataType, data_uri: String) -> MlTableData {
        MlTableData {
            referenced_uris: None,
            data_type,
            data_uri,
            is_anonymous: None,
            is_archived: None,
            description: None,
            properties: None,
            tags: None,
        }
    }
}
