/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MlTableJobInput {
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<models::InputDeliveryMode>,
    /// [Required] Input Asset URI.
    #[serde(rename = "uri")]
    pub uri: String,
    /// Description for the input.
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    #[serde(rename = "jobInputType")]
    pub job_input_type: models::JobInputType,
}

impl MlTableJobInput {
    pub fn new(uri: String, job_input_type: models::JobInputType) -> MlTableJobInput {
        MlTableJobInput {
            mode: None,
            uri,
            description: None,
            job_input_type,
        }
    }
}
