/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ModelSize : Image model size.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
pub enum ModelSize {
    #[serde(rename = "None")]
    #[default]
    None,
    #[serde(rename = "Small")]
    Small,
    #[serde(rename = "Medium")]
    Medium,
    #[serde(rename = "Large")]
    Large,
    #[serde(rename = "ExtraLarge")]
    ExtraLarge,
}

impl std::fmt::Display for ModelSize {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::None => write!(f, "None"),
            Self::Small => write!(f, "Small"),
            Self::Medium => write!(f, "Medium"),
            Self::Large => write!(f, "Large"),
            Self::ExtraLarge => write!(f, "ExtraLarge"),
        }
    }
}

impl std::str::FromStr for ModelSize {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "None" => Ok(Self::None),
            "Small" => Ok(Self::Small),
            "Medium" => Ok(Self::Medium),
            "Large" => Ok(Self::Large),
            "ExtraLarge" => Ok(Self::ExtraLarge),
            _ => Err(format!("Invalid ModelSize: {}", s)),
        }
    }
}
