/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ModelVersion : Model asset version details.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelVersion {
    /// Mapping of model flavors to their properties.
    #[serde(rename = "flavors", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub flavors: Option<Option<std::collections::HashMap<String, models::FlavorData>>>,
    /// Name of the training job which produced this model
    #[serde(rename = "jobName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub job_name: Option<Option<String>>,
    /// The storage format for this entity. Used for NCD.
    #[serde(rename = "modelType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub model_type: Option<Option<String>>,
    /// The URI path to the model contents.
    #[serde(rename = "modelUri", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub model_uri: Option<Option<String>>,
    #[serde(rename = "provisioningState", skip_serializing_if = "Option::is_none")]
    pub provisioning_state: Option<models::AssetProvisioningState>,
    /// Stage in the model lifecycle assigned to this model
    #[serde(rename = "stage", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub stage: Option<Option<String>>,
    /// If the name version are system generated (anonymous registration).
    #[serde(rename = "isAnonymous", skip_serializing_if = "Option::is_none")]
    pub is_anonymous: Option<bool>,
    /// Is the asset archived?
    #[serde(rename = "isArchived", skip_serializing_if = "Option::is_none")]
    pub is_archived: Option<bool>,
    /// The asset description text.
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    /// The asset property dictionary.
    #[serde(rename = "properties", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Option<std::collections::HashMap<String, String>>>,
    /// Tag dictionary. Tags can be added, removed, and updated.
    #[serde(rename = "tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Option<std::collections::HashMap<String, String>>>,
}

impl ModelVersion {
    /// Model asset version details.
    pub fn new() -> ModelVersion {
        ModelVersion {
            flavors: None,
            job_name: None,
            model_type: None,
            model_uri: None,
            provisioning_state: None,
            stage: None,
            is_anonymous: None,
            is_archived: None,
            description: None,
            properties: None,
            tags: None,
        }
    }
}

