/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelSettings {
    /// The unique model identifier that this ServerlessEndpoint should provision.
    #[serde(
        rename = "modelId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub model_id: Option<Option<String>>,
}

impl ModelSettings {
    pub fn new() -> ModelSettings {
        ModelSettings { model_id: None }
    }
}
