/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// MonitorComputeType : Monitor compute type enum.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum MonitorComputeType {
    #[serde(rename = "ServerlessSpark")]
    ServerlessSpark,
}

impl Default for MonitorComputeType {
    fn default() -> Self {
        Self::ServerlessSpark
    }
}

impl std::fmt::Display for MonitorComputeType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ServerlessSpark => write!(f, "ServerlessSpark"),
        }
    }
}

impl std::str::FromStr for MonitorComputeType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "ServerlessSpark" => Ok(Self::ServerlessSpark),
            _ => Err(format!("Invalid MonitorComputeType: {}", s)),
        }
    }
}
