/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// MonitoringNotificationType : MonitoringNotificationType enum
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
pub enum MonitoringNotificationType {
    #[serde(rename = "AmlNotification")]
    #[default]
    AmlNotification,
}

impl std::fmt::Display for MonitoringNotificationType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AmlNotification => write!(f, "AmlNotification"),
        }
    }
}

impl std::str::FromStr for MonitoringNotificationType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "AmlNotification" => Ok(Self::AmlNotification),
            _ => Err(format!("Invalid MonitoringNotificationType: {}", s)),
        }
    }
}
