/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MonitoringInputDataBase : Monitoring input data base definition.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "inputDataType")]
pub enum MonitoringInputDataBase {
    #[serde(rename="FixedInputData")]
    FixedInputData {
        /// Mapping of column names to special uses.
        #[serde(rename = "columns", skip_serializing_if = "Option::is_none")]
        columns: Option<std::collections::HashMap<String, String>>,
        /// The context metadata of the data source.
        #[serde(rename = "dataContext", skip_serializing_if = "Option::is_none")]
        data_context: Option<String>,
        #[serde(rename = "jobInputType")]
        job_input_type: models::JobInputType,
        /// [Required] Input Asset URI.
        #[serde(rename = "uri")]
        uri: String,
    },
    #[serde(rename="RollingInputData")]
    RollingInputData {
        /// Mapping of column names to special uses.
        #[serde(rename = "columns", skip_serializing_if = "Option::is_none")]
        columns: Option<std::collections::HashMap<String, String>>,
        /// The context metadata of the data source.
        #[serde(rename = "dataContext", skip_serializing_if = "Option::is_none")]
        data_context: Option<String>,
        #[serde(rename = "jobInputType")]
        job_input_type: models::JobInputType,
        /// [Required] Input Asset URI.
        #[serde(rename = "uri")]
        uri: String,
    },
    #[serde(rename="StaticInputData")]
    StaticInputData {
        /// Mapping of column names to special uses.
        #[serde(rename = "columns", skip_serializing_if = "Option::is_none")]
        columns: Option<std::collections::HashMap<String, String>>,
        /// The context metadata of the data source.
        #[serde(rename = "dataContext", skip_serializing_if = "Option::is_none")]
        data_context: Option<String>,
        #[serde(rename = "jobInputType")]
        job_input_type: models::JobInputType,
        /// [Required] Input Asset URI.
        #[serde(rename = "uri")]
        uri: String,
    },
}

impl Default for MonitoringInputDataBase {
    fn default() -> Self {
        Self::FixedInputData {
            columns: Default::default(),
            data_context: Default::default(),
            job_input_type: Default::default(),
            uri: Default::default(),
        }
        
    }
}


