/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// MonitoringFeatureDataType : MonitoringFeatureDataType enum
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
pub enum MonitoringFeatureDataType {
    #[serde(rename = "Numerical")]
    #[default]
    Numerical,
    #[serde(rename = "Categorical")]
    Categorical,
}

impl std::fmt::Display for MonitoringFeatureDataType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Numerical => write!(f, "Numerical"),
            Self::Categorical => write!(f, "Categorical"),
        }
    }
}

impl std::str::FromStr for MonitoringFeatureDataType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Numerical" => Ok(Self::Numerical),
            "Categorical" => Ok(Self::Categorical),
            _ => Err(format!("Invalid MonitoringFeatureDataType: {}", s)),
        }
    }
}
