/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "filterType")]
pub enum MonitoringFeatureFilterBase {
    #[serde(rename = "AllFeatures")]
    AllFeatures {},
    #[serde(rename = "FeatureSubset")]
    FeatureSubset {},
    #[serde(rename = "TopNFeaturesByAttribution")]
    TopNFeaturesByAttribution {},
}

impl Default for MonitoringFeatureFilterBase {
    fn default() -> Self {
        Self::AllFeatures {}
    }
}
