/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MonitoringTarget : Monitoring target definition.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MonitoringTarget {
    /// Reference to the deployment asset targeted by this monitor.
    #[serde(
        rename = "deploymentId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub deployment_id: Option<Option<String>>,
    /// Reference to the model asset targeted by this monitor.
    #[serde(
        rename = "modelId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub model_id: Option<Option<String>>,
    #[serde(rename = "taskType")]
    pub task_type: models::ModelTaskType,
}

impl MonitoringTarget {
    /// Monitoring target definition.
    pub fn new(task_type: models::ModelTaskType) -> MonitoringTarget {
        MonitoringTarget {
            deployment_id: None,
            model_id: None,
            task_type,
        }
    }
}
