/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// MonitoringFeatureFilterType : MonitoringFeatureFilterType enum
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
pub enum MonitoringFeatureFilterType {
    #[serde(rename = "AllFeatures")]
    #[default]
    AllFeatures,
    #[serde(rename = "TopNByAttribution")]
    TopNByAttribution,
    #[serde(rename = "FeatureSubset")]
    FeatureSubset,
}

impl std::fmt::Display for MonitoringFeatureFilterType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AllFeatures => write!(f, "AllFeatures"),
            Self::TopNByAttribution => write!(f, "TopNByAttribution"),
            Self::FeatureSubset => write!(f, "FeatureSubset"),
        }
    }
}

impl std::str::FromStr for MonitoringFeatureFilterType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "AllFeatures" => Ok(Self::AllFeatures),
            "TopNByAttribution" => Ok(Self::TopNByAttribution),
            "FeatureSubset" => Ok(Self::FeatureSubset),
            _ => Err(format!("Invalid MonitoringFeatureFilterType: {}", s)),
        }
    }
}
