/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// MonitoringInputDataType : Monitoring input data type enum.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum MonitoringInputDataType {
    #[serde(rename = "Static")]
    Static,
    #[serde(rename = "Rolling")]
    Rolling,
    #[serde(rename = "Fixed")]
    Fixed,
}

impl Default for MonitoringInputDataType {
    fn default() -> Self {
        Self::Static
    }
}

impl std::fmt::Display for MonitoringInputDataType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Static => write!(f, "Static"),
            Self::Rolling => write!(f, "Rolling"),
            Self::Fixed => write!(f, "Fixed"),
        }
    }
}

impl std::str::FromStr for MonitoringInputDataType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Static" => Ok(Self::Static),
            "Rolling" => Ok(Self::Rolling),
            "Fixed" => Ok(Self::Fixed),
            _ => Err(format!("Invalid MonitoringInputDataType: {}", s)),
        }
    }
}
