/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MonitoringThreshold {
    /// The threshold value. If null, the set default is dependent on the metric type.
    #[serde(rename = "value", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub value: Option<Option<f64>>,
}

impl MonitoringThreshold {
    pub fn new() -> MonitoringThreshold {
        MonitoringThreshold {
            value: None,
        }
    }
}

