/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MonitorNotificationSettings {
    #[serde(rename = "emailNotificationSettings", skip_serializing_if = "Option::is_none")]
    pub email_notification_settings: Option<Box<models::MonitorEmailNotificationSettings>>,
}

impl MonitorNotificationSettings {
    pub fn new() -> MonitorNotificationSettings {
        MonitorNotificationSettings {
            email_notification_settings: None,
        }
    }
}

