/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MonitoringSignalType : MonitoringSignalType enum
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum MonitoringSignalType {
    #[serde(rename = "DataDrift")]
    DataDrift,
    #[serde(rename = "PredictionDrift")]
    PredictionDrift,
    #[serde(rename = "DataQuality")]
    DataQuality,
    #[serde(rename = "FeatureAttributionDrift")]
    FeatureAttributionDrift,
    #[serde(rename = "Custom")]
    Custom,
}

impl Default for MonitoringSignalType {
    fn default() -> Self {
        Self::DataDrift
    }
}

impl std::fmt::Display for MonitoringSignalType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DataDrift => write!(f, "DataDrift"),
            Self::PredictionDrift => write!(f, "PredictionDrift"),
            Self::DataQuality => write!(f, "DataQuality"),
            Self::FeatureAttributionDrift => write!(f, "FeatureAttributionDrift"),
            Self::Custom => write!(f, "Custom"),
        }
    }
}

impl std::str::FromStr for MonitoringSignalType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "DataDrift" => Ok(Self::DataDrift),
            "PredictionDrift" => Ok(Self::PredictionDrift),
            "DataQuality" => Ok(Self::DataQuality),
            "FeatureAttributionDrift" => Ok(Self::FeatureAttributionDrift),
            "Custom" => Ok(Self::Custom),
            _ => Err(format!("Invalid MonitoringSignalType: {}", s)),
        }
    }
}
