/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// MonitorComputeConfigurationBase : Monitor compute configuration base definition.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "computeType")]
pub enum MonitorComputeConfigurationBase {
    #[serde(rename="MonitorServerlessSparkCompute")]
    MonitorServerlessSparkCompute {
    },
}

impl Default for MonitorComputeConfigurationBase {
    fn default() -> Self {
        Self::MonitorServerlessSparkCompute {
        }
        
    }
}


