/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Mpi : MPI distribution configuration.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Mpi {
    /// Number of processes per MPI node.
    #[serde(
        rename = "processCountPerInstance",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub process_count_per_instance: Option<Option<i32>>,
    #[serde(rename = "distributionType")]
    pub distribution_type: models::DistributionType,
}

impl Mpi {
    /// MPI distribution configuration.
    pub fn new(distribution_type: models::DistributionType) -> Mpi {
        Mpi {
            process_count_per_instance: None,
            distribution_type,
        }
    }
}
