/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NCrossValidations : N-Cross validations value.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "mode")]
pub enum NCrossValidations {
    #[serde(rename="AutoNCrossValidations")]
    AutoNCrossValidations {
    },
    #[serde(rename="CustomNCrossValidations")]
    CustomNCrossValidations {
    },
}

impl Default for NCrossValidations {
    fn default() -> Self {
        Self::AutoNCrossValidations {
        }
        
    }
}


