/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// Nodes : Abstract Nodes definition
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "nodesValueType")]
pub enum Nodes {
    #[serde(rename="AllNodes")]
    AllNodes {
    },
}

impl Default for Nodes {
    fn default() -> Self {
        Self::AllNodes {
        }
        
    }
}


