/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// NoneDatastoreCredentials : Empty/none datastore credentials.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NoneDatastoreCredentials {
    #[serde(rename = "credentialsType")]
    pub credentials_type: models::CredentialsType,
}

impl NoneDatastoreCredentials {
    /// Empty/none datastore credentials.
    pub fn new(credentials_type: models::CredentialsType) -> NoneDatastoreCredentials {
        NoneDatastoreCredentials {
            credentials_type,
        }
    }
}

