/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// NumericalDataDriftMetric : NumericalDataDriftMetric enum
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum NumericalDataDriftMetric {
    #[serde(rename = "JensenShannonDistance")]
    JensenShannonDistance,
    #[serde(rename = "PopulationStabilityIndex")]
    PopulationStabilityIndex,
    #[serde(rename = "NormalizedWassersteinDistance")]
    NormalizedWassersteinDistance,
    #[serde(rename = "TwoSampleKolmogorovSmirnovTest")]
    TwoSampleKolmogorovSmirnovTest,
}

impl Default for NumericalDataDriftMetric {
    fn default() -> Self {
        Self::JensenShannonDistance
    }
}

impl std::fmt::Display for NumericalDataDriftMetric {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::JensenShannonDistance => write!(f, "JensenShannonDistance"),
            Self::PopulationStabilityIndex => write!(f, "PopulationStabilityIndex"),
            Self::NormalizedWassersteinDistance => write!(f, "NormalizedWassersteinDistance"),
            Self::TwoSampleKolmogorovSmirnovTest => write!(f, "TwoSampleKolmogorovSmirnovTest"),
        }
    }
}

impl std::str::FromStr for NumericalDataDriftMetric {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "JensenShannonDistance" => Ok(Self::JensenShannonDistance),
            "PopulationStabilityIndex" => Ok(Self::PopulationStabilityIndex),
            "NormalizedWassersteinDistance" => Ok(Self::NormalizedWassersteinDistance),
            "TwoSampleKolmogorovSmirnovTest" => Ok(Self::TwoSampleKolmogorovSmirnovTest),
            _ => Err(format!("Invalid NumericalDataDriftMetric: {}", s)),
        }
    }
}
