/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Objective : Optimization objective.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Objective {
    #[serde(rename = "goal")]
    pub goal: models::Goal,
    /// [Required] Name of the metric to optimize.
    #[serde(rename = "primaryMetric")]
    pub primary_metric: String,
}

impl Objective {
    /// Optimization objective.
    pub fn new(goal: models::Goal, primary_metric: String) -> Objective {
        Objective {
            goal,
            primary_metric,
        }
    }
}

