/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// OneLakeArtifact : OneLake artifact (data source) configuration.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "artifactType")]
pub enum OneLakeArtifact {
    #[serde(rename="LakeHouseArtifact")]
    LakeHouseArtifact {
        /// [Required] OneLake artifact name
        #[serde(rename = "artifactName")]
        artifact_name: String,
    },
}

impl Default for OneLakeArtifact {
    fn default() -> Self {
        Self::LakeHouseArtifact {
            artifact_name: Default::default(),
        }
        
    }
}


