/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// OneLakeArtifactType : Enum to determine OneLake artifact type.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
pub enum OneLakeArtifactType {
    #[serde(rename = "LakeHouse")]
    #[default]
    LakeHouse,
}

impl std::fmt::Display for OneLakeArtifactType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::LakeHouse => write!(f, "LakeHouse"),
        }
    }
}

impl std::str::FromStr for OneLakeArtifactType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "LakeHouse" => Ok(Self::LakeHouse),
            _ => Err(format!("Invalid OneLakeArtifactType: {}", s)),
        }
    }
}
