/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// OnlineRequestSettings : Online deployment scoring requests configuration.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OnlineRequestSettings {
    /// The number of maximum concurrent requests per node allowed per deployment. Defaults to 1.
    #[serde(
        rename = "maxConcurrentRequestsPerInstance",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_concurrent_requests_per_instance: Option<i32>,
    /// (Deprecated for Managed Online Endpoints) The maximum amount of time a request will stay in the queue in ISO 8601 format.  Defaults to 500ms.  (Now increase `request_timeout_ms` to account for any networking/queue delays)
    #[serde(rename = "maxQueueWait", skip_serializing_if = "Option::is_none")]
    pub max_queue_wait: Option<String>,
    /// The scoring timeout in ISO 8601 format.  Defaults to 5000ms.
    #[serde(rename = "requestTimeout", skip_serializing_if = "Option::is_none")]
    pub request_timeout: Option<String>,
}

impl OnlineRequestSettings {
    /// Online deployment scoring requests configuration.
    pub fn new() -> OnlineRequestSettings {
        OnlineRequestSettings {
            max_concurrent_requests_per_instance: None,
            max_queue_wait: None,
            request_timeout: None,
        }
    }
}
