/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OnlineEndpoint : Online endpoint configuration
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OnlineEndpoint {
    /// ARM resource ID of the compute if it exists.  optional
    #[serde(rename = "compute", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub compute: Option<Option<String>>,
    /// Percentage of traffic to be mirrored to each deployment without using returned scoring. Traffic values need to sum to utmost 50.
    #[serde(rename = "mirrorTraffic", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub mirror_traffic: Option<Option<std::collections::HashMap<String, i32>>>,
    #[serde(rename = "provisioningState", skip_serializing_if = "Option::is_none")]
    pub provisioning_state: Option<models::EndpointProvisioningState>,
    #[serde(rename = "publicNetworkAccess", skip_serializing_if = "Option::is_none")]
    pub public_network_access: Option<models::PublicNetworkAccessType>,
    /// Percentage of traffic from endpoint to divert to each deployment. Traffic values need to sum to 100.
    #[serde(rename = "traffic", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub traffic: Option<Option<std::collections::HashMap<String, i32>>>,
    #[serde(rename = "authMode")]
    pub auth_mode: models::EndpointAuthMode,
    /// Description of the inference endpoint.
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "keys", skip_serializing_if = "Option::is_none")]
    pub keys: Option<Box<models::EndpointAuthKeys>>,
    /// Property dictionary. Properties can be added, but not removed or altered.
    #[serde(rename = "properties", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Option<std::collections::HashMap<String, String>>>,
    /// Endpoint URI.
    #[serde(rename = "scoringUri", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub scoring_uri: Option<Option<String>>,
    /// Endpoint Swagger URI.
    #[serde(rename = "swaggerUri", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub swagger_uri: Option<Option<String>>,
}

impl OnlineEndpoint {
    /// Online endpoint configuration
    pub fn new(auth_mode: models::EndpointAuthMode) -> OnlineEndpoint {
        OnlineEndpoint {
            compute: None,
            mirror_traffic: None,
            provisioning_state: None,
            public_network_access: None,
            traffic: None,
            auth_mode,
            description: None,
            keys: None,
            properties: None,
            scoring_uri: None,
            swagger_uri: None,
        }
    }
}

