/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// OperatingSystemType : The type of operating system.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
pub enum OperatingSystemType {
    #[serde(rename = "Linux")]
    #[default]
    Linux,
    #[serde(rename = "Windows")]
    Windows,
}

impl std::fmt::Display for OperatingSystemType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Linux => write!(f, "Linux"),
            Self::Windows => write!(f, "Windows"),
        }
    }
}

impl std::str::FromStr for OperatingSystemType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Linux" => Ok(Self::Linux),
            "Windows" => Ok(Self::Windows),
            _ => Err(format!("Invalid OperatingSystemType: {}", s)),
        }
    }
}
