/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OutputPathAssetReference : Reference to an asset via its path in a job output.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OutputPathAssetReference {
    /// ARM resource ID of the job.
    #[serde(
        rename = "jobId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub job_id: Option<Option<String>>,
    /// The path of the file/directory in the job output.
    #[serde(
        rename = "path",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub path: Option<Option<String>>,
    #[serde(rename = "referenceType")]
    pub reference_type: models::ReferenceType,
}

impl OutputPathAssetReference {
    /// Reference to an asset via its path in a job output.
    pub fn new(reference_type: models::ReferenceType) -> OutputPathAssetReference {
        OutputPathAssetReference {
            job_id: None,
            path: None,
            reference_type,
        }
    }
}
