/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OutputDeliveryMode : Output data delivery mode enums.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum OutputDeliveryMode {
    #[serde(rename = "ReadWriteMount")]
    ReadWriteMount,
    #[serde(rename = "Upload")]
    Upload,
    #[serde(rename = "Direct")]
    Direct,
}

impl Default for OutputDeliveryMode {
    fn default() -> Self {
        Self::ReadWriteMount
    }
}

impl std::fmt::Display for OutputDeliveryMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ReadWriteMount => write!(f, "ReadWriteMount"),
            Self::Upload => write!(f, "Upload"),
            Self::Direct => write!(f, "Direct"),
        }
    }
}

impl std::str::FromStr for OutputDeliveryMode {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "ReadWriteMount" => Ok(Self::ReadWriteMount),
            "Upload" => Ok(Self::Upload),
            "Direct" => Ok(Self::Direct),
            _ => Err(format!("Invalid OutputDeliveryMode: {}", s)),
        }
    }
}
