/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PartialBatchDeploymentPartialMinimalTrackedResourceWithProperties : Strictly used in update requests.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartialBatchDeploymentPartialMinimalTrackedResourceWithProperties {
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<Box<models::PartialBatchDeployment>>,
    /// Resource tags.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<std::collections::HashMap<String, String>>,
}

impl PartialBatchDeploymentPartialMinimalTrackedResourceWithProperties {
    /// Strictly used in update requests.
    pub fn new() -> PartialBatchDeploymentPartialMinimalTrackedResourceWithProperties {
        PartialBatchDeploymentPartialMinimalTrackedResourceWithProperties {
            properties: None,
            tags: None,
        }
    }
}

