/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PartialManagedServiceIdentity : Managed service identity (system assigned and/or user assigned identities)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartialManagedServiceIdentity {
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::ManagedServiceIdentityType>,
    /// The set of user assigned identities associated with the resource. The userAssignedIdentities dictionary keys will be ARM resource ids in the form: '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{identityName}. The dictionary values can be empty objects ({}) in requests.
    #[serde(
        rename = "userAssignedIdentities",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_assigned_identities: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl PartialManagedServiceIdentity {
    /// Managed service identity (system assigned and/or user assigned identities)
    pub fn new() -> PartialManagedServiceIdentity {
        PartialManagedServiceIdentity {
            r#type: None,
            user_assigned_identities: None,
        }
    }
}
