/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PartialSku : Common SKU definition.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartialSku {
    /// If the SKU supports scale out/in then the capacity integer should be included. If scale out/in is not possible for the resource this may be omitted.
    #[serde(rename = "capacity", skip_serializing_if = "Option::is_none")]
    pub capacity: Option<i32>,
    /// If the service has different generations of hardware, for the same SKU, then that can be captured here.
    #[serde(rename = "family", skip_serializing_if = "Option::is_none")]
    pub family: Option<String>,
    /// The name of the SKU. Ex - P3. It is typically a letter+number code.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The SKU size. When the name field is the combination of tier and some other value, this would be the standalone code.
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<String>,
    #[serde(rename = "tier", skip_serializing_if = "Option::is_none")]
    pub tier: Option<models::SkuTier>,
}

impl PartialSku {
    /// Common SKU definition.
    pub fn new() -> PartialSku {
        PartialSku {
            capacity: None,
            family: None,
            name: None,
            size: None,
            tier: None,
        }
    }
}
