/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PendingUploadType : Type of storage to use for the pending upload location
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum PendingUploadType {
    #[serde(rename = "None")]
    None,
    #[serde(rename = "TemporaryBlobReference")]
    TemporaryBlobReference,
}

impl Default for PendingUploadType {
    fn default() -> Self {
        Self::None
    }
}

impl std::fmt::Display for PendingUploadType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::None => write!(f, "None"),
            Self::TemporaryBlobReference => write!(f, "TemporaryBlobReference"),
        }
    }
}

impl std::str::FromStr for PendingUploadType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "None" => Ok(Self::None),
            "TemporaryBlobReference" => Ok(Self::TemporaryBlobReference),
            _ => Err(format!("Invalid PendingUploadType: {}", s)),
        }
    }
}
