/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PendingUploadResponseDto {
    #[serde(
        rename = "blobReferenceForConsumption",
        skip_serializing_if = "Option::is_none"
    )]
    pub blob_reference_for_consumption: Option<Box<models::BlobReferenceForConsumptionDto>>,
    /// ID for this upload request
    #[serde(
        rename = "pendingUploadId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub pending_upload_id: Option<Option<String>>,
    #[serde(rename = "pendingUploadType", skip_serializing_if = "Option::is_none")]
    pub pending_upload_type: Option<models::PendingUploadType>,
}

impl PendingUploadResponseDto {
    pub fn new() -> PendingUploadResponseDto {
        PendingUploadResponseDto {
            blob_reference_for_consumption: None,
            pending_upload_id: None,
            pending_upload_type: None,
        }
    }
}
