/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ProbeSettings : Deployment container liveness/readiness probe configuration.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProbeSettings {
    /// The number of failures to allow before returning an unhealthy status.
    #[serde(rename = "failureThreshold", skip_serializing_if = "Option::is_none")]
    pub failure_threshold: Option<i32>,
    /// The delay before the first probe in ISO 8601 format.
    #[serde(
        rename = "initialDelay",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub initial_delay: Option<Option<String>>,
    /// The length of time between probes in ISO 8601 format.
    #[serde(rename = "period", skip_serializing_if = "Option::is_none")]
    pub period: Option<String>,
    /// The number of successful probes before returning a healthy status.
    #[serde(rename = "successThreshold", skip_serializing_if = "Option::is_none")]
    pub success_threshold: Option<i32>,
    /// The probe timeout in ISO 8601 format.
    #[serde(rename = "timeout", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<String>,
}

impl ProbeSettings {
    /// Deployment container liveness/readiness probe configuration.
    pub fn new() -> ProbeSettings {
        ProbeSettings {
            failure_threshold: None,
            initial_delay: None,
            period: None,
            success_threshold: None,
            timeout: None,
        }
    }
}
