/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueueSettings {
    #[serde(rename = "jobTier", skip_serializing_if = "Option::is_none")]
    pub job_tier: Option<models::JobTier>,
}

impl QueueSettings {
    pub fn new() -> QueueSettings {
        QueueSettings {
            job_tier: None,
        }
    }
}

