/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RandomSamplingAlgorithm : Defines a Sampling Algorithm that generates values randomly
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RandomSamplingAlgorithm {
    #[serde(rename = "rule", skip_serializing_if = "Option::is_none")]
    pub rule: Option<models::RandomSamplingAlgorithmRule>,
    /// An optional integer to use as the seed for random number generation
    #[serde(
        rename = "seed",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub seed: Option<Option<i32>>,
    #[serde(rename = "samplingAlgorithmType")]
    pub sampling_algorithm_type: models::SamplingAlgorithmType,
}

impl RandomSamplingAlgorithm {
    /// Defines a Sampling Algorithm that generates values randomly
    pub fn new(sampling_algorithm_type: models::SamplingAlgorithmType) -> RandomSamplingAlgorithm {
        RandomSamplingAlgorithm {
            rule: None,
            seed: None,
            sampling_algorithm_type,
        }
    }
}
