/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecurrenceTrigger {
    #[serde(rename = "frequency")]
    pub frequency: models::RecurrenceFrequency,
    /// [Required] Specifies schedule interval in conjunction with frequency
    #[serde(rename = "interval")]
    pub interval: i32,
    #[serde(rename = "schedule", skip_serializing_if = "Option::is_none")]
    pub schedule: Option<Box<models::RecurrenceSchedule>>,
    /// Specifies end time of schedule in ISO 8601, but without a UTC offset. Refer https://en.wikipedia.org/wiki/ISO_8601.  Recommented format would be \"2022-06-01T00:00:01\"  If not present, the schedule will run indefinitely
    #[serde(
        rename = "endTime",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub end_time: Option<Option<String>>,
    /// Specifies start time of schedule in ISO 8601 format, but without a UTC offset.
    #[serde(
        rename = "startTime",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub start_time: Option<Option<String>>,
    /// Specifies time zone in which the schedule runs.  TimeZone should follow Windows time zone format. Refer: https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/default-time-zones?view=windows-11
    #[serde(rename = "timeZone", skip_serializing_if = "Option::is_none")]
    pub time_zone: Option<String>,
    #[serde(rename = "triggerType")]
    pub trigger_type: models::TriggerType,
}

impl RecurrenceTrigger {
    pub fn new(
        frequency: models::RecurrenceFrequency,
        interval: i32,
        trigger_type: models::TriggerType,
    ) -> RecurrenceTrigger {
        RecurrenceTrigger {
            frequency,
            interval,
            schedule: None,
            end_time: None,
            start_time: None,
            time_zone: None,
            trigger_type,
        }
    }
}
