/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// RecurrenceFrequency : Enum to describe the frequency of a recurrence schedule
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
pub enum RecurrenceFrequency {
    #[serde(rename = "Minute")]
    #[default]
    Minute,
    #[serde(rename = "Hour")]
    Hour,
    #[serde(rename = "Day")]
    Day,
    #[serde(rename = "Week")]
    Week,
    #[serde(rename = "Month")]
    Month,
}

impl std::fmt::Display for RecurrenceFrequency {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Minute => write!(f, "Minute"),
            Self::Hour => write!(f, "Hour"),
            Self::Day => write!(f, "Day"),
            Self::Week => write!(f, "Week"),
            Self::Month => write!(f, "Month"),
        }
    }
}

impl std::str::FromStr for RecurrenceFrequency {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Minute" => Ok(Self::Minute),
            "Hour" => Ok(Self::Hour),
            "Day" => Ok(Self::Day),
            "Week" => Ok(Self::Week),
            "Month" => Ok(Self::Month),
            _ => Err(format!("Invalid RecurrenceFrequency: {}", s)),
        }
    }
}
