/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ReferenceType : Enum to determine which reference method to use for an asset.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
pub enum ReferenceType {
    #[serde(rename = "Id")]
    #[default]
    Id,
    #[serde(rename = "DataPath")]
    DataPath,
    #[serde(rename = "OutputPath")]
    OutputPath,
}

impl std::fmt::Display for ReferenceType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Id => write!(f, "Id"),
            Self::DataPath => write!(f, "DataPath"),
            Self::OutputPath => write!(f, "OutputPath"),
        }
    }
}

impl std::str::FromStr for ReferenceType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Id" => Ok(Self::Id),
            "DataPath" => Ok(Self::DataPath),
            "OutputPath" => Ok(Self::OutputPath),
            _ => Err(format!("Invalid ReferenceType: {}", s)),
        }
    }
}
