/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// RegressionPrimaryMetrics : Primary metrics for Regression task.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
pub enum RegressionPrimaryMetrics {
    #[serde(rename = "SpearmanCorrelation")]
    #[default]
    SpearmanCorrelation,
    #[serde(rename = "NormalizedRootMeanSquaredError")]
    NormalizedRootMeanSquaredError,
    #[serde(rename = "R2Score")]
    R2Score,
    #[serde(rename = "NormalizedMeanAbsoluteError")]
    NormalizedMeanAbsoluteError,
}

impl std::fmt::Display for RegressionPrimaryMetrics {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::SpearmanCorrelation => write!(f, "SpearmanCorrelation"),
            Self::NormalizedRootMeanSquaredError => write!(f, "NormalizedRootMeanSquaredError"),
            Self::R2Score => write!(f, "R2Score"),
            Self::NormalizedMeanAbsoluteError => write!(f, "NormalizedMeanAbsoluteError"),
        }
    }
}

impl std::str::FromStr for RegressionPrimaryMetrics {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "SpearmanCorrelation" => Ok(Self::SpearmanCorrelation),
            "NormalizedRootMeanSquaredError" => Ok(Self::NormalizedRootMeanSquaredError),
            "R2Score" => Ok(Self::R2Score),
            "NormalizedMeanAbsoluteError" => Ok(Self::NormalizedMeanAbsoluteError),
            _ => Err(format!("Invalid RegressionPrimaryMetrics: {}", s)),
        }
    }
}
