/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RegressionTrainingSettings : Regression Training related configuration.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegressionTrainingSettings {
    /// Allowed models for regression task.
    #[serde(rename = "allowedTrainingAlgorithms", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub allowed_training_algorithms: Option<Option<Vec<models::RegressionModels>>>,
    /// Blocked models for regression task.
    #[serde(rename = "blockedTrainingAlgorithms", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub blocked_training_algorithms: Option<Option<Vec<models::RegressionModels>>>,
    /// Enable recommendation of DNN models.
    #[serde(rename = "enableDnnTraining", skip_serializing_if = "Option::is_none")]
    pub enable_dnn_training: Option<bool>,
    /// Flag to turn on explainability on best model.
    #[serde(rename = "enableModelExplainability", skip_serializing_if = "Option::is_none")]
    pub enable_model_explainability: Option<bool>,
    /// Flag for enabling onnx compatible models.
    #[serde(rename = "enableOnnxCompatibleModels", skip_serializing_if = "Option::is_none")]
    pub enable_onnx_compatible_models: Option<bool>,
    /// Enable stack ensemble run.
    #[serde(rename = "enableStackEnsemble", skip_serializing_if = "Option::is_none")]
    pub enable_stack_ensemble: Option<bool>,
    /// Enable voting ensemble run.
    #[serde(rename = "enableVoteEnsemble", skip_serializing_if = "Option::is_none")]
    pub enable_vote_ensemble: Option<bool>,
    /// During VotingEnsemble and StackEnsemble model generation, multiple fitted models from the previous child runs are downloaded.  Configure this parameter with a higher value than 300 secs, if more time is needed.
    #[serde(rename = "ensembleModelDownloadTimeout", skip_serializing_if = "Option::is_none")]
    pub ensemble_model_download_timeout: Option<String>,
    #[serde(rename = "stackEnsembleSettings", skip_serializing_if = "Option::is_none")]
    pub stack_ensemble_settings: Option<Box<models::StackEnsembleSettings>>,
}

impl RegressionTrainingSettings {
    /// Regression Training related configuration.
    pub fn new() -> RegressionTrainingSettings {
        RegressionTrainingSettings {
            allowed_training_algorithms: None,
            blocked_training_algorithms: None,
            enable_dnn_training: None,
            enable_model_explainability: None,
            enable_onnx_compatible_models: None,
            enable_stack_ensemble: None,
            enable_vote_ensemble: None,
            ensemble_model_download_timeout: None,
            stack_ensemble_settings: None,
        }
    }
}

