/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RollingRateType : RollingRateType enum
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum RollingRateType {
    #[serde(rename = "Year")]
    Year,
    #[serde(rename = "Month")]
    Month,
    #[serde(rename = "Day")]
    Day,
    #[serde(rename = "Hour")]
    Hour,
    #[serde(rename = "Minute")]
    Minute,
}

impl Default for RollingRateType {
    fn default() -> Self {
        Self::Year
    }
}

impl std::fmt::Display for RollingRateType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Year => write!(f, "Year"),
            Self::Month => write!(f, "Month"),
            Self::Day => write!(f, "Day"),
            Self::Hour => write!(f, "Hour"),
            Self::Minute => write!(f, "Minute"),
        }
    }
}

impl std::str::FromStr for RollingRateType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Year" => Ok(Self::Year),
            "Month" => Ok(Self::Month),
            "Day" => Ok(Self::Day),
            "Hour" => Ok(Self::Hour),
            "Minute" => Ok(Self::Minute),
            _ => Err(format!("Invalid RollingRateType: {}", s)),
        }
    }
}
