/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RollingInputData : Rolling input data definition.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RollingInputData {
    /// Reference to the component asset used to preprocess the data.
    #[serde(rename = "preprocessingComponentId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub preprocessing_component_id: Option<Option<String>>,
    /// [Required] The time offset between the end of the data window and the monitor's current run time.
    #[serde(rename = "windowOffset")]
    pub window_offset: String,
    /// [Required] The size of the rolling data window.
    #[serde(rename = "windowSize")]
    pub window_size: String,
    /// Mapping of column names to special uses.
    #[serde(rename = "columns", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub columns: Option<Option<std::collections::HashMap<String, String>>>,
    /// The context metadata of the data source.
    #[serde(rename = "dataContext", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub data_context: Option<Option<String>>,
    #[serde(rename = "inputDataType")]
    pub input_data_type: models::MonitoringInputDataType,
    #[serde(rename = "jobInputType")]
    pub job_input_type: models::JobInputType,
    /// [Required] Input Asset URI.
    #[serde(rename = "uri")]
    pub uri: String,
}

impl RollingInputData {
    /// Rolling input data definition.
    pub fn new(window_offset: String, window_size: String, input_data_type: models::MonitoringInputDataType, job_input_type: models::JobInputType, uri: String) -> RollingInputData {
        RollingInputData {
            preprocessing_component_id: None,
            window_offset,
            window_size,
            columns: None,
            data_context: None,
            input_data_type,
            job_input_type,
            uri,
        }
    }
}

