/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Route {
    /// [Required] The path for the route.
    #[serde(rename = "path")]
    pub path: String,
    /// [Required] The port for the route.
    #[serde(rename = "port")]
    pub port: i32,
}

impl Route {
    pub fn new(path: String, port: i32) -> Route {
        Route { path, port }
    }
}
