/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SamplingAlgorithmType : SamplingAlgorithmType enum
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum SamplingAlgorithmType {
    #[serde(rename = "Grid")]
    Grid,
    #[serde(rename = "Random")]
    Random,
    #[serde(rename = "Bayesian")]
    Bayesian,
}

impl Default for SamplingAlgorithmType {
    fn default() -> Self {
        Self::Grid
    }
}

impl std::fmt::Display for SamplingAlgorithmType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Grid => write!(f, "Grid"),
            Self::Random => write!(f, "Random"),
            Self::Bayesian => write!(f, "Bayesian"),
        }
    }
}

impl std::str::FromStr for SamplingAlgorithmType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Grid" => Ok(Self::Grid),
            "Random" => Ok(Self::Random),
            "Bayesian" => Ok(Self::Bayesian),
            _ => Err(format!("Invalid SamplingAlgorithmType: {}", s)),
        }
    }
}
