/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SasCredentialDto {
    /// Full SAS Uri, including the storage, container/blob path and SAS token
    #[serde(
        rename = "sasUri",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sas_uri: Option<Option<String>>,
    #[serde(rename = "credentialType")]
    pub credential_type: models::PendingUploadCredentialType,
}

impl SasCredentialDto {
    pub fn new(credential_type: models::PendingUploadCredentialType) -> SasCredentialDto {
        SasCredentialDto {
            sas_uri: None,
            credential_type,
        }
    }
}
