/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SasDatastoreCredentials : SAS datastore credentials configuration.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SasDatastoreCredentials {
    #[serde(rename = "secrets")]
    pub secrets: Box<models::SasDatastoreSecrets>,
    #[serde(rename = "credentialsType")]
    pub credentials_type: models::CredentialsType,
}

impl SasDatastoreCredentials {
    /// SAS datastore credentials configuration.
    pub fn new(secrets: models::SasDatastoreSecrets, credentials_type: models::CredentialsType) -> SasDatastoreCredentials {
        SasDatastoreCredentials {
            secrets: Box::new(secrets),
            credentials_type,
        }
    }
}

