/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ScaleType : ScaleType enum
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum ScaleType {
    #[serde(rename = "Default")]
    Default,
    #[serde(rename = "TargetUtilization")]
    TargetUtilization,
}

impl Default for ScaleType {
    fn default() -> Self {
        Self::Default
    }
}

impl std::fmt::Display for ScaleType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Default => write!(f, "Default"),
            Self::TargetUtilization => write!(f, "TargetUtilization"),
        }
    }
}

impl std::str::FromStr for ScaleType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Default" => Ok(Self::Default),
            "TargetUtilization" => Ok(Self::TargetUtilization),
            _ => Err(format!("Invalid ScaleType: {}", s)),
        }
    }
}
