/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "actionType")]
pub enum ScheduleActionBase {
    #[serde(rename="CreateMonitorAction")]
    CreateMonitorAction {
    },
    #[serde(rename="EndpointScheduleAction")]
    EndpointScheduleAction {
    },
    #[serde(rename="JobScheduleAction")]
    JobScheduleAction {
    },
}

impl Default for ScheduleActionBase {
    fn default() -> Self {
        Self::CreateMonitorAction {
        }
        
    }
}


