/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Schedule : Base definition of a schedule
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Schedule {
    #[serde(rename = "action")]
    pub action: Box<models::ScheduleActionBase>,
    /// Display name of schedule.
    #[serde(
        rename = "displayName",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub display_name: Option<Option<String>>,
    /// Is the schedule enabled?
    #[serde(rename = "isEnabled", skip_serializing_if = "Option::is_none")]
    pub is_enabled: Option<bool>,
    #[serde(rename = "provisioningState", skip_serializing_if = "Option::is_none")]
    pub provisioning_state: Option<models::ScheduleProvisioningStatus>,
    #[serde(rename = "trigger")]
    pub trigger: Box<models::TriggerBase>,
    /// The asset description text.
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    /// The asset property dictionary.
    #[serde(
        rename = "properties",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub properties: Option<Option<std::collections::HashMap<String, String>>>,
    /// Tag dictionary. Tags can be added, removed, and updated.
    #[serde(
        rename = "tags",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tags: Option<Option<std::collections::HashMap<String, String>>>,
}

impl Schedule {
    /// Base definition of a schedule
    pub fn new(action: models::ScheduleActionBase, trigger: models::TriggerBase) -> Schedule {
        Schedule {
            action: Box::new(action),
            display_name: None,
            is_enabled: None,
            provisioning_state: None,
            trigger: Box::new(trigger),
            description: None,
            properties: None,
            tags: None,
        }
    }
}
