/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ScheduleProvisioningStatus : ScheduleProvisioningStatus enum
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum ScheduleProvisioningStatus {
    #[serde(rename = "Creating")]
    Creating,
    #[serde(rename = "Updating")]
    Updating,
    #[serde(rename = "Deleting")]
    Deleting,
    #[serde(rename = "Succeeded")]
    Succeeded,
    #[serde(rename = "Failed")]
    Failed,
    #[serde(rename = "Canceled")]
    Canceled,
}

impl Default for ScheduleProvisioningStatus {
    fn default() -> Self {
        Self::Creating
    }
}

impl std::fmt::Display for ScheduleProvisioningStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Creating => write!(f, "Creating"),
            Self::Updating => write!(f, "Updating"),
            Self::Deleting => write!(f, "Deleting"),
            Self::Succeeded => write!(f, "Succeeded"),
            Self::Failed => write!(f, "Failed"),
            Self::Canceled => write!(f, "Canceled"),
        }
    }
}

impl std::str::FromStr for ScheduleProvisioningStatus {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Creating" => Ok(Self::Creating),
            "Updating" => Ok(Self::Updating),
            "Deleting" => Ok(Self::Deleting),
            "Succeeded" => Ok(Self::Succeeded),
            "Failed" => Ok(Self::Failed),
            "Canceled" => Ok(Self::Canceled),
            _ => Err(format!("Invalid ScheduleProvisioningStatus: {}", s)),
        }
    }
}
