/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ScheduleListViewType : ScheduleListViewType enum
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum ScheduleListViewType {
    #[serde(rename = "EnabledOnly")]
    EnabledOnly,
    #[serde(rename = "DisabledOnly")]
    DisabledOnly,
    #[serde(rename = "All")]
    All,
}

impl Default for ScheduleListViewType {
    fn default() -> Self {
        Self::EnabledOnly
    }
}

impl std::fmt::Display for ScheduleListViewType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::EnabledOnly => write!(f, "EnabledOnly"),
            Self::DisabledOnly => write!(f, "DisabledOnly"),
            Self::All => write!(f, "All"),
        }
    }
}

impl std::str::FromStr for ScheduleListViewType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "EnabledOnly" => Ok(Self::EnabledOnly),
            "DisabledOnly" => Ok(Self::DisabledOnly),
            "All" => Ok(Self::All),
            _ => Err(format!("Invalid ScheduleListViewType: {}", s)),
        }
    }
}
