/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ScheduleActionType : ScheduleActionType enum
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
pub enum ScheduleActionType {
    #[serde(rename = "CreateJob")]
    #[default]
    CreateJob,
    #[serde(rename = "InvokeBatchEndpoint")]
    InvokeBatchEndpoint,
    #[serde(rename = "CreateMonitor")]
    CreateMonitor,
}

impl std::fmt::Display for ScheduleActionType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::CreateJob => write!(f, "CreateJob"),
            Self::InvokeBatchEndpoint => write!(f, "InvokeBatchEndpoint"),
            Self::CreateMonitor => write!(f, "CreateMonitor"),
        }
    }
}

impl std::str::FromStr for ScheduleActionType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "CreateJob" => Ok(Self::CreateJob),
            "InvokeBatchEndpoint" => Ok(Self::InvokeBatchEndpoint),
            "CreateMonitor" => Ok(Self::CreateMonitor),
            _ => Err(format!("Invalid ScheduleActionType: {}", s)),
        }
    }
}
