/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// Seasonality : Forecasting seasonality.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "mode")]
pub enum Seasonality {
    #[serde(rename = "AutoSeasonality")]
    AutoSeasonality {},
    #[serde(rename = "CustomSeasonality")]
    CustomSeasonality {},
}

impl Default for Seasonality {
    fn default() -> Self {
        Self::AutoSeasonality {}
    }
}
