/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// SecretsType : Enum to determine the datastore secrets type.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum SecretsType {
    #[serde(rename = "AccountKey")]
    AccountKey,
    #[serde(rename = "Certificate")]
    Certificate,
    #[serde(rename = "Sas")]
    Sas,
    #[serde(rename = "ServicePrincipal")]
    ServicePrincipal,
}

impl Default for SecretsType {
    fn default() -> Self {
        Self::AccountKey
    }
}

impl std::fmt::Display for SecretsType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AccountKey => write!(f, "AccountKey"),
            Self::Certificate => write!(f, "Certificate"),
            Self::Sas => write!(f, "Sas"),
            Self::ServicePrincipal => write!(f, "ServicePrincipal"),
        }
    }
}

impl std::str::FromStr for SecretsType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "AccountKey" => Ok(Self::AccountKey),
            "Certificate" => Ok(Self::Certificate),
            "Sas" => Ok(Self::Sas),
            "ServicePrincipal" => Ok(Self::ServicePrincipal),
            _ => Err(format!("Invalid SecretsType: {}", s)),
        }
    }
}
