/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ServicePrincipalDatastoreCredentials : Service Principal datastore credentials configuration.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServicePrincipalDatastoreCredentials {
    /// Authority URL used for authentication.
    #[serde(
        rename = "authorityUrl",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub authority_url: Option<Option<String>>,
    /// [Required] Service principal client ID.
    #[serde(rename = "clientId")]
    pub client_id: uuid::Uuid,
    /// Resource the service principal has access to.
    #[serde(
        rename = "resourceUrl",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub resource_url: Option<Option<String>>,
    #[serde(rename = "secrets")]
    pub secrets: Box<models::ServicePrincipalDatastoreSecrets>,
    /// [Required] ID of the tenant to which the service principal belongs.
    #[serde(rename = "tenantId")]
    pub tenant_id: uuid::Uuid,
    #[serde(rename = "credentialsType")]
    pub credentials_type: models::CredentialsType,
}

impl ServicePrincipalDatastoreCredentials {
    /// Service Principal datastore credentials configuration.
    pub fn new(
        client_id: uuid::Uuid,
        secrets: models::ServicePrincipalDatastoreSecrets,
        tenant_id: uuid::Uuid,
        credentials_type: models::CredentialsType,
    ) -> ServicePrincipalDatastoreCredentials {
        ServicePrincipalDatastoreCredentials {
            authority_url: None,
            client_id,
            resource_url: None,
            secrets: Box::new(secrets),
            tenant_id,
            credentials_type,
        }
    }
}
