/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ServerlessEndpointState : State of the Serverless Endpoint.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum ServerlessEndpointState {
    #[serde(rename = "Unknown")]
    Unknown,
    #[serde(rename = "Creating")]
    Creating,
    #[serde(rename = "Deleting")]
    Deleting,
    #[serde(rename = "Suspending")]
    Suspending,
    #[serde(rename = "Reinstating")]
    Reinstating,
    #[serde(rename = "Online")]
    Online,
    #[serde(rename = "Suspended")]
    Suspended,
    #[serde(rename = "CreationFailed")]
    CreationFailed,
    #[serde(rename = "DeletionFailed")]
    DeletionFailed,
}

impl Default for ServerlessEndpointState {
    fn default() -> Self {
        Self::Unknown
    }
}

impl std::fmt::Display for ServerlessEndpointState {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Unknown => write!(f, "Unknown"),
            Self::Creating => write!(f, "Creating"),
            Self::Deleting => write!(f, "Deleting"),
            Self::Suspending => write!(f, "Suspending"),
            Self::Reinstating => write!(f, "Reinstating"),
            Self::Online => write!(f, "Online"),
            Self::Suspended => write!(f, "Suspended"),
            Self::CreationFailed => write!(f, "CreationFailed"),
            Self::DeletionFailed => write!(f, "DeletionFailed"),
        }
    }
}

impl std::str::FromStr for ServerlessEndpointState {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Unknown" => Ok(Self::Unknown),
            "Creating" => Ok(Self::Creating),
            "Deleting" => Ok(Self::Deleting),
            "Suspending" => Ok(Self::Suspending),
            "Reinstating" => Ok(Self::Reinstating),
            "Online" => Ok(Self::Online),
            "Suspended" => Ok(Self::Suspended),
            "CreationFailed" => Ok(Self::CreationFailed),
            "DeletionFailed" => Ok(Self::DeletionFailed),
            _ => Err(format!("Invalid ServerlessEndpointState: {}", s)),
        }
    }
}
