/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerlessEndpoint {
    #[serde(rename = "authMode")]
    pub auth_mode: models::ServerlessInferenceEndpointAuthMode,
    #[serde(rename = "contentSafety", skip_serializing_if = "Option::is_none")]
    pub content_safety: Option<Box<models::ContentSafety>>,
    #[serde(rename = "endpointState", skip_serializing_if = "Option::is_none")]
    pub endpoint_state: Option<models::ServerlessEndpointState>,
    #[serde(rename = "inferenceEndpoint", skip_serializing_if = "Option::is_none")]
    pub inference_endpoint: Option<Box<models::ServerlessInferenceEndpoint>>,
    /// The MarketplaceSubscription Azure ID associated to this ServerlessEndpoint.
    #[serde(rename = "marketplaceSubscriptionId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub marketplace_subscription_id: Option<Option<String>>,
    #[serde(rename = "modelSettings", skip_serializing_if = "Option::is_none")]
    pub model_settings: Option<Box<models::ModelSettings>>,
    #[serde(rename = "provisioningState", skip_serializing_if = "Option::is_none")]
    pub provisioning_state: Option<models::EndpointProvisioningState>,
}

impl ServerlessEndpoint {
    pub fn new(auth_mode: models::ServerlessInferenceEndpointAuthMode) -> ServerlessEndpoint {
        ServerlessEndpoint {
            auth_mode,
            content_safety: None,
            endpoint_state: None,
            inference_endpoint: None,
            marketplace_subscription_id: None,
            model_settings: None,
            provisioning_state: None,
        }
    }
}

