/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ServiceDataAccessAuthIdentity : ServiceDataAccessAuthIdentity enum
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum ServiceDataAccessAuthIdentity {
    #[serde(rename = "None")]
    None,
    #[serde(rename = "WorkspaceSystemAssignedIdentity")]
    WorkspaceSystemAssignedIdentity,
    #[serde(rename = "WorkspaceUserAssignedIdentity")]
    WorkspaceUserAssignedIdentity,
}

impl Default for ServiceDataAccessAuthIdentity {
    fn default() -> Self {
        Self::None
    }
}

impl std::fmt::Display for ServiceDataAccessAuthIdentity {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::None => write!(f, "None"),
            Self::WorkspaceSystemAssignedIdentity => write!(f, "WorkspaceSystemAssignedIdentity"),
            Self::WorkspaceUserAssignedIdentity => write!(f, "WorkspaceUserAssignedIdentity"),
        }
    }
}

impl std::str::FromStr for ServiceDataAccessAuthIdentity {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "None" => Ok(Self::None),
            "WorkspaceSystemAssignedIdentity" => Ok(Self::WorkspaceSystemAssignedIdentity),
            "WorkspaceUserAssignedIdentity" => Ok(Self::WorkspaceUserAssignedIdentity),
            _ => Err(format!("Invalid ServiceDataAccessAuthIdentity: {}", s)),
        }
    }
}
