/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ServicePrincipalDatastoreSecrets : Datastore Service Principal secrets.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServicePrincipalDatastoreSecrets {
    /// Service principal secret.
    #[serde(rename = "clientSecret", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub client_secret: Option<Option<String>>,
    #[serde(rename = "secretsType")]
    pub secrets_type: models::SecretsType,
}

impl ServicePrincipalDatastoreSecrets {
    /// Datastore Service Principal secrets.
    pub fn new(secrets_type: models::SecretsType) -> ServicePrincipalDatastoreSecrets {
        ServicePrincipalDatastoreSecrets {
            client_secret: None,
            secrets_type,
        }
    }
}

