/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerlessInferenceEndpoint {
    /// Specifies any required headers to target this serverless endpoint.
    #[serde(rename = "headers", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub headers: Option<Option<std::collections::HashMap<String, String>>>,
    /// [Required] The inference uri to target when making requests against the Serverless Endpoint.
    #[serde(rename = "uri")]
    pub uri: String,
}

impl ServerlessInferenceEndpoint {
    pub fn new(uri: String) -> ServerlessInferenceEndpoint {
        ServerlessInferenceEndpoint {
            headers: None,
            uri,
        }
    }
}

