/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SkuSetting : SkuSetting fulfills the need for stripped down SKU info in ARM contract.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SkuSetting {
    /// [Required] The name of the SKU. Ex - P3. It is typically a letter+number code.
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "tier", skip_serializing_if = "Option::is_none")]
    pub tier: Option<models::SkuTier>,
}

impl SkuSetting {
    /// SkuSetting fulfills the need for stripped down SKU info in ARM contract.
    pub fn new(name: String) -> SkuSetting {
        SkuSetting { name, tier: None }
    }
}
