/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// SkuTier : This field is required to be implemented by the Resource Provider if the service has more than one tier, but is not required on a PUT.
/// This field is required to be implemented by the Resource Provider if the service has more than one tier, but is not required on a PUT.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default)]
pub enum SkuTier {
    #[serde(rename = "Free")]
    #[default]
    Free,
    #[serde(rename = "Basic")]
    Basic,
    #[serde(rename = "Standard")]
    Standard,
    #[serde(rename = "Premium")]
    Premium,
}

impl std::fmt::Display for SkuTier {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Free => write!(f, "Free"),
            Self::Basic => write!(f, "Basic"),
            Self::Standard => write!(f, "Standard"),
            Self::Premium => write!(f, "Premium"),
        }
    }
}
