/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// SparkJobEntryType : SparkJobEntryType enum
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
pub enum SparkJobEntryType {
    #[serde(rename = "SparkJobPythonEntry")]
    #[default]
    SparkJobPythonEntry,
    #[serde(rename = "SparkJobScalaEntry")]
    SparkJobScalaEntry,
}

impl std::fmt::Display for SparkJobEntryType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::SparkJobPythonEntry => write!(f, "SparkJobPythonEntry"),
            Self::SparkJobScalaEntry => write!(f, "SparkJobScalaEntry"),
        }
    }
}

impl std::str::FromStr for SparkJobEntryType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "SparkJobPythonEntry" => Ok(Self::SparkJobPythonEntry),
            "SparkJobScalaEntry" => Ok(Self::SparkJobScalaEntry),
            _ => Err(format!("Invalid SparkJobEntryType: {}", s)),
        }
    }
}
