/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SparkJobEntry : Spark job entry point definition.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "sparkJobEntryType")]
pub enum SparkJobEntry {
    #[serde(rename="SparkJobPythonEntry")]
    SparkJobPythonEntry {
    },
    #[serde(rename="SparkJobScalaEntry")]
    SparkJobScalaEntry {
    },
}

impl Default for SparkJobEntry {
    fn default() -> Self {
        Self::SparkJobPythonEntry {
        }
        
    }
}


