/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SparkResourceConfiguration {
    /// Optional type of VM used as supported by the compute target.
    #[serde(rename = "instanceType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub instance_type: Option<Option<String>>,
    /// Version of spark runtime used for the job.
    #[serde(rename = "runtimeVersion", skip_serializing_if = "Option::is_none")]
    pub runtime_version: Option<String>,
}

impl SparkResourceConfiguration {
    pub fn new() -> SparkResourceConfiguration {
        SparkResourceConfiguration {
            instance_type: None,
            runtime_version: None,
        }
    }
}

