/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SparkJob : Spark job definition.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SparkJob {
    /// Archive files used in the job.
    #[serde(
        rename = "archives",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub archives: Option<Option<Vec<String>>>,
    /// Arguments for the job.
    #[serde(
        rename = "args",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub args: Option<Option<String>>,
    /// [Required] arm-id of the code asset.
    #[serde(rename = "codeId")]
    pub code_id: String,
    /// Spark configured properties.
    #[serde(
        rename = "conf",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub conf: Option<Option<std::collections::HashMap<String, String>>>,
    #[serde(rename = "entry")]
    pub entry: Box<models::SparkJobEntry>,
    /// The ARM resource ID of the Environment specification for the job.
    #[serde(
        rename = "environmentId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub environment_id: Option<Option<String>>,
    /// Environment variables included in the job.
    #[serde(
        rename = "environmentVariables",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub environment_variables: Option<Option<std::collections::HashMap<String, String>>>,
    /// Files used in the job.
    #[serde(
        rename = "files",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub files: Option<Option<Vec<String>>>,
    /// Mapping of input data bindings used in the job.
    #[serde(
        rename = "inputs",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub inputs: Option<Option<std::collections::HashMap<String, models::JobInput>>>,
    /// Jar files used in the job.
    #[serde(
        rename = "jars",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub jars: Option<Option<Vec<String>>>,
    /// Mapping of output data bindings used in the job.
    #[serde(
        rename = "outputs",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub outputs: Option<Option<std::collections::HashMap<String, models::JobOutput>>>,
    /// Python files used in the job.
    #[serde(
        rename = "pyFiles",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub py_files: Option<Option<Vec<String>>>,
    #[serde(rename = "queueSettings", skip_serializing_if = "Option::is_none")]
    pub queue_settings: Option<Box<models::QueueSettings>>,
    #[serde(rename = "resources", skip_serializing_if = "Option::is_none")]
    pub resources: Option<Box<models::SparkResourceConfiguration>>,
    /// ARM resource ID of the component resource.
    #[serde(
        rename = "componentId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub component_id: Option<Option<String>>,
    /// ARM resource ID of the compute resource.
    #[serde(
        rename = "computeId",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub compute_id: Option<Option<String>>,
    /// Display name of job.
    #[serde(
        rename = "displayName",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub display_name: Option<Option<String>>,
    /// The name of the experiment the job belongs to. If not set, the job is placed in the \"Default\" experiment.
    #[serde(rename = "experimentName", skip_serializing_if = "Option::is_none")]
    pub experiment_name: Option<String>,
    #[serde(rename = "identity", skip_serializing_if = "Option::is_none")]
    pub identity: Option<Box<models::IdentityConfiguration>>,
    /// Is the asset archived?
    #[serde(rename = "isArchived", skip_serializing_if = "Option::is_none")]
    pub is_archived: Option<bool>,
    #[serde(rename = "jobType")]
    pub job_type: models::JobType,
    #[serde(
        rename = "notificationSetting",
        skip_serializing_if = "Option::is_none"
    )]
    pub notification_setting: Option<Box<models::NotificationSetting>>,
    /// List of JobEndpoints.  For local jobs, a job endpoint will have an endpoint value of FileStreamObject.
    #[serde(
        rename = "services",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub services: Option<Option<std::collections::HashMap<String, models::JobService>>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::JobStatus>,
    /// The asset description text.
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    /// The asset property dictionary.
    #[serde(
        rename = "properties",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub properties: Option<Option<std::collections::HashMap<String, String>>>,
    /// Tag dictionary. Tags can be added, removed, and updated.
    #[serde(
        rename = "tags",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub tags: Option<Option<std::collections::HashMap<String, String>>>,
}

impl SparkJob {
    /// Spark job definition.
    pub fn new(
        code_id: String,
        entry: models::SparkJobEntry,
        job_type: models::JobType,
    ) -> SparkJob {
        SparkJob {
            archives: None,
            args: None,
            code_id,
            conf: None,
            entry: Box::new(entry),
            environment_id: None,
            environment_variables: None,
            files: None,
            inputs: None,
            jars: None,
            outputs: None,
            py_files: None,
            queue_settings: None,
            resources: None,
            component_id: None,
            compute_id: None,
            display_name: None,
            experiment_name: None,
            identity: None,
            is_archived: None,
            job_type,
            notification_setting: None,
            services: None,
            status: None,
            description: None,
            properties: None,
            tags: None,
        }
    }
}
