/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SparkJobScalaEntry {
    /// [Required] Scala class name used as entry point.
    #[serde(rename = "className")]
    pub class_name: String,
    #[serde(rename = "sparkJobEntryType")]
    pub spark_job_entry_type: models::SparkJobEntryType,
}

impl SparkJobScalaEntry {
    pub fn new(class_name: String, spark_job_entry_type: models::SparkJobEntryType) -> SparkJobScalaEntry {
        SparkJobScalaEntry {
            class_name,
            spark_job_entry_type,
        }
    }
}

