/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SparkJobPythonEntry {
    /// [Required] Relative python file path for job entry point.
    #[serde(rename = "file")]
    pub file: String,
    #[serde(rename = "sparkJobEntryType")]
    pub spark_job_entry_type: models::SparkJobEntryType,
}

impl SparkJobPythonEntry {
    pub fn new(file: String, spark_job_entry_type: models::SparkJobEntryType) -> SparkJobPythonEntry {
        SparkJobPythonEntry {
            file,
            spark_job_entry_type,
        }
    }
}

