/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StackEnsembleSettings : Advances setting to customize StackEnsemble run.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StackEnsembleSettings {
    /// Optional parameters to pass to the initializer of the meta-learner.
    #[serde(
        rename = "stackMetaLearnerKWargs",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub stack_meta_learner_k_wargs: Option<Option<serde_json::Value>>,
    /// Specifies the proportion of the training set (when choosing train and validation type of training) to be reserved for training the meta-learner. Default value is 0.2.
    #[serde(
        rename = "stackMetaLearnerTrainPercentage",
        skip_serializing_if = "Option::is_none"
    )]
    pub stack_meta_learner_train_percentage: Option<f64>,
    #[serde(
        rename = "stackMetaLearnerType",
        skip_serializing_if = "Option::is_none"
    )]
    pub stack_meta_learner_type: Option<models::StackMetaLearnerType>,
}

impl StackEnsembleSettings {
    /// Advances setting to customize StackEnsemble run.
    pub fn new() -> StackEnsembleSettings {
        StackEnsembleSettings {
            stack_meta_learner_k_wargs: None,
            stack_meta_learner_train_percentage: None,
            stack_meta_learner_type: None,
        }
    }
}
