/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// StochasticOptimizer : Stochastic optimizer for image models.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
pub enum StochasticOptimizer {
    #[serde(rename = "None")]
    #[default]
    None,
    #[serde(rename = "Sgd")]
    Sgd,
    #[serde(rename = "Adam")]
    Adam,
    #[serde(rename = "Adamw")]
    Adamw,
}

impl std::fmt::Display for StochasticOptimizer {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::None => write!(f, "None"),
            Self::Sgd => write!(f, "Sgd"),
            Self::Adam => write!(f, "Adam"),
            Self::Adamw => write!(f, "Adamw"),
        }
    }
}

impl std::str::FromStr for StochasticOptimizer {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "None" => Ok(Self::None),
            "Sgd" => Ok(Self::Sgd),
            "Adam" => Ok(Self::Adam),
            "Adamw" => Ok(Self::Adamw),
            _ => Err(format!("Invalid StochasticOptimizer: {}", s)),
        }
    }
}
