/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SweepJobLimits : Sweep Job limit class.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SweepJobLimits {
    /// Sweep Job max concurrent trials.
    #[serde(rename = "maxConcurrentTrials", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_concurrent_trials: Option<Option<i32>>,
    /// Sweep Job max total trials.
    #[serde(rename = "maxTotalTrials", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_total_trials: Option<Option<i32>>,
    /// Sweep Job Trial timeout value.
    #[serde(rename = "trialTimeout", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub trial_timeout: Option<Option<String>>,
    #[serde(rename = "jobLimitsType")]
    pub job_limits_type: models::JobLimitsType,
    /// The max run duration in ISO 8601 format, after which the job will be cancelled. Only supports duration with precision as low as Seconds.
    #[serde(rename = "timeout", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<Option<String>>,
}

impl SweepJobLimits {
    /// Sweep Job limit class.
    pub fn new(job_limits_type: models::JobLimitsType) -> SweepJobLimits {
        SweepJobLimits {
            max_concurrent_trials: None,
            max_total_trials: None,
            trial_timeout: None,
            job_limits_type,
            timeout: None,
        }
    }
}

