/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// SystemData : Metadata pertaining to creation and last modification of the resource.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SystemData {
    /// The identity that created the resource.
    #[serde(rename = "createdBy", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
    /// The type of identity that created the resource.
    #[serde(rename = "createdByType", skip_serializing_if = "Option::is_none")]
    pub created_by_type: Option<CreatedByType>,
    /// The timestamp of resource creation (UTC).
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// The identity that last modified the resource.
    #[serde(rename = "lastModifiedBy", skip_serializing_if = "Option::is_none")]
    pub last_modified_by: Option<String>,
    /// The type of identity that last modified the resource.
    #[serde(rename = "lastModifiedByType", skip_serializing_if = "Option::is_none")]
    pub last_modified_by_type: Option<LastModifiedByType>,
    /// The timestamp of resource last modification (UTC)
    #[serde(rename = "lastModifiedAt", skip_serializing_if = "Option::is_none")]
    pub last_modified_at: Option<String>,
}

impl SystemData {
    /// Metadata pertaining to creation and last modification of the resource.
    pub fn new() -> SystemData {
        SystemData {
            created_by: None,
            created_by_type: None,
            created_at: None,
            last_modified_by: None,
            last_modified_by_type: None,
            last_modified_at: None,
        }
    }
}
/// The type of identity that created the resource.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CreatedByType {
    #[serde(rename = "User")]
    User,
    #[serde(rename = "Application")]
    Application,
    #[serde(rename = "ManagedIdentity")]
    ManagedIdentity,
    #[serde(rename = "Key")]
    Key,
}

impl Default for CreatedByType {
    fn default() -> CreatedByType {
        Self::User
    }
}
/// The type of identity that last modified the resource.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LastModifiedByType {
    #[serde(rename = "User")]
    User,
    #[serde(rename = "Application")]
    Application,
    #[serde(rename = "ManagedIdentity")]
    ManagedIdentity,
    #[serde(rename = "Key")]
    Key,
}

impl Default for LastModifiedByType {
    fn default() -> LastModifiedByType {
        Self::User
    }
}
