/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TableVerticalFeaturizationSettings : Featurization Configuration.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TableVerticalFeaturizationSettings {
    /// These transformers shall not be used in featurization.
    #[serde(
        rename = "blockedTransformers",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub blocked_transformers: Option<Option<Vec<models::BlockedTransformers>>>,
    /// Dictionary of column name and its type (int, float, string, datetime etc).
    #[serde(
        rename = "columnNameAndTypes",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub column_name_and_types: Option<Option<std::collections::HashMap<String, String>>>,
    /// Determines whether to use Dnn based featurizers for data featurization.
    #[serde(
        rename = "enableDnnFeaturization",
        skip_serializing_if = "Option::is_none"
    )]
    pub enable_dnn_featurization: Option<bool>,
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<models::FeaturizationMode>,
    /// User can specify additional transformers to be used along with the columns to which it would be applied and parameters for the transformer constructor.
    #[serde(
        rename = "transformerParams",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub transformer_params:
        Option<Option<std::collections::HashMap<String, Vec<models::ColumnTransformer>>>>,
    /// Dataset language, useful for the text data.
    #[serde(
        rename = "datasetLanguage",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub dataset_language: Option<Option<String>>,
}

impl TableVerticalFeaturizationSettings {
    /// Featurization Configuration.
    pub fn new() -> TableVerticalFeaturizationSettings {
        TableVerticalFeaturizationSettings {
            blocked_transformers: None,
            column_name_and_types: None,
            enable_dnn_featurization: None,
            mode: None,
            transformer_params: None,
            dataset_language: None,
        }
    }
}
