/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// TargetLagsMode : Target lags selection modes.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
pub enum TargetLagsMode {
    #[serde(rename = "Auto")]
    #[default]
    Auto,
    #[serde(rename = "Custom")]
    Custom,
}

impl std::fmt::Display for TargetLagsMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Auto => write!(f, "Auto"),
            Self::Custom => write!(f, "Custom"),
        }
    }
}

impl std::str::FromStr for TargetLagsMode {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Auto" => Ok(Self::Auto),
            "Custom" => Ok(Self::Custom),
            _ => Err(format!("Invalid TargetLagsMode: {}", s)),
        }
    }
}
