/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TargetLags : The number of past periods to lag from the target column.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "mode")]
pub enum TargetLags {
    #[serde(rename="AutoTargetLags")]
    AutoTargetLags {
    },
    #[serde(rename="CustomTargetLags")]
    CustomTargetLags {
    },
}

impl Default for TargetLags {
    fn default() -> Self {
        Self::AutoTargetLags {
        }
        
    }
}


