/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// TargetAggregationFunction : Target aggregate function.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum TargetAggregationFunction {
    #[serde(rename = "None")]
    None,
    #[serde(rename = "Sum")]
    Sum,
    #[serde(rename = "Max")]
    Max,
    #[serde(rename = "Min")]
    Min,
    #[serde(rename = "Mean")]
    Mean,
}

impl Default for TargetAggregationFunction {
    fn default() -> Self {
        Self::None
    }
}

impl std::fmt::Display for TargetAggregationFunction {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::None => write!(f, "None"),
            Self::Sum => write!(f, "Sum"),
            Self::Max => write!(f, "Max"),
            Self::Min => write!(f, "Min"),
            Self::Mean => write!(f, "Mean"),
        }
    }
}

impl std::str::FromStr for TargetAggregationFunction {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "None" => Ok(Self::None),
            "Sum" => Ok(Self::Sum),
            "Max" => Ok(Self::Max),
            "Min" => Ok(Self::Min),
            "Mean" => Ok(Self::Mean),
            _ => Err(format!("Invalid TargetAggregationFunction: {}", s)),
        }
    }
}
