/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// TaskType : AutoMLJob Task type.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub enum TaskType {
    #[serde(rename = "Classification")]
    Classification,
    #[serde(rename = "Regression")]
    Regression,
    #[serde(rename = "Forecasting")]
    Forecasting,
    #[serde(rename = "ImageClassification")]
    ImageClassification,
    #[serde(rename = "ImageClassificationMultilabel")]
    ImageClassificationMultilabel,
    #[serde(rename = "ImageObjectDetection")]
    ImageObjectDetection,
    #[serde(rename = "ImageInstanceSegmentation")]
    ImageInstanceSegmentation,
    #[serde(rename = "TextClassification")]
    TextClassification,
    #[serde(rename = "TextClassificationMultilabel")]
    TextClassificationMultilabel,
    #[serde(rename = "TextNER")]
    TextNER,
}

impl Default for TaskType {
    fn default() -> Self {
        Self::Classification
    }
}

impl std::fmt::Display for TaskType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Classification => write!(f, "Classification"),
            Self::Regression => write!(f, "Regression"),
            Self::Forecasting => write!(f, "Forecasting"),
            Self::ImageClassification => write!(f, "ImageClassification"),
            Self::ImageClassificationMultilabel => write!(f, "ImageClassificationMultilabel"),
            Self::ImageObjectDetection => write!(f, "ImageObjectDetection"),
            Self::ImageInstanceSegmentation => write!(f, "ImageInstanceSegmentation"),
            Self::TextClassification => write!(f, "TextClassification"),
            Self::TextClassificationMultilabel => write!(f, "TextClassificationMultilabel"),
            Self::TextNER => write!(f, "TextNER"),
        }
    }
}

impl std::str::FromStr for TaskType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Classification" => Ok(Self::Classification),
            "Regression" => Ok(Self::Regression),
            "Forecasting" => Ok(Self::Forecasting),
            "ImageClassification" => Ok(Self::ImageClassification),
            "ImageClassificationMultilabel" => Ok(Self::ImageClassificationMultilabel),
            "ImageObjectDetection" => Ok(Self::ImageObjectDetection),
            "ImageInstanceSegmentation" => Ok(Self::ImageInstanceSegmentation),
            "TextClassification" => Ok(Self::TextClassification),
            "TextClassificationMultilabel" => Ok(Self::TextClassificationMultilabel),
            "TextNER" => Ok(Self::TextNER),
            _ => Err(format!("Invalid TaskType: {}", s)),
        }
    }
}
