/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TextClassificationMultilabel : Text Classification Multilabel task in AutoML NLP vertical.  NLP - Natural Language Processing.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TextClassificationMultilabel {
    #[serde(rename = "primaryMetric", skip_serializing_if = "Option::is_none")]
    pub primary_metric: Option<models::ClassificationMultilabelPrimaryMetrics>,
    #[serde(rename = "featurizationSettings", skip_serializing_if = "Option::is_none")]
    pub featurization_settings: Option<Box<models::NlpVerticalFeaturizationSettings>>,
    #[serde(rename = "limitSettings", skip_serializing_if = "Option::is_none")]
    pub limit_settings: Option<Box<models::NlpVerticalLimitSettings>>,
    #[serde(rename = "validationData", skip_serializing_if = "Option::is_none")]
    pub validation_data: Option<Box<models::MlTableJobInput>>,
    #[serde(rename = "logVerbosity", skip_serializing_if = "Option::is_none")]
    pub log_verbosity: Option<models::LogVerbosity>,
    /// Target column name: This is prediction values column.  Also known as label column name in context of classification tasks.
    #[serde(rename = "targetColumnName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub target_column_name: Option<Option<String>>,
    #[serde(rename = "taskType")]
    pub task_type: models::TaskType,
    #[serde(rename = "trainingData")]
    pub training_data: Box<models::MlTableJobInput>,
}

impl TextClassificationMultilabel {
    /// Text Classification Multilabel task in AutoML NLP vertical.  NLP - Natural Language Processing.
    pub fn new(task_type: models::TaskType, training_data: models::MlTableJobInput) -> TextClassificationMultilabel {
        TextClassificationMultilabel {
            primary_metric: None,
            featurization_settings: None,
            limit_settings: None,
            validation_data: None,
            log_verbosity: None,
            target_column_name: None,
            task_type,
            training_data: Box::new(training_data),
        }
    }
}

