/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TopNFeaturesByAttribution {
    /// The number of top features to include.
    #[serde(rename = "top", skip_serializing_if = "Option::is_none")]
    pub top: Option<i32>,
    #[serde(rename = "filterType")]
    pub filter_type: models::MonitoringFeatureFilterType,
}

impl TopNFeaturesByAttribution {
    pub fn new(filter_type: models::MonitoringFeatureFilterType) -> TopNFeaturesByAttribution {
        TopNFeaturesByAttribution {
            top: None,
            filter_type,
        }
    }
}
