/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TrialComponent : Trial component definition.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrialComponent {
    /// ARM resource ID of the code asset.
    #[serde(rename = "codeId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub code_id: Option<Option<String>>,
    /// [Required] The command to execute on startup of the job. eg. \"python train.py\"
    #[serde(rename = "command")]
    pub command: String,
    #[serde(rename = "distribution", skip_serializing_if = "Option::is_none")]
    pub distribution: Option<Box<models::DistributionConfiguration>>,
    /// [Required] The ARM resource ID of the Environment specification for the job.
    #[serde(rename = "environmentId")]
    pub environment_id: String,
    /// Environment variables included in the job.
    #[serde(rename = "environmentVariables", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub environment_variables: Option<Option<std::collections::HashMap<String, String>>>,
    #[serde(rename = "resources", skip_serializing_if = "Option::is_none")]
    pub resources: Option<Box<models::JobResourceConfiguration>>,
}

impl TrialComponent {
    /// Trial component definition.
    pub fn new(command: String, environment_id: String) -> TrialComponent {
        TrialComponent {
            code_id: None,
            command,
            distribution: None,
            environment_id,
            environment_variables: None,
            resources: None,
        }
    }
}

