/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "triggerType")]
pub enum TriggerBase {
    #[serde(rename = "CronTrigger")]
    CronTrigger {
        /// Specifies end time of schedule in ISO 8601, but without a UTC offset. Refer https://en.wikipedia.org/wiki/ISO_8601.  Recommented format would be \"2022-06-01T00:00:01\"  If not present, the schedule will run indefinitely
        #[serde(rename = "endTime", skip_serializing_if = "Option::is_none")]
        end_time: Option<String>,
        /// Specifies start time of schedule in ISO 8601 format, but without a UTC offset.
        #[serde(rename = "startTime", skip_serializing_if = "Option::is_none")]
        start_time: Option<String>,
        /// Specifies time zone in which the schedule runs.  TimeZone should follow Windows time zone format. Refer: https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/default-time-zones?view=windows-11
        #[serde(rename = "timeZone", skip_serializing_if = "Option::is_none")]
        time_zone: Option<String>,
    },
    #[serde(rename = "RecurrenceTrigger")]
    RecurrenceTrigger {
        /// Specifies end time of schedule in ISO 8601, but without a UTC offset. Refer https://en.wikipedia.org/wiki/ISO_8601.  Recommented format would be \"2022-06-01T00:00:01\"  If not present, the schedule will run indefinitely
        #[serde(rename = "endTime", skip_serializing_if = "Option::is_none")]
        end_time: Option<String>,
        /// Specifies start time of schedule in ISO 8601 format, but without a UTC offset.
        #[serde(rename = "startTime", skip_serializing_if = "Option::is_none")]
        start_time: Option<String>,
        /// Specifies time zone in which the schedule runs.  TimeZone should follow Windows time zone format. Refer: https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/default-time-zones?view=windows-11
        #[serde(rename = "timeZone", skip_serializing_if = "Option::is_none")]
        time_zone: Option<String>,
    },
}

impl Default for TriggerBase {
    fn default() -> Self {
        Self::CronTrigger {
            end_time: Default::default(),
            start_time: Default::default(),
            time_zone: Default::default(),
        }
    }
}
