/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// TriggerType : TriggerType enum
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
pub enum TriggerType {
    #[serde(rename = "Recurrence")]
    #[default]
    Recurrence,
    #[serde(rename = "Cron")]
    Cron,
}

impl std::fmt::Display for TriggerType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Recurrence => write!(f, "Recurrence"),
            Self::Cron => write!(f, "Cron"),
        }
    }
}

impl std::str::FromStr for TriggerType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Recurrence" => Ok(Self::Recurrence),
            "Cron" => Ok(Self::Cron),
            _ => Err(format!("Invalid TriggerType: {}", s)),
        }
    }
}
