/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TruncationSelectionPolicy : Defines an early termination policy that cancels a given percentage of runs at each evaluation interval.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TruncationSelectionPolicy {
    /// The percentage of runs to cancel at each evaluation interval.
    #[serde(rename = "truncationPercentage", skip_serializing_if = "Option::is_none")]
    pub truncation_percentage: Option<i32>,
    /// Number of intervals by which to delay the first evaluation.
    #[serde(rename = "delayEvaluation", skip_serializing_if = "Option::is_none")]
    pub delay_evaluation: Option<i32>,
    /// Interval (number of runs) between policy evaluations.
    #[serde(rename = "evaluationInterval", skip_serializing_if = "Option::is_none")]
    pub evaluation_interval: Option<i32>,
    #[serde(rename = "policyType")]
    pub policy_type: models::EarlyTerminationPolicyType,
}

impl TruncationSelectionPolicy {
    /// Defines an early termination policy that cancels a given percentage of runs at each evaluation interval.
    pub fn new(policy_type: models::EarlyTerminationPolicyType) -> TruncationSelectionPolicy {
        TruncationSelectionPolicy {
            truncation_percentage: None,
            delay_evaluation: None,
            evaluation_interval: None,
            policy_type,
        }
    }
}

