/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UriFolderJobOutput {
    #[serde(rename = "mode", skip_serializing_if = "Option::is_none")]
    pub mode: Option<models::OutputDeliveryMode>,
    /// Output Asset URI.
    #[serde(rename = "uri", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub uri: Option<Option<String>>,
    /// Description for the output.
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "jobOutputType")]
    pub job_output_type: models::JobOutputType,
}

impl UriFolderJobOutput {
    pub fn new(job_output_type: models::JobOutputType) -> UriFolderJobOutput {
        UriFolderJobOutput {
            mode: None,
            uri: None,
            description: None,
            job_output_type,
        }
    }
}

