/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 * 
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// UserAssignedIdentity : User assigned identity properties
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserAssignedIdentity {
    /// The principal ID of the assigned identity.
    #[serde(rename = "principalId", skip_serializing_if = "Option::is_none")]
    pub principal_id: Option<uuid::Uuid>,
    /// The client ID of the assigned identity.
    #[serde(rename = "clientId", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<uuid::Uuid>,
}

impl UserAssignedIdentity {
    /// User assigned identity properties
    pub fn new() -> UserAssignedIdentity {
        UserAssignedIdentity {
            principal_id: None,
            client_id: None,
        }
    }
}

