/*
 * Azure Machine Learning Services
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-09-01
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// ValidationMetricType : Metric computation method to use for validation metrics in image tasks.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
pub enum ValidationMetricType {
    #[serde(rename = "None")]
    #[default]
    None,
    #[serde(rename = "Coco")]
    Coco,
    #[serde(rename = "Voc")]
    Voc,
    #[serde(rename = "CocoVoc")]
    CocoVoc,
}

impl std::fmt::Display for ValidationMetricType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::None => write!(f, "None"),
            Self::Coco => write!(f, "Coco"),
            Self::Voc => write!(f, "Voc"),
            Self::CocoVoc => write!(f, "CocoVoc"),
        }
    }
}

impl std::str::FromStr for ValidationMetricType {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "None" => Ok(Self::None),
            "Coco" => Ok(Self::Coco),
            "Voc" => Ok(Self::Voc),
            "CocoVoc" => Ok(Self::CocoVoc),
            _ => Err(format!("Invalid ValidationMetricType: {}", s)),
        }
    }
}
