[package]
name = "fora_cli"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"

[[bin]]
name = "fora"
path = "src/main.rs"

[dependencies]
azure_ml = { path = "../azure_ml" }
azure_tui = { path = "../azure_tui" }
azure_core = { workspace = true }
azure_identity = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
clap = { version = "4.4", features = ["derive", "color"] }
anyhow = "1.0"
serde_json = "1.0"
regex = "1.12.3"
thiserror.workspace = true
anstyle = "1.0.13"
azure_storage_blob = "0.9.0"
ignore = "0.4.25"
url.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
sled = "0.34.7"
uuid.workspace = true
zip = "8.2.0"
rayon = "1.11.0"
reqwest.workspace = true
globset = "0.4.18"
blake3 = "1.8.3"
async-trait.workspace = true
names = "0.14.0"
